### ISSUE TITLE
how to run uncompyle6?

### ISSUE THREAD

**Issue by drunkwolfs** [rocky/python-uncompyle6#10]
win7
Python34

```
>python34 uncompyle6 -h
  File "uncompyle6", line 52
    program =  os.path.basename(__file__)
          ^
SyntaxError: invalid syntax
```

**Comment by rocky** [comment]
From README.rst: 

> It accepts bytecodes from Python version 2.5 to 3.4 or so, It has been *tested on Python running versions 2.6, 2.7, 3.3, 3.4 and 3.5.*

I'll update the readme to be clearer. You need at least Python 2.6 to play this game.

**Comment by rocky** [comment]
Sorry misread 34 as 24. https://github.com/rocky/python-uncompyle6/commit/feec241da88107b97bbdfbabeb3ae7131a7aa923 fixes this problem and there will soon be another release.
