### ISSUE TITLE
Another EXTENDED_ARG error probably due to optimization

### ISSUE THREAD

**Issue by Zm908** [rocky/python-uncompyle6#102]
[EXTENDED_ARG_2.zip](https://github.com/rocky/python-uncompyle6/files/923827/EXTENDED_ARG_2.zip)

**Comment by Zm908** [comment]
BTW, test/simple_source/bug36/01_if_file.py testcase doesn't produce EXTENDED_ARG opcode and thus a bug

**Comment by rocky** [comment]
No, it is not a bug. It is wrong to think that that compiling a decompiled program will always give the same bytecode. The correct measure is only whether the two are _semenatically_ equivalent. Reread the README.rst for examples.
