### ISSUE TITLE
COME_FROM_EXCEPT_CLAUSE error

### ISSUE THREAD

**Issue by Zm908** [rocky/python-uncompyle6#105]
[COME_FROM_EXCEPT_CLAUSE.zip](https://github.com/rocky/python-uncompyle6/files/926473/COME_FROM_EXCEPT_CLAUSE.zip)

**Comment by rocky** [comment]
Not sure when this started working, but it is working in git now.

**Comment by Carlos272** [comment]
HI ROCKY, how are you? I really need a help.

I'm using the last version's uncompyle6 and I got a problem that is show below. 

Parse error at or near `COME_FROM_EXCEPT_CLAUSE' instruction at offset 9739_0

 928    9669  LOAD_GLOBAL              'print'
        9672  LOAD_CONST               '[{} - {}] 3 Error json={}'
        9675  LOAD_ATTR                'format'
        9678  LOAD_GLOBAL              'datetime'
        9681  LOAD_ATTR                'now'
        9684  CALL_FUNCTION_0       0  '0 positional, 0 keyword pair'
        9687  LOAD_FAST                'req_ip'
        9690  LOAD_GLOBAL              'request'
        9693  LOAD_ATTR                'json'
        9696  CALL_FUNCTION_3       3  '3 positional, 0 keyword pair'
        9699  LOAD_CONST               'flush'
        9702  LOAD_CONST            1  True
        9705  CALL_FUNCTION_257   257  '1 positional, 1 keyword pair'
        9708  POP_TOP          

 929    9709  LOAD_GLOBAL              'cerrar_conexion'
        9712  LOAD_FAST                'psql_db'
        9715  CALL_FUNCTION_1       1  '1 positional, 0 keyword pair'
        9718  POP_TOP          

 930    9719  LOAD_GLOBAL              'json'
        9722  LOAD_ATTR                'dumps'
        9725  BUILD_MAP_1           1  ''
        9728  LOAD_CONST               '2-datos incorrecto'
        9731  LOAD_CONST               'respuesta'
        9734  STORE_MAP        
        9735  CALL_FUNCTION_1       1  '1 positional, 0 keyword pair'
        9738  RETURN_VALUE     
      **9739_0  COME_FROM_EXCEPT_CLAUSE  9567  '9567'**
        9739  JUMP_FORWARD       9812  'to 9812'
        9742  ELSE                     '9812'
