### ISSUE TITLE
Several errors related to lambda *,a=a0

### ISSUE THREAD

**Issue by Zm908** [rocky/python-uncompyle6#110]
[LAMBDA.zip](https://github.com/rocky/python-uncompyle6/files/926527/LAMBDA.zip)

I think all these errors are due to insufficient handling of the aforementioned syntax. The errors are grouped into:

- the lambda itself. Error MAKE_FUNCTION_N1_0

- simple value construction (list, tuple, set, dict). Errors BUILD_LIST_1, BUILD_TUPLE_1, BUILD_SET_1, BUILD_MAP_1

- comprehensions. Errors LIST_APPEND, POP_TOP, SET_ADD, MAP_ADD

- inside with statement. Errors POP_TOP, STORE_FAST, STORE_NAME

**Comment by rocky** [comment]
It would be helpful if these were broken out into separate issues. The with multiple bugs in a single issue is that it is harder for me to track what's been done and what remains to be done. I may get drips and drabs of free time to work on this, so no way could I handle of the issues in say one sitting.

**Comment by rocky** [comment]
e500869 might fix everything. If it doesn't please file separate individual tickets. Thanks.

**Comment by Zm908** [comment]
e500869 fixed all the related errors
