### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by testnameC09** [rocky/python-uncompyle6#12]
Instalation python-2.7.2.msi (md5=44c8bbe92b644d78dd49e18df354386f).
Unpack  python-uncompyle6-master.zip (https://codeload.github.com/rocky/python-uncompyle6/zip/master) , put bat-file 
C:\Python27\python.exe setup.py install
in same folder where setup.py (in my case "I:\anime\python-uncompyle6-master\python-uncompyle6-master\")
After running bat-file I get :

I:\anime\python-uncompyle6-master\python-uncompyle6-master>C:\Python27\python.ex
e setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    __import__('pkg_resources')
ImportError: No module named pkg_resources

**Comment by testnameC09** [comment]
Also if I use pip as  README.rst says , I get 
pip not a recognized as an internal or external command,operable program or batch file

**Comment by rocky** [comment]
> ImportError: No module named pkg_resources

Sewe http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

But I don't think I need line 11 anyway, so try removing that. If that works, I'll remove it from the source code. 

Try googling "pip not a recognized as an internal or external command,operable program or batch file"

In general, learn to use the google.

**Comment by testnameC09** [comment]
comented line 11, bat-file output:


I:\anime\python-uncompyle6-master\python-uncompyle6-master>C:\Python27\python.ex
e setup.py install
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from setuptools import setup
ImportError: No module named setuptools

I:\anime\python-uncompyle6-master\python-uncompyle6-master>C:\Python27\python.ex
e setup.py develop
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from setuptools import setup
ImportError: No module named setuptools

coment line 11 and 12 , bat-file output:

I:\anime\python-uncompyle6-master\python-uncompyle6-master>C:\Python27\python.ex
e setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setup(
NameError: name 'setup' is not defined

I:\anime\python-uncompyle6-master\python-uncompyle6-master>C:\Python27\python.ex
e setup.py develop
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setup(
NameError: name 'setup' is not defined

**Comment by testnameC09** [comment]
I'm not programmer. I looked in google, but didn't understand anything. So pip and setuptools are additional third-party packages. So you need to write down these to requirements , as clean python is not enough. And you  need write detailed instructions how to bring your uncompyle6 work with clean python.

**Comment by rocky** [comment]
This project has a [wiki](https://github.com/rocky/python-uncompyle6/wiki) where people such as yourself can contribute information, explanations,  or instructions. 

As a non-programmer who is unfamiliar with Python, you are most uniquely qualified to explain such things that confused you, and explain to others who may be in this situation how to fix.

Perhaps you could you create a new page like "Installation on windows 7 with Python 2.7" describing those additional things you needed to do. Thanks.
