### ISSUE TITLE
'charmap' codec can't encode character '\xb4' in position

### ISSUE THREAD

**Issue by KhArtNJava** [rocky/python-uncompyle6#121]
# uncompyle6 version 2.10.1
# Python bytecode 3.3 (3230)
# Decompiled from: Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:37:12) [MSC v.1600 32 bit (Intel)]
# Embedded file name: resurrectcheat.py
# Compiled at: 2014-12-28 20:57:54
# Size of source mod 2**32: 1048 bytes

# file c:\Art\Projects\Experiments\q\resurrectcheat.pyc
# 'charmap' codec can't encode character '\xb4' in position 556: character maps to <undefined>

File is here:
https://mega.nz/#!txdSESCZ!pHO_xVGZqlTZYmj-q1AJ2ZakieyPFVDIgipaEC6i1-s

**Comment by rocky** [comment]
Works for me on linux: 
```
$ ./bin/uncompyle6 ~/Downloads/resurrectcheat.pyc 
# uncompyle6 version 2.10.1
# Python bytecode 3.3 (3230)
# Decompiled from: Python 3.6.1 (default, Apr 20 2017, 12:43:56) 
# [GCC 5.4.0 20160609]
# Embedded file name: resurrectcheat.py
# Compiled at: 2014-12-28 12:57:54
# Size of source mod 2**32: 1048 bytes
import services
import sims4.commands
import sims4.tuning.tunable
import tag
import traits.traits

@sims4.commands.Command('resurrectsim', command_type=sims4.commands.CommandType.Live)
def get_resurrect_data(first_name='', last_name='', _connection=None):
    info = services.sim_info_manager().get_sim_info_by_name(first_name, last_name)
    output = sims4.commands.CheatOutput(_connection)
    if info is not None:
        output('Resurrected sim succesfully. If you want to disable all deaths, please, run the command death.toggle and you won´t never die. THANK YOU FOR USING -fer456')
        info.trait_tracker.remove_traits_of_type(traits.traits.TraitType.GHOST)
        info.death_tracker.clear_death_type(info)
        info.update_age_callbacks(info)
        sim = info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS)
        if sim is not None:
            sim.routing_context.ghost_route = False
    output('Sim not found. Do you wrote correctly the name?. Check also you haven´t liberated that spirit in the urnstone.THANK YOU FOR USING -fer456')
    return True
# okay decompiling /home/rocky/Downloads/resurrectcheat.pyc
```

**Comment by rocky** [comment]
Also, in the future give the exact command you ran.

**Comment by KhArtNJava** [comment]
Downloaded with git from https://github.com/rocky/python-uncompyle6.git .
Installed on Python 3.3.5, Windows 10 x64, with commands

pip install -e .
pip install -r requirements-dev.txt
python setup.py install # may need sudo

Started decompiling with

**Comment by rocky** [comment]
Must be a Windows thing then. Python usually gives a traceback when it hits and error.  Did it here?

**Comment by KhArtNJava** [comment]
No. Error, that I got from it, is in the first post of this thread. No, it didn't show trace...

**Comment by rocky** [comment]
I'm assuming your setup is messed up and or this is a windows thing. At some point in the vague future, I'll try running on Windows, or maybe we can wait for someone else who uses windows to scope out what the problem is. 

You can try running py.test to see if the tests check out. Install some sort of GNU make such as from mingw and probably you can then try running "make check".
