### ISSUE TITLE
Parse error. Instruction context JUMP_BACK (after continue) with clause elif.

### ISSUE THREAD

**Issue by phonexicum** [rocky/python-uncompyle6#122]
While using `uncompyle6` for decompilation of `.pyo` files I run into parse error. The file was too big, so I tried to reproduce for you the same parse error on small example and succeeded.

Here is version information:
``` bash
phoenix@xxxxxx:~/Desktop/bug$ uname -a
Linux xxxxxx 4.8.0-kali2-amd64 #1 SMP Debian 4.8.15-1kali1 (2016-12-23) x86_64 GNU/Linux
phoenix@xxxxxx:~/Desktop/bug$ python --version
Python 2.7.13
phoenix@xxxxxx:~/Desktop/bug$ uncompyle6 --version
uncompyle6 2.10.1
```

This is small python code example for reproducing parse error:
``` python
#! /usr/bin/python

s = [i for i in xrange(5)]

def func():

    for i in s:
        
        if i == 3:
            print 0
        elif i == 4:
            print 1
        else:
            continue

        if len(s) % 2 == 0:
            print 'even'
        else:
            print 'aaa'

    print 'end'

func()

```

Here I compile the code into `.pyo` byte-code and uncompyle it afterward with parse error:
``` bash
phoenix@xxxxxx:~/Desktop/bug$ python test.py
0
odd
1
odd
end
phoenix@xxxxxx:~/Desktop/bug$ python -O -m py_compile test.py 
phoenix@xxxxxx:~/Desktop/bug$ python test.pyo
0
odd
1
odd
end
phoenix@xxxxxx:~/Desktop/bug$ uncompyle6 -o test-uncompile.py test.pyo
Instruction context:
   
  14      53  JUMP_BACK             7  'to 7'
->         56_0  COME_FROM                '50'
           56_1  COME_FROM                '30'


# file test.pyo
# Deparsing stopped due to parse error
decompiled 0 files: 0 okay, 1 failed
phoenix@xxxxxx:~/Desktop/bug$
```

For bug reproduction it is important to have clauses `elif` and `continue`. Checks are insignificant, that was just some semantics to write some code around.

**Comment by rocky** [comment]
Thanks for stripping this down and the detailed analysis. It greatly reduced the time to work out the problem. (By the way, the venerable uncompyle2 doesn't have this bug.)

Commit 0893652 fixes this, although it is possible it introduces a 1% failure rate elsewhere. (I'm not totally certain, but it could). 

Not until uncompyle6 has full-scale control-flow analysis will this be fully addressed. And more than half of the bug requests here are control-flow problems.
