### ISSUE TITLE
How to pass parameters in this codes

### ISSUE THREAD

**Issue by mfaraj57** [rocky/python-uncompyle6#125]
First thanks for excellent work
after several failed trials and time consuming to reverse my lost 10 py files with uncompyle2,easy decompiler and others,i succeeded with uncompyle6
now i used this code in windows python IDLE and produce the reversed code successfully in python shell
how to direct output to py file with same name in directory of pyo file
`# -*- coding: utf-8 -*-
import sys

import os,inspect

import inspect, os
dfile =inspect.getfile(inspect.currentframe()) # script filename (usually with path)
dpath = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))) # script directory

######################################

######################################

sys.argv=[]
sys.argv.append(dfile)
sys.argv.append(dpath+"\\"+"plugindb6.pyo")

import uncompyle6

from uncompyle6.bin.uncompile import main_bin
main_bin()
`
i could not follow the main_bin function due to my limitation in python
regards

**Comment by rocky** [comment]
Thanks for the kind words. 

The decompile a file without using the command-line, use [decompile_file].(https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/main.py#L54)

Somethng like: 

```
from uncompyle6.main import decompile_file
with outstream=open('source.py', 'w'): 
  decompile_file(depath, outstream)
```

**Comment by rocky** [comment]
This kind of help request is better suited for asking on StackOverflow than as an issue. I'm closing this. If you have further questions, please open it on StackOverflow or an equivalent. (I think Quora also has something like this.)
