### ISSUE TITLE
Hardcoded Python path in last release

### ISSUE THREAD

**Issue by jezdez** [rocky/python-uncompyle6#13]
When I install from PyPI and try to un uncompyle6 I get:

```console
$ uncompyle6 
/usr/local/Cellar/pyenv/20160422/libexec/pyenv-exec: /usr/local/var/pyenv/versions/2.7.11/bin/uncompyle6: /home/rocky/.pyenv/versions/3.5.1/bin/python: bad interpreter: No such file or directory
/usr/local/Cellar/pyenv/20160422/libexec/pyenv-exec: line 47: /usr/local/var/pyenv/versions/2.7.11/bin/uncompyle6: Undefined error: 0
$
```

As you can see I'm using pyenv, but I think something went wrong when building the whl file or something, that it hardcoded the `/home/rocky/.pyenv/versions/3.5.1/bin/python` path. Any idea how to fix it?

**Comment by Tey** [comment]
Same issue here. I installed uncompyle6 using pip (`pip install uncompyle6`) on Cygwin but the shebang is hardcoded:
```
$ head /usr/bin/uncompyle6
#!/home/rocky/.pyenv/versions/3.5.1/bin/python
# Mode: -*- python -*-
#
# Copyright (c) 2015-2016 by Rocky Bernstein
# Copyright (c) 2000-2002 by hartmut Goebel <h.goebel@crazy-compilers.com>
#
from __future__ import print_function
import sys, os, getopt, time

program =  os.path.basename(__file__)
```
```
$ head /usr/bin/pydisassemble
#!/home/rocky/.pyenv/versions/3.5.1/bin/python
# Mode: -*- python -*-
#
# Copyright (c) 2015-2016 by Rocky Bernstein <rb@dustyfeet.com>
#
from __future__ import print_function
import sys, os, getopt

program =  os.path.basename(__file__)
```

The version installed by pip was `uncompyle6-2.3.4-py2.py3-none-any.whl`.

> Any idea how to fix it?

@jezdez Replace the shebang in `/usr/local/var/pyenv/versions/2.7.11/bin/uncompyle6` with `#!/usr/bin/env python` and it should work.

**Comment by rocky** [comment]
Sorry for the problems. When I get a chance, I'll put out a new release with the current github changes which address some more of the Python 3 decompilation problems. 

I guess I'll be changing things package-wise along the lines of https://packaging.python.org/en/latest/distributing/#scripts in case either of you want to investigate and submit a pull request.

But as jezdez says, until then just modify the shebang line.

**Comment by Tey** [comment]
Thanks, packaging is not my cup of Tea, so I'll just wait :)

**Comment by rocky** [comment]
Should be fixed with release 2.3.6. (The name when you run uncompyle6 -V is wrong, but that will wait for another release.)

If this does it for you, just close the issue.

**Comment by Tey** [comment]
I've upgraded the package with pip, and it works for me now, thanks!

**Comment by rocky** [comment]
Good to hear. (If you star this repon it might help to draw attention away from the uncompyle2's in github that have way more stars but aren't likely to be updated anymore.)

**Comment by jezdez** [comment]
Yep, works!

**Comment by jezdez** [comment]
@rocky Also, thank you for the fix! 💐

**Comment by rocky** [comment]
Again, good to get independent confirmation. Closing this then.
