### ISSUE TITLE
Can't decompile file, a lot of errors.

### ISSUE THREAD

**Issue by KhArtNJava** [rocky/python-uncompyle6#136]
Hello.
Can't decompile file, getting a lot of errors.
Can you check it? https://mega.nz/#!EJNjTICK!BTCYBW11RpFSeCQ7KPpq_aJQ-tNrlSN6HA6Q2_oBp9c
Thank you!

**Comment by rocky** [comment]
No can't check it.  Please read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md
