### ISSUE TITLE
AssertionError: Didn't find RETURN_VALUE or END_FINALLY

### ISSUE THREAD

**Issue by CaledoniaProject** [rocky/python-uncompyle6#137]
I'm trying to process this file (rename it to pyc extension): [100004.txt](https://github.com/rocky/python-uncompyle6/files/1457357/100004.txt)

And it fails with `AssertionError: Didn't find RETURN_VALUE or END_FINALLY` error, can you help?

**Comment by rocky** [comment]
10004.txt is not valid Python bytecode and I suspect you were aware of that too. 

So what's going on and why do you feel someone should help you?

**Comment by CaledoniaProject** [comment]
And 

```
# Embedded file name: /tmp/vul/100004_phpcms_9_6_0_wap_sqli.py
# Compiled at: 2017-10-31 11:23:53

**Comment by CaledoniaProject** [comment]
Resolved. The bytecode is invalid and has nothing to do with uncompyle6.
