### ISSUE TITLE
Uncompyle6 a directory

### ISSUE THREAD

**Issue by tysondogerz** [rocky/python-uncompyle6#138]
I have about 200 pyc files I need to decompile.  I want to compile them to py files in a new folder.  I see you can do this for a folder in cmd?  Is this supported?

**Comment by rocky** [comment]
The issue tracker is not set up for general help bug is for instead for reporting bugs. And even here, there is a bit of work that is required for bug reporting. See [HOW TO REPORT A BUG]( https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md). 

For asking questions or getting help in general, [StackOverflow](https://stackoverflow.com) is one such medium that can be used for help. However, as just general etiquette and policy, before asking a question I'd show that I made a decent effort to solve my problem above say reading a help page.

**Comment by tysondogerz** [comment]
THank you.  I am just curious as no documentation.  uncompyle6 -o . 31.pyc works, but there is no mention in docs I take it that you can't decompile whole folder of pyc files?  Cheers.

**Comment by Japrajah** [comment]
```
@ECHO OFF
setlocal enabledelayedexpansion
for %%f in (common\*.pyc) do (
uncompyle6 -o .\common_decompiled %%f
)
```
