### ISSUE TITLE
Generator error and a bunch of control-flow failures (POP_TOP, COME_FROM_FINALLY, LOAD_GENEXPR)

### ISSUE THREAD

**Issue by eltrhn** [rocky/python-uncompyle6#139]
Python 3.6.4, Ubuntu 17.10. (EDIT: Wrote 3.6.3 by accident)
Here's a full decompyle6 output for the CPython binary of a file I accidentally deleted from a [discord.py](https://github.com/Rapptz/discord.py/tree/rewrite) bot:
https://gist.github.com/eltrhn/cfd862d288bb3d78e57281fe3977345b
As you can see, a lot of functions got interrupted halfway through at one of the opcodes mentioned in title, but unfortunately I don't have the original source for these to compare against.

I do, however, have the source for the failed SList class at the top, and I figure that may be of interest pertaining to this issue -- so here it is with its decompyle6 output, alongside a full disassembly of the binary (from pycdas):
https://gist.github.com/eltrhn/3d80757990c2994e8ac398e0f528e014

**Comment by rocky** [comment]
From what I can tell this might do it. 

3.6 however changes the semantics of a couple of instructions and that hasn't been addressed yet. See #58

**Comment by eltrhn** [comment]
Thanks! The \_\_rsub__ deparsing does still fail, this time with
``Parse error at or near `COME_FROM_FINALLY' instruction at offset 66_0`` -- but I assume that's a consequence of the hasn't-been-addressed-yet semantic changing that you mention?

By the way, there were sections in the first file above that I'd edited out with the comment "decompiled successfully", but after looking at them again I've noticed a minor error:
```python
foo(bar, baz=1)
foo(bar, baz, qux=1)
foo(bar, baz=1, qux=2)
foo(bar, baz, qux=1, quux=2)
```
decompiles as
```python
foo(baz=bar,)
foo(qux=bar,)
foo(baz=bar,qux=1,)
foo(qux=bar,quux=baz,)
```
instead of something like `foo(bar, baz='aaa',)`.

I'll try and start rewriting the unrecoverable bits of the file, and test decompyle6 on stuff along the way. Will post further results as new issues if anything else deserves attention

**Comment by rocky** [comment]
Text usually drops off when a node in the tree doesn't have a semantic action or doesn't treat passes over its children. Open a separate bug for this when complete source code and miscompilation. 

Let's have please just one kind of problem per issue rather than, here's all of the stuff I am trying to do. 

I need to track separate problems separately in the smallest possible pieces.
