### ISSUE TITLE
Is there a way to log errors?

### ISSUE THREAD

**Issue by tallmanDavid** [rocky/python-uncompyle6#140]
Is there a way to make this log errors?

Here's what i'm doing.
I was running this using recurse directories on a directory with almost 2000 files. When uncompyle gets to some errors. It freezes up and have to close it. 
So I created a batch for loop to do command for each file so it will finish all files that work.
But I wanted to figure out which files fail.
and all batch errorlevels give 0 on success or fail of the file this is running on.

**Comment by rocky** [comment]
It is not clear this is a bug, and it is not clear if or what feature would be helpful. 

Issues are not set up for help requests. I suggest some other medium like StackOverflow instead. 

My suggestion though if you do post this elsewhere is to give a more detail in the code you wrote, what you got and so on.
