### ISSUE TITLE
Add Syntax Tree transformation phase

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#141]
Code that currently modifies the AST would get moved to a separate phase. This includes things like

* removing fields that get hidden or modified, for example: 
   * RETURN LAST
   * \_\_doc\_\_  and other \_\_ variable settings
* code transformation like `while True: if x ..` -> `while x`

Ideally we would have a tree matching and substitution language.

**Comment by x0ret** [comment]
Some discussions about Tree transformation phase and my attempts to first learn and then implement things. Maybe these help others as well in the future.

After i read Rocky's comments in [Adding a tree transformation phase to uncompyle6](https://github.com/rocky/python-uncompyle6/wiki/Adding-a-tree-transformation-phase-to-uncompyle6#a-tree-transformation-phase-to-uncompyle6), i decided to take a look at code and see where and how to implement such a interesting thing. 

Then i landed [here](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/pysource.py#L663-L675) and said to myself "Rocky, did you try to support `elif`?" So i re-read the wiki page again and came to this 

> so this is what we want to get used instead. So what needs to get done is to write a rule in some as-yet-to-be implemented tree transformation system ...

Then changed the code a little as following diff:

```diff
diff --git a/uncompyle6/semantics/pysource.py b/uncompyle6/semantics/pysource.py
index 1cb6980d..097244c6 100644
--- a/uncompyle6/semantics/pysource.py
+++ b/uncompyle6/semantics/pysource.py
@@ -651,7 +651,9 @@ class SourceWalker(GenericASTTraversal, object):

         n = else_suite[0]

-        if len(n) == 1 == len(n[0]) and n[0] == '_stmts':
+        if len(n) == 1 == len(n[0]) and n[0] == 'stmt':
+            n = n[0][0]
+        elif len(n) == 1 == len(n[0]) and n[0] == '_stmts':
             n = n[0][0][0]
         elif n[0].kind in ('lastc_stmt', 'lastl_stmt'):
             n = n[0][0]
``` 

and happily i got this:

```python
    x = True
    y = False
    if x:
        pass
    elif x == False:
        pass
    elif not y:
        pass
```

That was easy, yeah? but Rocky told us before:

> The thing can be done stupidly by iterating over the entire tree for each kind of transform.

Indeed. 

The problem arises when we change the test case to:

```python
    x = True
    y = False
    if x:
        pass
    elif x == False and y:
        #return 1
        pass
    elif not y:
        #return 2
        pass
`` 

and we get this instead:

```python
    x = True
    y = False
    if x:
        pass
    elif x == False:
        if y:
            pass
        if not y:
            pass
``` 

Too much conditions as it seems.

So i'm still learning and try to implement what i learnt.

Anyway, @rocky are we trying to use grammer as you said at wiki page or just have a nasty implementation as diff shows in the first place? Sorry for these questions, i'm tyring to adjust my thoughts as you think about these stuffs.

Thanks.

**Comment by rocky** [comment]
uncompyle6 has been able to get where it has to support multiple versions of Python with decent quality and having a chance of continuing for future versions of Python has been because it has tried to address problems as they arise in a trackable, sensible, debuggable way.

(That is why I think the other uncompyle2, and unpy{2,3} variants will be hopelessly stuck on a single version, and even then, their often not as good. pycdc added some table-drivenness but not at enough levels. So right now it is doubtful it will ever support 3.7 or 3.8 in a decent way.)

The way I think to think about this is as an entire separate pass. That way you can dump out the tree before modification, and then dump out the tree _after_ this tree-transformation.

To get the ball rolling I made a [start at such a tree transformation](https://github.com/rocky/python-decompile3/pull/15). It is ugly, but ugly in the right way :-)

What the code attempts to do is find places where `if x: raise AssertionError` can be turned into an `assert`. It does that part of it, but it is failing somewhere because I thing the grammar customizations are not getting added.

So in things like:
```
             20  LOAD_CODE                <code_object __init__>
             22  LOAD_STR                 'BoundedSemaphore.__init__'
             24  MAKE_FUNCTION_11         'default, keyword-only, closure'
             26  STORE_NAME               __init__
             28  LOAD_CLOSURE             '__class__'
             30  DUP_TOP          
->           32  STORE_NAME               __classcell__
```
grammar parsing fails because we don't have the custom rule for `MAKE_FUNCTION_11` which needs to be added to this transform phase. (It is in the other later phase in `pysource.py` though)

I'd be grateful if that problem could be fixed. Another thing related to do after this is to handle the 2 argument assert:

```
   assert x, "This is a message"
```

And also simple is to remove this kind of tree-transformation code that is already in `pysource.py` which would be better separated and be handled in this new transform phase `transform.py`.


Any place you see something doing a `del ast[x]` like:

```
        # the function defining a class normally returns locals(); we
        # don't want this to show up in the source, thus remove the node
        if len(ast) > 0 and ast[-1][0] == RETURN_LOCALS:
            if self.hide_internal: del ast[-1] # remove last node
```

this should be done in the transform phase.

The way document strings would better be handled would be for it to be detected in the transformation phase, and then it places a fabricated _document_ astnode. Then in the later phase in `pysource.py` it sees that node and calls `print_docstring` which could be renamed `n_docstring` assuming the arguments have been set up for this.

Lastly we get to the table drivenness. Perhaps the right thing for now is just just use only functions, like `n_xxx`. After some of these have been written, I am hoping it will be clear as to how to template this to reduce the code and make the intent cleaner.

Sorry this is yet another mess. The good news though is that after this is done, this aspect will be much clearer _and_ the decompiled code will be more like what people expect.

**Comment by rocky** [comment]
This has largely been shaken down and resolved thanks to @x0ret
