### ISSUE TITLE
Control flow mis-decompile

### ISSUE THREAD

**Issue by HMPerson1** [rocky/python-uncompyle6#143]
Source code: 
```python
for x in [1,2,3]:
    if x == 1:
        print('a');
        if x % 2 == 0:
            print('b')
    else:
        print('c')
```

Uncompyle6 output:
```python
for x in (1, 2, 3):
    if x == 1:
        print('a')
    if x % 2 == 0:
        print('b')
    else:
        print('c')
```

Bytecode: [foo.cpython-36.pyc.gz](https://github.com/rocky/python-uncompyle6/files/1546035/foo.cpython-36.pyc.gz)

Versions:
- uncompyle6 2.13.2
- Python 3.6.3

**Comment by rocky** [comment]
Version 2.14.0 is the current released version where it says: 

> - Fix a number of bytecode decompile problems
>  (many more remain)

Although I haven't tried 2.14.0, this  does work properly on current git sources which will go out in a day or so.
