### ISSUE TITLE
Another control flow mis-decompile 

### ISSUE THREAD

**Issue by HMPerson1** [rocky/python-uncompyle6#144]
Original:
```python
for x in [1,2,3]:
    print('a')
    if x % 2 == 0:
        a = x
        if x == 2:
            print('b')
    else:
        print('c')
```

Uncompyle6 output:
```python
for x in [1, 2, 3]:
    print('a')
    if x % 2 == 0:
        pass
    a = x
    if x == 2:
        print('b')
    else:
        print('c')
```

Bytecode: [foo.cpython-35.pyc.gz](https://github.com/rocky/python-uncompyle6/files/1548930/foo.cpython-35.pyc.gz)

Versions:
- Python 3.5.2
- uncompyle6 2.14.1

**Comment by rocky** [comment]
Yeah, this one I've seen before. A lot. 

The basic flaw is some rather custom code that is putting "COME_FROM" targets in the wrong place. Specifically for this program: 

```
          42  COMPARE_OP               '=='
          45  POP_JUMP_IF_FALSE    79  'to 79'

   4      48  LOAD_NAME                'x'
          51  STORE_NAME               'a'

   5      54  LOAD_NAME                'x'
          57  LOAD_CONST            2  2
          60  COMPARE_OP               '=='
          63  POP_JUMP_IF_FALSE    89  'to 89'

   6      66  LOAD_NAME                'print'
          69  LOAD_CONST               'b'
          72  CALL_FUNCTION         1  '1 positional, 0 keyword pair'
          75  POP_TOP          
        76_0  COME_FROM                '63'
          76  JUMP_BACK            16  'to 16'

   8      79  LOAD_NAME                'print'
          82  LOAD_CONST               'c'
```

The jump in the instruction at offset 45 is to offset 79, but this custom code omits the COME_FROM before offset 79. In the past I have fixed this, but that breaks a number of other things and I have not had the patience to go and sort out that large ball of spaghetti. If I recall correctly, this also happens in 3.4 and possibly others 3.x versions. 

It will all get sorted out eventually, but as long as I'm the only one fixing things, it may take a while.
