### ISSUE TITLE
Parse error at or near `POP_BLOCK' instruction

### ISSUE THREAD

**Issue by wangym5106** [rocky/python-uncompyle6#149]
Python bytecode version: 2.7, compiled with 2.7.10
uncompyle6 https://github.com/rocky/python-uncompyle6/commit/71e712050131d9aa340da92c8c856a1159e445bf on Python 3.6.4

Code example:
```
def test(a):
    while True:
        if a:
            pass
        else:
            continue
        return
```
Instruction context:
```
   7      21  LOAD_CONST            0  ''
             24  RETURN_END_IF
           25_0  COME_FROM            12  '12'
->           25  POP_BLOCK
```
Thanks

**Comment by rocky** [comment]
This bug appears in uncompyle2 which unusual, but doesn't appear in 2.6 or earlier. 

The "COME_FROM" instruction off offset 25_0 is wrong: the instruction jumps from another location.

**Comment by rocky** [comment]
The shorter term fix will probably be to realize that the LOAD_CONST is a jump target, so the "END_IF" really occurs at the instruction before offset 21. If that one thing is detected, everything else will go through.
