### ISSUE TITLE
Control flow mis-decompile on python 2.7

### ISSUE THREAD

**Issue by wangym5106** [rocky/python-uncompyle6#151]
Python bytecode version: 2.7, compiled with 2.7.10
uncompyle6 https://github.com/rocky/python-uncompyle6/commit/71e712050131d9aa340da92c8c856a1159e445bf on Python 3.6.4

original code:
```
def func(a, b, c):
    while a:
        if b:
            continue
        return False
    return True
```

uncompyle6 output:
```
def func(a, b, c):
    while 1:
        if a:
            if b:
                pass
            continue
        return False

    return True
```
The output has different behavior compared to original code.

**Comment by rocky** [comment]
Commit 5039a71 now addresses this. https://github.com/rocky/python-uncompyle6/wiki/Fixing-Issue-%23151 gives details on how to find and fix the bug.
