### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by FriedTM** [rocky/python-uncompyle6#154]
[Bot.zip](https://github.com/rocky/python-uncompyle6/files/1708973/Bot.zip)
above is the file I am trying to uncompyle below is the result
![capture](https://user-images.githubusercontent.com/36281865/36001162-663d24da-0cf3-11e8-8870-0ee9c166d60e.JPG)
Please help

**Comment by rocky** [comment]
This isn't valid bytecode.

**Comment by StranikS-Scan** [comment]
This is mod for the WorldOfTanks and its obfuscated and protected by the PjOrion ))))
