### ISSUE TITLE
Annotation args in 3.0 - 3.5

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#169]
We've punted on this for now.  3.6 on @x0ret has working.

**Comment by DamlaAltun** [comment]
+1

**Comment by rocky** [comment]
@DamlaAltun interested enough in trying your hand at this?

**Comment by DamlaAltun** [comment]
:/ Sorry, i am not familiar with bytecode, parsing... Maybe Batuhan (@BTaskaya) can help you, he wrote a blog post about this bytecode tech.

**Comment by rocky** [comment]
No one is born understanding bytecode parsing.

 I find it amusing that you are happy to volunteer someone else. Personally, though am not looking for help as I have no need of this feature right now.

**Comment by rocky** [comment]
@x0ret We capture the information and even show return annotation information. Parameter information still isn't done. If this is of no interest, just unassign yourself.

**Comment by rocky** [comment]
@x0ret Actually this may be fixed in 3.0-3.5, but there is a more general bug in parameter order. 

For Python 3.3 for 

```
def foo2(a, b: 'annotating b', c: int, *args: str) -> float:
``` 

we get: 

```
def foo2(*argsa, b: 'annotating b',
         c: int) -> float:
```

Python has switched around parameter ordering on the stack several times between versions.

**Comment by x0ret** [comment]
Sorry, I admit i didn't check other versions. According to my investigation `make_function3_annotate` is responsible for such a behavior. 

> Python has switched around parameter ordering on the stack several times between versions.
I didn't know that. Thanks.

I'll check other versions and fix the issue. (I'm a little busy right now, will try tomorrow).

**Comment by rocky** [comment]
> I'm a little busy right now, 

I totally understand. No problem. Thanks for all of the help.
