### ISSUE TITLE
Parse error at or near `COME_FROM' instruction

### ISSUE THREAD

**Issue by yyusea** [rocky/python-uncompyle6#173]
source:

```
ms=0
if ms==1:
    while 1:
        pass
else:
    print ms
```

  
   4      21  CONTINUE             21  'to 21'
->         24_0  COME_FROM            18  '18'
             24  JUMP_FORWARD          5  'to 32'

# --- This code section failed: ---

   1       0  LOAD_CONST            0  0
           3  STORE_NAME            0  'ms'

   2       6  LOAD_NAME             0  'ms'
           9  LOAD_CONST            1  1
          12  COMPARE_OP            2  '=='
          15  POP_JUMP_IF_FALSE    27  'to 27'

   3      18  SETUP_LOOP           11  'to 32'

   4      21  CONTINUE             21  'to 21'
        24_0  COME_FROM            18  '18'
          24  JUMP_FORWARD          5  'to 32'

   6      27  LOAD_NAME             0  'ms'
          30  PRINT_ITEM       
          31  PRINT_NEWLINE_CONT
        32_0  COME_FROM            18  '18'

Parse error at or near `COME_FROM' instruction at offset 24_0

**Comment by rocky** [comment]
Works for me with the current git sources on 2.7.14 and 2.6.9. So try with current sources if you are not already using that. 

I'm not into guessing games you want this considered for bug fixing, read what I wrote about how to report bug.

**Comment by yyusea** [comment]
Think you.rocky. In windows ,It 's ok for me also.

**Comment by rocky** [comment]
I decompiled on GNU/Linux without problem. So  the magic number and version might not the same on GNU/Linux.

**Comment by yyusea** [comment]
[a_win.zip](https://github.com/rocky/python-uncompyle6/files/1960857/a_win.zip)
[a_linux.zip](https://github.com/rocky/python-uncompyle6/files/1960858/a_linux.zip)

**Comment by yyusea** [comment]
yes ,   2.7.5

**Comment by yyusea** [comment]
Thank you very much.
