### ISSUE TITLE
high memory consumption

### ISSUE THREAD

**Issue by yelkarama** [rocky/python-uncompyle6#177]
I'm trying to decompile a 400k .pyc file. from the task manager, I see that the python process running uncompyle6 is chewing all my RAM (at 30GB right now and still increasing). 
![image](https://user-images.githubusercontent.com/5099215/40386651-5262b4c6-5dd8-11e8-84c6-acbc1293c213.png)
Is this expected? 
Thanks

**Comment by rocky** [comment]
See https://github.com/rocky/python-uncompyle6/issues/70

**Comment by yelkarama** [comment]
Seems to be pretty old bug. Is it fixed? 
What action should I take? 
Thanks

**Comment by rocky** [comment]
I guess the first step is to disassemble the bytecode to see what's up. Attach that.
