### ISSUE TITLE
NameError: name 'intern' is not defined (Py 3.6 decompiling Py 2.7 code)

### ISSUE THREAD

**Issue by iamgreaser** [rocky/python-uncompyle6#180]
```
  File "/usr/lib/python3.6/site-packages/uncompyle6/scanners/scanner2.py", line 1153, in patch_continue
    tokens[-1].kind = intern('CONTINUE')
NameError: name 'intern' is not defined
```

* uncompyle6 version: git commit `6fd8d2556b0ba0a17d4c3267a9a1b1f42c5dd5e8` - `HEAD` at the time of reporting, roughly 3.2.3
* Host Python version: 3.6.5
* Bytecode Python version: 2.7.10

The file which trips this is `uuid.pyc`.

I've had a look into this and I have a fix but my fix does smell a bit bad.

`scanners/scanner2.py` is missing something along the lines of this:

```
from uncompyle6 import PYTHON3

if PYTHON3:
    import sys
    intern = sys.intern
```

Adding that makes `uuid` decompile successfully.

**Comment by rocky** [comment]
Thanks for the report and fix. I think commit 1350f4c fixes this. Please double check and close if so.
