### ISSUE TITLE
 "C code is Python 1.0 - 1.2; can't handle yet"

### ISSUE THREAD

**Issue by ulysaicha** [rocky/python-uncompyle6#185]
Hey, recieving this error:

` "C code is Python 1.0 - 1.2; can't handle yet"`

Any help?

**Comment by rocky** [comment]
Don't hold your breath on this one unless you or someone else wants to do it. Then I'd advise perhaps.

Handling 1.0 to 1.2 probably isn't technically challenging, just hard to believe there is much need except for curiosity or completeness. 

We are talking about bytecode from 1994 or 24 years ago, so I amsurprised that there any interest in this. 

I need to put this project more or less in deep freeze, and much more pressing is better 3.7 support, or better analysis of control flow.

**Comment by ulysaicha** [comment]
Um I have no idea how I got bytecode from 1994 since im trying to decompile a recently made program... super weird

**Comment by rocky** [comment]
Ok. It looks like you haven't read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md . Please do so before reporting what you think are bugs.
