### ISSUE TITLE
Non-ASCII character '\xe0' in file

### ISSUE THREAD

**Issue by loretoparisi** [rocky/python-uncompyle6#186]
I'm getting a bad escape sequence in the `.py` output file. Shall I define some encoding that is missing in the output file? - https://www.python.org/dev/peps/pep-0263/

**Comment by rocky** [comment]
I've updated the issue template to focus attention on what's needed in bug reports.

Please also read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md

**Comment by loretoparisi** [comment]
@rocky ok thank you. In this case my opinion is that `uncompyle6` is not defining the encoding at the top of the generated file. Since I have `\u0874` chars in the file, this causes the error, so is there a way to specify explicitly the `# coding=` option? Thank you.

**Comment by rocky** [comment]
Ok, still look at the bug report form and follow that. Or perhaps this is a feature request, follow that instead.

Feel free to suggest an command-line option or suggest a default encoding to the generated python, or a default coding option that should be added by default. Better though would be a pull request.
