### ISSUE TITLE
Slow decompilation or crash when decompiling large list, set, or dictionary literal

### ISSUE THREAD

**Issue by wangym5106** [rocky/python-uncompyle6#188]
## Description

Decompiling is **very** slow when origin python code contains a large list/tuple/set literal.

## How to Reproduce

Origin python code:
```
a_list = [0, 1, 2, {...}, 9999]   # A list literal contains 10000 items
```

Compile it to bytecode then decompile it with uncompyle6.

## Expected behavior

Decompile finish in acceptable time.

## Environment

- Uncompyle6 version: 3.2.2
- Python version: Python 2.7.10
- OS and Version: macOS 10.13.6

## Additional Environment or Context

This problem seems caused by https://github.com/rocky/python-uncompyle6/commit/626f690a5abb1c5c3c679dc73dee529e8250bd23#diff-93b193a7eb1cd7fb48d289c05e22f7f7

**Comment by rocky** [comment]
Yes, this is a problem. Unfortunately I won't have time to address in the near future. 

However if you or someone else would like to address by reinstating the grammar rules for `expr32` and `expr1024` and make the corresponding change in `n_build_list` inside `python-uncompyle6/uncompyle6/semantics/pysource.py` along the lines of 
https://github.com/wibiti/uncompyle2/blob/master/uncompyle2/Walker.py#L1070-L1078
I'd be happy to accept a a pull request for ths.

**Comment by rocky** [comment]
If the literal is large enough the program crashes. See also #238

**Comment by rocky** [comment]
Late breaking news.... 

The other day I realized how this can be addressed, sort of (see below) and have started working on it in decompyle3. Eventually it will make its way here I imagine. 

We can now handle a little under 5K items without a slowdown which is short of the 10K given. At 5K the spark parser dies due to recursion.

**Comment by rocky** [comment]
Fixed now up to 5K items. For problems above 5K, feel free to open another issue with details.
