### ISSUE TITLE
Extended args broken for Python 2.7

### ISSUE THREAD

**Issue by Zireael07** [rocky/python-uncompyle6#191]
## Description

when trying to decompile a pyc file, I get an error on line https://github.com/rocky/python-uncompyle6/blob/ec42ee540cb8c9e67340091d142a78057db3feae/uncompyle6/scanners/scanner2.py#L275

the error is Scanner2.7 has no attribute extended_arg_val()

(I tried several different files, both under Windows and Linux. It seems any file big enough to be EXTENDED_ARG causes this)

## How to Reproduce

On windows, console gets frozen so I can't copy the output, and I'm a newbie to Linux, so how do I copy terminal output?

## Expected behavior
It should work.

## Environment
uncompyle6 2.3.2
Python 2.7.15
Ubuntu 18.04

-->

**Comment by rocky** [comment]
In commit 616e5c82f from last September, that routine was added in line 113 of scanner2.py

You say you are using 2.3.2, which seems very old. The current version is 3.2.3. 

I'm closing this as invalid. In the future, please provide the bytecode. I've updated the template instructions.

**Comment by Zireael07** [comment]
I installed uncompyle from pip, it should therefore be 3.2.3 (I typed version number manually and got the numbers wrong)

**Comment by rocky** [comment]
Ok. Try installing from git then. As described above, that has been fixed since the last release since last June.

**Comment by Zireael07** [comment]
Ok, will try installing from git. Will there be a pip release?
