### ISSUE TITLE
Is it possible to decompile the mpy file? micropython pre-compiled file.

### ISSUE THREAD

**Issue by kylinpoet** [rocky/python-uncompyle6#193]
The mpy-cross tool is here...
https://github.com/micropython/micropython/tree/master/mpy-cross

**Comment by rocky** [comment]
Micropython is not python and it doesn't produce Python bytecode. So this project is of no use here.

As to the answer to your question of "Is it possible"... a lot is possible if you are willing to put effort into it. Are you? There has been a lot written about decompilers in general.  http://rocky.github.io/Deparsing-Paper.pdf has my take on how to write a decompiler.

**Comment by eggfly** [comment]
But Micropython USE its bytecodes indeed, and its bytecode is very like Python's bytecode.
