### ISSUE TITLE
3 Bugs found!

### ISSUE THREAD

**Issue by byehack** [rocky/python-uncompyle6#207]
### Bug 1:
it doesn't support `def x(arg,*,kwarg='test',**kw)`
### Bug 2:
it doesn't put `return` out of `if`
### Bug 3:
change the encoding default to utf-8 .now it is charmap

my real test code:
```
import http
def bug1(arg,*,kwarg='test',**kw):
    print('hello world!')
    
def bug2():
    if hasattr(http, 'say_hello'):
        return "hello"
    return "world"

def bug3():
    x="""
    persian: \xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xd9\x8a
    --charmap encoding does'nt support it
    test with UTF-8
    """
```

after unpack(without `Bug3` because with that, it will raise error):
```
import http

def bug1(arg, *, kwarg='test'**kw):
    print('hello world!')


def bug2():
    if hasattr(http, 'say_hello'):
        return 'hello'
        return 'world'
```

for charmap codec raise this:
```
>/uncompyle6 -o xxx.py xxx.pyc


# file xxx.pyc
# 'charmap' codec can't encode character '\xd9' in position 221: character maps to <undefined>

# decompile failed
```

**Comment by rocky** [comment]
Please break these up into one bug per issue. And by they way, maybe you should also read and follow the instructions for how to report a bug.
