### ISSUE TITLE
it doesn't support def x(arg, *, kwarg='test', **kw):pass

### ISSUE THREAD

**Issue by byehack** [rocky/python-uncompyle6#208]
py3.7    uncompyle6 v3.2.5    win10

my code:
```
def bug1(arg,*,kwarg='test',**kw):
    print('hello world!')
```

after unpack, it removed `,` before `**kw`:
```
def bug1(arg, *, kwarg='test'**kw):
    print('hello world!')
```

**Comment by rocky** [comment]
Hmm. Maybe you'd like to try your hand at fixing? It basically comes down to [this test](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/make_function.py#L743)

Note that this is broken on both 3.6 and 3.7. 3.5 seems okay.

**Comment by byehack** [comment]
> Hmm. Maybe you'd like to try your hand at fixing? It basically comes down to [this test].(https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/make_function.py#L743)
> 
> Note that this is broken on both 3.6 and 3.7. 3.5 seems okay.

can't You use [this](https://stackoverflow.com/a/39517721) for extract function args?
i think it is better :-)

**Comment by rocky** [comment]
> can't You use this for extract function args?

No, that doesn't work here. You can use that function only when the Python interpreter running uncompyle6 uses the same magic number or bytecode release as the code getting decompiled. 

In other situations we don't in fact have a true python types.Code object but some structure represents the code object given that the  some of the fields are different as a result of changes in the Python interpreter. 

That said, you can look at how signature is implemented in Python 3.6 and Python 3.7 to see how it wokrs and mirror that in the code there. I suspect the implementation of signature is different between Python 3.6 and Python 3.7.

**Comment by byehack** [comment]
> Hmm. Maybe you'd like to try your hand at fixing? It basically comes down to [this test].(https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/make_function.py#L743)
> 
> Note that this is broken on both 3.6 and 3.7. 3.5 seems okay.

i think we dont need ends_in_comma:
```
if code_has_star_star_arg(code):
        if argc > 0:
            self.write(', ')
        self.write('**%s' % code.co_varnames[argc + kw_pairs])
```

beacuse **kw always come in end :)

**Comment by rocky** [comment]
> i think we dont need ends_in_comma

Wrong. 

```
def foo(**kw):
    pass
```

is valid python.

**Comment by rocky** [comment]
Let me correct that. I don't know if variable `ends_in_comma` is set _properly_. https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/make_function.py#L738  looks incorrect.

But whether it can be altogether _omitted_ though is a different thing. There is code where there are dangling commas.

Why don't you make changes and see of all of the tests still work?

**Comment by byehack** [comment]
> Let me correct that. I don't know if variable `ends_in_comma` is set _properly_. https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/make_function.py#L738 looks incorrect.
> 
> But whether it can be altogether _omitted_ though is a different thing. There is code where there are dangling commas.
> 
> Why don't you make changes and see of all of the tests still work?

hey i found a way to extract args

```
import gc,inspect
code= OUR-CODE-OBJECT #you get it in some lines
funcargs=str(signature(gc.get_referrers(code)[0]))
```

it works 100%🐸🐸
