### ISSUE TITLE
'charmap' codec can't encode

### ISSUE THREAD

**Issue by byehack** [rocky/python-uncompyle6#210]
change the encoding to utf-8. charmap is default.
open("xxx.pyc","rb",encoding="utf-8").read()

my code:
```
x="""
    persian: \xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xd9\x8a
    --charmap encoding does'nt support it
    test with UTF-8
    """
```

when i try to unpack:

```
/> uncompyle6 -o xxx.py xxx.pyc

# file xxx.pyc
# 'charmap' codec can't encode character '\xd9' in position 221: character maps to <undefined>

# decompile failed
```

**Comment by rocky** [comment]
This works for me:

```
$ pydisasm /tmp/bug9-3.7.pyc
# pydisasm version 3.8.8
# Python bytecode 3.7 (3394)
# Disassembled from Python 3.6.6 (default, Jul  2 2018, 00:06:07) 
# [GCC 5.4.0 20160609]
# Source code size mod 2**32: 130 bytes
# Method Name:       <module>
# Filename:          exec
# Argument count:    0
# Kw-only arguments: 0
# Number of locals:  0
# Stack size:        1
# Flags:             0x00000040 (NOFREE)
# First Line:        5
# Constants:
#    0: "\n    persian: Ù\x81Ø§Ø±Ø³Ù\x8a\n    --charmap encoding does'nt support it\n    test with UTF-8\n    "
#    1: None
# Names:
#    0: x
  5:           0 LOAD_CONST                0 ("\n    persian: Ù\x81Ø§Ø±Ø³Ù\x8a\n    --charmap encoding does'nt support it\n    test with UTF-8\n    ")
               2 STORE_NAME                0 (x)
               4 LOAD_CONST                1 (None)
               6 RETURN_VALUE
```

```
$ ../bin/uncompyle6 /tmp/bug9-3.7.pyc
# uncompyle6 version 3.2.5
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.2 (default, Dec 26 2018, 18:52:51) 
# [GCC 7.3.0]
# Embedded file name: exec
# Size of source mod 2**32: 130 bytes
x = "\n    persian: Ù\x81Ø§Ø±Ø³Ù\x8a\n    --charmap encoding does'nt support it\n    test with UTF-8\n    "
# okay decompiling /tmp/bug9-3.7.pyc
```

**Comment by byehack** [comment]
how?

try with -o :
uncompyle6 -o xxx.py xxx.pyc

**Comment by byehack** [comment]
yes without` -o `worked for me.
i think you shoud use utf-8 for outfile writing:
open("out","w",encoding="utf-8").write("")

**Comment by rocky** [comment]
Ok - add a pull request for this. If it passes the various tests, we can add.

**Comment by byehack** [comment]
> Ok - add a pull request for this. If it passes the various tests, we can add.
> 
> Also, if you had followed instructions better, the back-and-forth over what it was you did, would not have been needed.
> 
> The less you follow instructions, the less likely I am to look at your problem. The bug reporting instructions are there to make it easier for me to fix problems when I have the time.
> 
> So I am perfectly happy to wait for someone else who does a better job at following instructions to report problems you encountered. As described in the guide on how to report a bug, there is no shortage of bugs, just people to fix them.
> 
> As a result, bug fixing needs to get prioritized, and this is one way to do it.

  replace :
https://github.com/rocky/python-uncompyle6/blob/763c599c16636b838b09b177d00bc725553619bf/uncompyle6/main.py#L46 
with :
`return open(outfile, mode, encoding="utf-8")`

it was worked for me.🐖🐐

Then close this issue. if you read this msg.
