### ISSUE TITLE
py37 bugs

### ISSUE THREAD

**Issue by byehack** [rocky/python-uncompyle6#212]
uncompyle6 3.2.5 --  py37

```
def x(a):
    if 0<=a<=2:print()
```
it cant be decompile and raise error.

```
def x(a):
    if a:return 0
    return 1
```
after dec:
```
def x(a):
    if a:
        return 0
        return 1
```

`return 1` must be out of `if`

can you fix them????
i need to fix them.they are very important for me.
please answer

**Comment by rocky** [comment]
Will look at when I get a chance. 

> i need to fix them.they are very important for me.

Why the urgency?>

**Comment by byehack** [comment]
> Will look at when I get a chance.
> 
> > i need to fix them.they are very important for me.
> 
> Why the urgency?

i should unpack some .pyc of py37 for someworks
i dont think fix them give long time. because u know your codes.

**Comment by rocky** [comment]
>  dont think fix them give long time. because u know your codes.

Knowing how to fix is not the only consideration. There is how much time I have for this, and what the requester is doing for why should address this problem over other things I could be doing. 

Quite franky you've been vague.

**Comment by rocky** [comment]
Got fixed at some point.
