### ISSUE TITLE
failed to recognize and conditional statements !

### ISSUE THREAD

**Issue by maqinzhang** [rocky/python-uncompyle6#213]
uncompyle6 3.6.5

source:
<pre>
#! E:\Python36\python
# -*- coding:utf-8 -*-
a = 1
b = ['a', 'b', 'c']
if len(b) > 2 and a:
	print('hhhhh')
else:
	print('gogogogo')
if b or not a:
	print('hhhhhhh')
else:
	print('gogogo')
</pre>
this is the source code, i use python commond  'python -m compileall testfile.py' to complie the file.

then i use uncompyle6 to uncomple the pyc file, this is the uncompyle code:
<pre>
# uncompyle6 version 3.2.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]
# Embedded file name: D:\11\testpyc.py
# Compiled at: 2019-01-24 18:05:18
# Size of source mod 2**32: 201 bytes
a = 1
b = ['a', 'b', 'c']
if len(b) > 2:
    if a:
        print('hhhhh')
    print('gogogogo')
if b or not a:
    print('hhhhhhh')
else:
    print('gogogo')
</pre>

failed to recognize and conditional statements !

**Comment by maqinzhang** [comment]
Will this be fixed in the new version? When will the new version be released?  @rocky ，thank you！

**Comment by rocky** [comment]
I probably won't look at for a while.  However you and others are free to try your hand at this. 

Look for other bugs for control flow perhaps optionally Python 3.6 and see how that was handled, and that might suggest how this too could be handled.

**Comment by nishantm9** [comment]
Is there any work around for this issue...probably an older version that did not have this bug?

**Comment by rocky** [comment]
Well, you could try your hand at fixing yourself. 

Or you could try all of the old versions to see if one works.

**Comment by rocky** [comment]
Another thought is offering a bounty for having someone else fix it.

**Comment by rocky** [comment]
Was fixed in the release 3.2.6.
