### ISSUE TITLE
Deparsing stopped due to parse error + Deparsing hit an internal grammar-rule bug

### ISSUE THREAD

**Issue by skochinsky** [rocky/python-uncompyle6#215]
## Description

Having above errors decompiling a specific file.  "parse error" happens with 2.7 bytecode, "internal grammar-rule bug" with the 2.5 one.

## How to Reproduce

Files were extracted from GenFds.exe from the UEFI Development Kit, versions UDK2010.SR1.UP1.P1 and UDK2014. 

I used:

    uncompyle6 -t FdfParser.pyc  >FdfParser.pyt

Output is 
```
# file FdfParser.pyc
# Deparsing stopped due to parse error
```
and 

```
# file FdfParser.pyc
# Deparsing hit an internal grammar-rule bug
```

I attached both extracted files and the output here: [FdfParser_bug.zip](https://github.com/rocky/python-uncompyle6/files/2799295/FdfParser_bug.zip). Source from the recent edk2 tree is added too but it probably does not match the .pyc files which are older. You can find the past versions in the  [edk2 tree](https://github.com/tianocore/edk2/tree/master/BaseTools/Source/Python/GenFds) by switching the git branch.

## Expected behavior

No errors and output close to the original 

## Environment

uncompyle6 3.2.5 (just pulled today and did `pip install -e .`)
Python 2.7.10 from python.org (x86)
OS: windows 10 1809

**Comment by rocky** [comment]
See if e1628d4 fixes this. If so, close this issue.

**Comment by skochinsky** [comment]
Thank you! The UDK2010 (2.5 bytecode) now decompiles cleanly, however the 2014 one (2.7 bytecode) still produces this output:

```
Instruction context:
   
 801    2329  LOAD_FAST             0  'self'
           2332  LOAD_ATTR            10  'CurrentLineNumber'
           2335  LOAD_CONST            7  1
           2338  BINARY_ADD       
           2339  STORE_FAST            2  'RegionLayoutLine'
           2342  JUMP_BACK            21  'to 21'
->         2345  JUMP_BACK            21  'to 21'
           2348  POP_BLOCK        
         2349_0  COME_FROM            18  '18'


# decompile failed
# file FdfParser.pyc
# Deparsing stopped due to parse error
```

**Comment by rocky** [comment]
In the future please isolate to one issue per bug not one issue for everything you happen to be working on. 

Also, please reduce the size of the source code to just the function that is failing and further try removing statements extraneous source-code lines to get a small function that exhibits the behavior. 

This is all spelled out in the instructions for how to report a bug.

**Comment by sooooooph** [comment]
> [e1628d4 が](https://github.com/rocky/python-uncompyle6/commit/e1628d4d3a87002d1246b4d7ba7d523e9266dd44)これを修正するかどうかを確認してください。その場合は、この問題を閉じてください。

I don't know how to use parse36.py.
I would like to know the command

**Comment by sooooooph** [comment]
> See if [e1628d4](https://github.com/rocky/python-uncompyle6/commit/e1628d4d3a87002d1246b4d7ba7d523e9266dd44) fixes this. If so, close this issue.

I don't know how to use parse36.py.
I would like to know the command
