### ISSUE TITLE
Wrong grammar for nested ifelsestmt (in Python 3.7 at least)

### ISSUE THREAD

**Issue by jpivarski** [rocky/python-uncompyle6#221]
## Description

`ifelsestmt` includes instructions beyond the if-else when nested within another if-else.

## How to Reproduce, Expected Results, and Environment

In Python 3.7 (might affect earlier versions of Python, does not affect Python 2.7), the following code is incorrectly converted into source code:

```python
import uncompyle6

def testme(x):
    if x < 0:
        y = -1
    else:
        if x > 0:
            y = 0
        else:
            y = 1
    return y

uncompyle6.code_deparse(testme.__code__)
```

The output is

```python
if x < 0:
    y = -1
else:
    if x > 0:
        y = 0
    else:
        y = 1
    return y
```

Note that the `return` in the original code is _outside_ the if-else, and in the generated code, it is _inside_ the if-else. This also happens for `elif` chains (which are compiled to nested if-elses), and you don't see it for only one level of if-else: it has to be nested. (Though I do see it for two levels as well.)

The bug is not in the source generation; it's in the earlier step of parsing of the bytecode. Here is a printout of the `ifelsestmt` node passed from parser to code generator:

```
ifelsestmt (5)
     0. testexpr
        testfalse (2)
             0. expr
                compare
                    compare_single (3)
                         0. expr
                            L.   2       0  LOAD_FAST                'x'
                         1. expr
                            L.   2       2  LOAD_CONST            0  0
                         2. L.   2       4  COMPARE_OP               '<'
             1. jmp_false
                L.   2       6  POP_JUMP_IF_FALSE    14  'to 14'
     1. c_stmts
        stmt
            assign (2)
                 0. expr
                    L.   3       8  LOAD_CONST           -1  -1
                 1. store
                    L.   3      10  STORE_FAST               'y'
     2. jump_forward_else (2)
         0. L.   2      12  JUMP_FORWARD         32  'to 32'
         1. L.   2      14  ELSE                     '32'
     3. else_suite
        suite_stmts (2)
             0. stmt
                ifelsestmt (5)
                     0. testexpr
                        testfalse (2)
                             0. expr
                                compare
                                    compare_single (3)
                                         0. expr
                                            L.   5      14  LOAD_FAST                'x'
                                         1. expr
                                            L.   5      16  LOAD_CONST            0  0
                                         2. L.   5      18  COMPARE_OP               '>'
                             1. jmp_false
                                L.   5      20  POP_JUMP_IF_FALSE    28  'to 28'
                     1. c_stmts
                        stmt
                            assign (2)
                                 0. expr
                                    L.   6      22  LOAD_CONST            0  0
                                 1. store
                                    L.   6      24  STORE_FAST               'y'
                     2. jump_forward_else (2)
                         0. L.   5      26  JUMP_FORWARD         32  'to 32'
                         1. L.   5      28  ELSE                     '32'
                     3. else_suite
                        suite_stmts
                            stmt
                                assign (2)
                                     0. expr
                                        L.   8      28  LOAD_CONST            1  1
                                     1. store
                                        L.   8      30  STORE_FAST               'y'
                     4. _come_froms (2)
                         0. L.   5    32_0  COME_FROM            26  '26'
                         1. L.   5    32_1  COME_FROM            12  '12'
             1. stmt
                return (2)
                     0. ret_expr
                        expr
                            L.   9      32  LOAD_FAST                'y'
                     1. L.   9      34  RETURN_VALUE
     4. _come_froms
```

You can see that the `return (2)` stmt is in there. The BNF (I don't know where it is defined) should stop absorbing instructions after all `COME_FROM` instructions referred to by `JUMP_FORWARDs` (which both go to offset 32 in this example).

Thanks! (Otherwise, _great_ tool! Having converted and tested a wide swath of the Python language, including all of the expressions, to ASTs, this was the only parsing-tree error.)

**Comment by rocky** [comment]
Handling control flow properly is the biggest weakness in uncompyle6. And 3.8 it will get progressively worse. That is why I started https://github.com/rocky/python-control-flow 

Working on that and integrating that here would put this project on solid footing. 

Until then there are a number of hacks that have been made to limp things along. If you'd like to try your hand at fixing just look for [closed issues that have the "control flow" label](https://github.com/rocky/python-uncompyle6/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+is%3A+control+flow) and see how those were fixed.

**Comment by jpivarski** [comment]
Thanks for pointing me to the other control flow examples—this is indeed a duplicate of #200. I forgot to say that I'm using the latest version from pip, which looks like 3.2.5. I'll test it again with master from git.

Assuming that fixes it, when should we expect a new release? Is there a regular schedule?

(Fortunately, my project doesn't require many control structures, but if-elif-else assigning the same variables in each branch or returning in each branch is equivalent to and easier to write than an if-else expression.)

**Comment by jpivarski** [comment]
I've verified that the bug was fixed in git-master. When will that be deployed to PyPI?

Thanks!

**Comment by rocky** [comment]
> this was the only parsing-tree error.

Finding bugs is actually pretty easy. Start with the test suite for a version like 3.7. The tests and suite is written in Python. Run it and see that everything succeeds as it should. Now compile all of the Python code and run it again. Aside from some self-referential code that may fail, for example those tests that assume text at a particular line, or assume the text of some Python source code having a particular value, the remaining tests should succeed. My experiments of this ilk shows a number of failures.

> when should we expect a new release? Is there a regular schedule?

This is a hobby project that I work on it when I feel like it. If others would like to see it become something else more involvement by others is necessary,. 

If I have time, I may put out another release after finding another random bug and fixing,.

**Comment by rocky** [comment]
Released now. (There is a way you and watch for releases by hitting the "watch" button in this repository and there may be other ways as well. I'll assume in the future that you'll be watching for releases, especially those that you request.)

**Comment by jpivarski** [comment]
Thanks! I was going to say that while I can fix bugs with pull requests, I can't release or deploy new versions. It helps to know that this is a hobby project, but it does look like a very professional one that we can rely on. (I hope so!) That's a good idea about watching the repository, I'll do that.

**Comment by rocky** [comment]
If people get involved, deployment ot Pypi can be done via tagging.  The problem has been getting people involved, not the release process.
