### ISSUE TITLE
Multilevel if statements combined with conditional assignment fails

### ISSUE THREAD

**Issue by dontech** [rocky/python-uncompyle6#226]
Hello Rocky/Uncompyle

## Description

The following code does not uncompile correctly:

```
path = raw_input("")
y = raw_input("")

x = "hello" if y else None
if path and "world":
    if(path == "world"):
        print "oh!"

```

It turns into:

```
path = raw_input('')
y = raw_input('')
if y:
    x = 'hello' if 1 else None
    if path and 'peter' and path == 'peter':
        print 'oh!'

```

Notice that "x" is now not assigned to anything and thus empty if "y" is false. It should have been "None".

## How to Reproduce

Compile/Uncompile

## Environment

# Decompiled from: Python 2.7.16 (default, Mar 20 2019, 12:15:19)

**Comment by rocky** [comment]
Not sure when this got fixed, but it is fixed now. 

I think some point I added additional reduction checks in decompyle3 and those checked filtered down into the 2.7 deparsing.
