### ISSUE TITLE
Inconsistent if block in python3.6

### ISSUE THREAD

**Issue by x0ret** [rocky/python-uncompyle6#229]
## Description

Please consider following src:

```python
def func():
    if x.t:
        return False
    try:
        c = x.c
    except Exception as e:
        return False
    if x.t > 5:
        return x.g
```
which is decompiled as :

```python
def func():
    if x.t:
        return False
        try:
            c = x.c
        except Exception as e:
            return False

        if x.t > 5:
            return x.g
```

After using `pdb` a little bit, i came to following condition [L#919](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/scanners/scanner3.py#L919):

```
                    # based on seeing SETUP_EXCEPT various places.
                    if self.version < 3.8 and code[rtarget] == self.opc.SETUP_EXCEPT:
                        return
                    # Check that next instruction after pops and jump is
```
a temporary solution is to fix `3.8` to `3.6` but please consider the disassembly:

```
           4  POP_JUMP_IF_FALSE    10  'to 10'

   3       6  LOAD_CONST            0  False
           8  RETURN_VALUE

   4      10  SETUP_EXCEPT         22  'to 22'

   5      12  LOAD_GLOBAL              'x'
          14  LOAD_ATTR                'c'
```

Since `SETUP_EXCEPT` is just after `RETURN_VALUE` and our python version is below `3.8` this function returns and we have no end if block in `self.return_end_ifs`, So all later statements are in first `if` block.

I also checked `v3.7` and the result is the same.

@rocky , Could you please guide me around this ?

```diff
diff --git a/uncompyle6/scanners/scanner3.py b/uncompyle6/scanners/scanner3.py
index 9e24bdd8..eec5f43c 100644
--- a/uncompyle6/scanners/scanner3.py
+++ b/uncompyle6/scanners/scanner3.py
@@ -916,7 +916,7 @@ class Scanner3(Scanner):
                     # Python 3.5 may remove as dead code a JUMP
                     # instruction after a RETURN_VALUE. So we check
                     # based on seeing SETUP_EXCEPT various places.
-                    if self.version < 3.8 and code[rtarget] == self.opc.SETUP_EXCEPT:
+                    if self.version < 3.6 and code[rtarget] == self.opc.SETUP_EXCEPT:
                         return
                     # Check that next instruction after pops and jump is
                     # not from SETUP_EXCEPT
``` 

## How to Reproduce

Please consider following commands:

```bash
$ cat test4.py
def func():
    if x.t:
        return False
    try:
        c = x.c
    except Exception as e:
        return False
    if x.t > 5:
        return x.g
$ python -m compileall . ; uncompyle6 __pycache__/test4.cpython-36.pyc
...
```

## Expected behavior

Expected behavior in this case is having proper if block if applicable.

## Environment

- Uncompyle6 version: master HEAD `b57ca392`
- Python version: `3.6.7`
- OS and Version: Ubuntu bionic

**Comment by rocky** [comment]
For now I've taken your suggestion. The best way however to handle this is proper control flow analysis and for that I started https://github.com/rocky/python-control-flow

This reliably finds where the if block ends so there is none of the Python version crap here. 

However this code needs work. I'd like to see it used in a specific version of Python, say 3.8 and then extended to other versions.
