### ISSUE TITLE
KeyError: '3.7.3candidate1'

### ISSUE THREAD

**Issue by muellert** [rocky/python-uncompyle6#231]
## Description

Same as #176, just for a different version of Python

**Comment by rocky** [comment]
As it says in [README.rst](https://github.com/rocky/python-uncompyle6/blob/master/README.rst):

> Currently not all Python magic numbers are supported. Specifically in some versions of Python, notably Python 3.6, the magic number has changes several times within a version. We support only the released magic. 

I have just changed that text slightly to make that clear. 

However we do keep a list of all Python magic numbers in [xdis](https://github.com/rocky/python-xdis) so if you want to report the magic number in the project, we will eventually update that.

**Comment by rocky** [comment]
Also in #176 I wrote:

> I don't guarantee supporting all intermediate versions of Python, but others are willing to keep track of this and make pull requests, I am not opposed to it when the underlying bytecode magic doesn't change.
