### ISSUE TITLE
About unicode docstring

### ISSUE THREAD

**Issue by x0ret** [rocky/python-uncompyle6#241]
## Description

There are 2 points i think:
1. In the py <= 2.7 we can recognize unicode with `isinstance`, I should add using `uncompyle6` in Python `2.7.16` env does add `u` but does not unescape unicode.

```python
def test():
    u"""
    \xd8\xaa\xd8\xb3\xd8\xaa
    """
    pass
```

```bash
>>> a = "\xd8\xaa\xd8\xb3\xd8\xaa"
>>> print(a.decode("utf-8"))
تست
```

and this can be easily achieved. but Please note with `Python3` all has `str` type and it needs a little more work to check. And this is why we don't have `u` there.

Besides do we really need `u` in `Python3` when it treats all in `str`? I checked multiple cases and it worked. 

2. Whenever we face unicode chars we should add coding type in the file's header according to `pep-0263`. I'm not sure if current implementation allows this.

Thanks.

**Comment by rocky** [comment]
Everything you say is great! Any fixes for any of the many issues would be appreciated. 

I'll link to this in decompile3.

**Comment by rocky** [comment]
> Whenever we face unicode chars we should add coding type in the file's header according to pep-0263. I'm not sure if current implementation allows this.

We don't.
