### ISSUE TITLE
Extra parenthesis around in generators when they are the sole argument in a function call

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#247]
In Python 3.7ish

```
if all(str(exc) == model for exc in exceptions):
    raise exceptions[0]
```

has extra parenthesis:

```
if all((str(exc) == model for exc in exceptions)):
    raise exceptions[0]
```

**Comment by x0ret** [comment]
As far as i can tell, The cause of this behavior is caused by these two routes:

1. [pysource.py:1020-1028](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/pysource.py#L1020-L1028) which will output inner parenthesis.
2. Second, [pysource.py:1986](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/pysource.py#L1986) which is responsible for handling call parenthesis.

Due to need information about inner `genexpr_exp`. I think we should fix this in handling call (access to parent node is possible?). otherwise we break tests like:
```
names = (formatmonthname(False) for k in __file__)
```

I'll investigate more.

**Comment by x0ret** [comment]
Maybe something like this? 

```diff
diff --git a/uncompyle6/semantics/customize35.py b/uncompyle6/semantics/customize35.py
index 05639d5c..40df0477 100644
--- a/uncompyle6/semantics/customize35.py
+++ b/uncompyle6/semantics/customize35.py
@@ -113,6 +113,16 @@ def customize_for_version35(self, version):
                 self.template_engine(template, node)
             self.prune()

+        elif key.kind == "CALL_FUNCTION_1":
+            args_node = node[-2]
+            if args_node == 'pos_arg':
+                assert args_node[0] == 'expr'
+                n = args_node[0][0]
+                if n == 'generator_exp':
+                    template = ('%c%P', 0, (1, -1, ', ', 100))
+                    self.template_engine(template, node)
+                    self.prune()
+
         self.default(node)
     self.n_call = n_call
```

What do you think?

**Comment by rocky** [comment]
The analysis is right on. Thanks for investigating. The fix is great too. 

I checked to see whether there could be functions other than `FUNCTION_1`, but I get the message `Generator functions must be parenthesized of not the sole argument`. 

So let's patch and ship it! I'd be grateful if you would handle and note that peculiarity which I am likely to forget (and others may be unaware of). 

In the end this seems like a small detail, which is why it is a _feature_ rather than a bug. But I think it cool to handle.

**Comment by x0ret** [comment]
@rocky, A question, I'm implementing this for python2 and we override `n_call` in `customize36.py` which means in my understanding its superclass's `n_call` is not called. did you implement a way for workaround this which i am not aware of? 

I implemented `n_call` in `pysource.py` and also in `customize35.py` as above. Is this correct and your preferred implementation?

**Comment by rocky** [comment]
For Python less than version 3.0 add routines to  [semantics/customize26_27.py](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/customize26_27.py) or 
[semantics/customize25.py](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/customize25.py).

If it turns out there is common code for this, for example maybe you want to do the same thing on the outside and pass a function to call on the inside, then you could add that to [semantics/helper.py](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/helper.py).
