### ISSUE TITLE
3.3-6 function signature with *

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#258]
```
class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(*, a:float, b:str, c:str = 'test', **kwargs: int) -> int:
            pass
```
on 3.3-3.4 gives: 

```
class TestSignatureObject:

    def test_signature_on_wkwonly(self):

        def test(*, **b: str) -> int:
            pass
# okay decompiling /tmp/bug-3.3.pyc
```

On 3.6 gives: 

```
class TestSignatureObject:

    def test_signature_on_wkwonly(self):

        def test(*, c='test'**a):
            pass
```

Follow up to #257

**Comment by rocky** [comment]
@x0ret Sorry that was an old branch. However what you report above is still different in that `c` is coming after `a`, and `b`.

**Comment by x0ret** [comment]
Yes, Sorry about that, you are right, I didn't pay attention to ordering, besides `make_function3_annotate` seems to have this issue either.

About issue: 

after this line:
```python
if kw_args + annotate_argc > 0:
```
We are handling `kwargs` first and later `annotate_args`. 

I can handle both for both versions if you don't mind. Sorry for buggy PR.

**Comment by rocky** [comment]
@x0ret Yes please handle as much as you are willing to do. I am kind of fed up with Python and all of its futzing with the order of parameters in signatures. (And I'm not very good at this stuff either). Thanks for all of the help.

**Comment by rocky** [comment]
P.S. After things stabalize I think we should put out a release.

There has been a _lot_ of work done and lots of bug fixes.
