### ISSUE TITLE
Deparsing errors on JUMP_FORWARD

### ISSUE THREAD

**Issue by imPRAGMA** [rocky/python-uncompyle6#267]
## Description

it gets to "2290  JUMP_FORWARD       2688  'to 2688'" in the instruction context and then fails right before an ELSE. "Parse error at or near `JUMP_FORWARD' instruction at offset 2290"

## How to Reproduce

```console
$ uncompyle6 -o . primevideo36.pyc
...
$Instruction context:

2764    2256  LOAD_GLOBAL              sys
           2258  LOAD_ATTR                exit
           2260  LOAD_CONST               0
           2262  CALL_FUNCTION_1       1  ''
           2264  POP_TOP
           2266  POP_BLOCK
           2268  POP_EXCEPT
           2270  LOAD_CONST               None
         2272_0  COME_FROM_FINALLY  2216  '2216'
           2272  LOAD_CONST               None
           2274  STORE_FAST               'e'
           2276  DELETE_FAST              'e'
           2278  END_FINALLY
           2280  JUMP_FORWARD       2284  'to 2284'
           2282  END_FINALLY
         2284_0  COME_FROM          2280  '2280'
         2284_1  COME_FROM          2198  '2198'
           2284  JUMP_BACK          2016  'to 2016'
           2288  POP_BLOCK
->         2290  JUMP_FORWARD       2688  'to 2688'
           2294  ELSE                     '2688'


# file x.pyc
# Deparsing stopped due to parse error
x.pyc --
# decompile failed
```

## Expected behavior
Finish

## Environment
Attempted on both 3.7 and 3.6
- Uncompyle6 version: 3.3.4
- Python version: 3.7.3 and 3.6.0
- OS and Version: Windows 10 1809

**Comment by imPRAGMA** [comment]
The .pyc was compiled on PyInstaller using Python 3.6.0

**Comment by rocky** [comment]
Do you have the source code for this? If so please attach it or point to where it can be found.
The same question goes for the python bytecode. We can't do anything with a fragment of bytecode, we need to use the full bytecode. 

If you do have the source code, then can you figure out how to narrow the code to a smaller example? 
The fragment listed above looks like it has thousands of lines of source code and thousands of bytes of bytecode. That is hard to work with.

If you don't have the source code have you read Have you read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md ?

**Comment by imPRAGMA** [comment]
Sadly I do not have the original source code, and I could possibly try to manually convert the bytecodes to py, but im really not known to it yet, I can provide the .pyc file if required: http://pragma.nyx.feralhosting.com/public_html/x.pyc

If you need me to do anything else that I have missed please let me know, and I understand your point of this too, that it would also be time consuming on your end, but you would overall be better and faster at it then I would be, considering you have a bit more knowledge of it then me.

**Comment by imPRAGMA** [comment]
If I were to manually convert it by analysing the byte code by hand, how would I get the bytecode to analyse, as in how would I get a file of lines of data like:
```
2           0 LOAD_GLOBAL              0 (len)
              2 LOAD_FAST                0 (alist)
              4 CALL_FUNCTION            1
              6 RETURN_VALUE
```

**Comment by rocky** [comment]
The wiki has numerous examples for how to debug problems. Python documents the meaning of all of its opcodes. Above I am not seeing much effort on your part other htan soliciting help from someone else to do something possibly questionable.
