### ISSUE TITLE
Python 3.x star args function signatures

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#268]
The following fails in at least Python 3.2-3.7

```
def test_11(*args, name):
    return args, name

assert test_11(1, 2, 3, name='hi') == ((1, 2, 3), 'hi'), "*args name"

def test_12(a, *args, name):
    return a, args, name

assert test_11(1, 2, 3, name='hi') == ((1, 2, 3), 'hi'), "*args, name"
assert test_12(1, 2, 3, name='hi') == (1, (2, 3), 'hi'), "a, *args, name"
```

We get for example: 

```
    def test_11(*args, ):

```

The problem is in `make_function.py`, `build_param()` again. 

@x0ret - if you are not up for this, lemme know and I will look at.

**Comment by x0ret** [comment]
Thanks, I will take a look.

**Comment by x0ret** [comment]
@rocky, i managed to fix the issue for >= 3.4, but need your comment on this.

for 3.2, please consider following example:

```python
def test_12(a, *args, name):
    return a, args, name
```

however we have this:

```python
(Pdb) node
mkfunc (3)
     0. no_kwargs
     1. L.  10      48  LOAD_CODE                <code_object test_12>
     2.             51  MAKE_FUNCTION_0          '0 positional, 0 keyword only, 0 annotated'
(Pdb) kwonlyargcount
1
```

I'm confused here, first `0 keyword only` is for kw count? Second it seems parser failed to detect `kwargs`.

What do you think?

**Comment by x0ret** [comment]
Also it seems we have an issue in parse `classdef`(?) on py3.2, Please look at following example:

```python
class BoundedSemaphore(Semaphore):
    def __init__(self, value:int =1, *, loop=None):
        super().__init__(value, loop=loop)
```

results in:

```
   5       0  LOAD_FAST                '__locals__'
           3  STORE_LOCALS
           4  LOAD_NAME                __name__
           7  STORE_NAME               __module__

   6      10  LOAD_STR                 'loop'
          13  LOAD_NAME                None
          16  LOAD_CONST               1
          19  LOAD_NAME                int
          22  LOAD_CONST               ('value',)
          25  LOAD_CLOSURE             '__class__'
          28  BUILD_TUPLE_1         1
          31  LOAD_CODE                <code_object __init__>
          34  MAKE_CLOSURE_N1_A_2_1        '1 positional, 1 keyword only, 2 annotated'
          40  STORE_NAME               __init__
          43  LOAD_CLOSURE             '__class__'
          46  RETURN_VALUE
          -1  RETURN_LAST

Parse error at or near `STORE_NAME' instruction at offset 40
```

which is annotation related issue (Please try without `int` annotated arg `value`).

I tried to follow the issue, but i still new to `MAKE_FUNCTION` and ... in `parse3.py`. Sorry about that.

**Comment by rocky** [comment]
For the

```
     2.             51  MAKE_FUNCTION_0          '0 positional, 0 keyword only, 0 annotated'
```

This is correct, but what is _not_ shown are "name only" args, and apparently in order to be able to pick that out and get the value of the parameter apparently you need to look inside the code object: 

```
# Method Name:       test_12
# Filename:          exec
# Argument count:    1
# Kw-only arguments: 1
^^^^^^^^^^^^^^^^^^^^^^
# Number of locals:  3
# Stack size:        3
# Flags:             0x00000047 (NOFREE | VARARGS | NEWLOCALS | OPTIMIZED)
# First Line:        1
# Constants:

```

So the parsing and assembly display are correct here, even if they seems misleading.
 
I have to leave now, so I will look at hte classdef later.

**Comment by rocky** [comment]
> I tried to follow the issue, but i still new to MAKE_FUNCTION and ... in parse3.py. Sorry about that.

@x0ret  It is I that should be embarrassed for for not being more attentive and  careful when creating the rule. 50e46531 should fix this. However I see that the annotation types are missing in the final output, so back to you. This is something needed to be added in `make_function.py` now.

**Comment by rocky** [comment]
Down the line we could probably be more restrictive about what can be an annotation type. Right now it is an `expr` but I suspect it has to be some sort of identifier which would be some sort of `LOAD` like `LOAD_NAME` or `LOAD_FAST`.

**Comment by x0ret** [comment]
> Down the line we could probably be more restrictive about what can be an annotation type. Right now it is an expr but I suspect it has to be some sort of identifier which would be some sort of LOAD like LOAD_NAME or LOAD_FAST.

In my tests i didn't catch anything other than what you said, however reviewing python code `compiler_visit_argannotation` seems they treat the ann_arg as `expr`

```c
static int
compiler_visit_argannotation(struct compiler *c, identifier id,
    expr_ty annotation, PyObject *names)
{
    if (annotation) {
...
        VISIT(c, expr, annotation);
...
    }
    return 0;
}
```

**Comment by rocky** [comment]
>  ... reviewing python code compiler_visit_argannotation seems they treat the ann_arg as expr

@x0ret I am really glad you are looking at the C code generation for clarity and guidance. I should be doing this myself too.
