### ISSUE TITLE
Chained comparisons in `if` or `and`

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#274]
In Python 3.7.3 

```
digit = 1
if isinstance(digit, int) and 0 <= digit <= 9:
    pass
```
or

```
def chained_compare_b(a, obj):
    if a:
        if -0x80000000 <= obj <= 0x7fffffff:
            return 5

chained_compare_b(True, 0x0)
```

are not coming out correctly

**Comment by x0ret** [comment]
There may be an issue in <3.7, Please consider following example:

```python
def chained_compare_b(a, obj):
    if a:
        if -0x80000000 <= obj <= 0x7fffffff:
            return 5
```
which is decompiled to:

```python
def chained_compare_b(a, obj):
    if a:
        if -2147483648 <= obj <= 2147483647:
            pass
        return 5
```

And i think the return stmt is not correct, looking at the disassembly we have this:

```
                 1. _ifstmts_jump
                    return_if_stmts (3)
                         0. _stmts
                            stmt
                                ifstmt (2)
                   ...
                                     1. _ifstmts_jump
                                        pass
                         1. return_if_stmt (2)
                             0. ret_expr
                                expr
                                    L.   8      28  LOAD_CONST               5
                             1.             30  RETURN_END_IF
```

Sorry about the diff but this one seems fixes for 3.5 and 3.6 but i'm not sure about the side-effects:

```diff
diff --git a/uncompyle6/parsers/parse3.py b/uncompyle6/parsers/parse3.py
index 6a59acbc..d75d870d 100644
--- a/uncompyle6/parsers/parse3.py
+++ b/uncompyle6/parsers/parse3.py
@@ -149,7 +149,7 @@ class Python3Parser(PythonParser):
         testfalse ::= expr jmp_false
         testtrue ::= expr jmp_true

-        _ifstmts_jump ::= return_if_stmts
+        _ifstmts_jump ::= return_if_stmt
         _ifstmts_jump ::= c_stmts_opt COME_FROM

         iflaststmt  ::= testexpr c_stmts_opt JUMP_ABSOLUTE
```

Thanks

**Comment by rocky** [comment]
I spent probably too much time looking at this. This is a big mess.

Here is what's going on. The rule for `return_if_stmt` is fine. `RETURN_END_IF` is one of our renamed instructions for `RETURN`, and indeed `ret_exr` is a Python `return` statement. And indeed ends an `if` statement.

However there are *two* `if` statements. And grammar rules match both. If you add the `-g` option you can see (in 3.6) it associating with the correct `if`

```
L.  4:  28-30  return_if_stmt ::= ret_expr RETURN_END_IF (18)
... 
L.  4:  28     _ifstmts_jump ::= return_if_stmts (18)
L.  3:   4     _ifstmts_jump ::= return_if_stmts (18)
L.  4:  28     _stmts ::= stmt (18)
L.  3:   4-30  _stmts ::= _stmts stmt (18)
```

as well as the incorrect `if` further below:

```
L.  3:   4-32  return_if_stmts ::= _stmts return_if_stmt _come_froms (19)
               ifstmt ::= testexpr _ifstmts_jump (19)
L.  3:   4-32  ifstmt ::= testexpr _ifstmts_jump (19)
L.  4:  28     _ifstmts_jump ::= return_if_stmts (19)
L.  3:   4     _ifstmts_jump ::= return_if_stmts (19)
               stmt ::= ifstmt (19)
L.  3:   4     stmt ::= ifstmt (19)
               sstmt ::= stmt (19)
L.  3:   4     _stmts ::= stmt (19)
```

Probably easier to see this is to change the rule

```
        return_if_stmts ::= _stmts return_if_stmt _come_froms
```	

to :
```
        return_if_stmts ::= _stmts return_if_stmt _come_from
```	

Looking at the assembly the are _two_ `COME_FROM`s. One from the inner `if` and one from the outer `if`. By disallowing more than one `COME_FROM` all I did was remove the ambiguity so the right rule is used.

In older Python's this was less of a problem because there would be these I guess unecessary `POP_BLOCK` instructions.

Having more than one `COME_FROM`, however, is legitimate. The straight-forward approach to fix this would be to simply arranch to add marks to deliniate the end of a the "then" part of an "if", the end of an "else" part of an if and the end of the "if".

Parsers are good at counting nesting properly.  So in python-control-flow that's what we're trying to do. Please check to see that it gets this right. I think it does.

My sugggestion then is to leave this bug be. If it had to be fixed here, what I would do is add some sort of reduction check rule to make sure the `COME_FROM`s line up.  In control-flow terminology, that `return_if_stmt` belongs in the smallest "if" block that dominates it.

**Comment by x0ret** [comment]
Thanks for the detailed investigation.

> My suggestion then is to leave this bug be. If it had to be fixed here, what I would do is add some sort of reduction check rule to make sure the COME_FROMs line up. In control-flow terminology, that return_if_stmt belongs in the smallest "if" block that dominates it.

For now i take your suggestion and will focus on control-flow project then. (I was thinking to myself to handle other issues in this project and after reaching to a reasonable situation switch with full attention to `decompyle3` and `python-control-flow`, it seems i should change my approach : ) )

**Comment by rocky** [comment]
Thanks. It is so easy to get drawn into trying/hoping that somehow this could be fixed by some simple grammar-rule changes. In fact virtually everyone who has wored on this has thought that, including me. 

But in the end, after the countless hours of trying to patch things up, it ultimately fails.

bSo instead we have:
* added `COME_FROM`s,
*  added all that tricky and indecipherable code to "detect structure", 
* extended the `COME_FROM`s, to things like `COME_FROM_LOOP`, `ELSE`, `RETURN_IF_LOOP`, and,
*  added reduction tests. 

All of this is skirting around a problem that should have been met head one, and is hard.

And so there has been this steady progression of things getting worse and worse as Python code generation gets better and better. 

Here, for example, there is removal of unnecessary `POP_...` and `JUMP_..` instructions in recent Python for example. And in Python 3.8 things are going to get even worse.

**Comment by rocky** [comment]
Expanding on the comment:

>  In control-flow terminology, that return_if_stmt belongs in the smallest "if" block that dominates it.

One problems of redoing thing with real control flow is that is going to be slow getting all of Python's control-flow constructs in there and then getting that migrated. 

However I believe the dominator and reverse dominator code already work. (And that is a non-trivial piece of code). 

So one approach to truly fixing this, might be to compute the dominators and in a reduction-rule check verify if indeed the  `COME_FROM`s all are immediate dominators. (I don't know if we distinguish "immediate" though). 

I believe though this would be rather slow because testing could occur many times in the grammar.

**Comment by rocky** [comment]
At some point I backported this.
