### ISSUE TITLE
incorrect decompilation for if statements in with block.

### ISSUE THREAD

**Issue by thautwarm** [rocky/python-uncompyle6#277]
## Description

Wrong decompilations when it comes to the `with` syntax. 

## How to Reproduce

```python
from uncompyle6 import PYTHON_VERSION, deparse_code

def f(x, r=1):
    with match(x):
        if 0: return 1
        if x: return f(x-1, r * x)

deparse_code(PYTHON_VERSION, f.__code__)
```
outputs
```
with match(x):
    if x:
        return f(x - 1, r * x)
```

## Expected behavior

```python
from uncompyle6 import PYTHON_VERSION, deparse_code

def f(x, r=1):
    with match(x):
        if 0: return 1
        if x: return f(x-1, r * x)

deparse_code(PYTHON_VERSION, f.__code__)
```
outputs
```
with match(x):
    if 0:
        return 1
   if x:
        return f(x-1, r * x)
```

## Environment

- Uncompyle6 version: uncompyle6 3.3.3
- Python version: 3.7.2
- OS and Version: 4.19.56-1-MANJARO

**Comment by rocky** [comment]
There is a misunderstanding here. 

```python
if 0:  return 1
``` 

is vitually the same thing as removing that statement altogether. The python bytecode compiler notices this, and therefore doesn't generate any code for that `if` statement. If you disassemble the bytecode, you will see that whatever line(s) the `if 0` and `return 1` are on, do not appear in the assembly anywhere, whereas other lines with code in them have a line listed in the assembly (and line number table). 

If instead you change the `if 0` to some ohter expression that the Python interpreter can't figure out, such as `if r: return 1`, you'll see that `if` statement appear in decompilation.

**Comment by thautwarm** [comment]
Sorry, I must be drunk.
