### ISSUE TITLE
incorrect compilation of list/tuple unpacking in RHS

### ISSUE THREAD

**Issue by thautwarm** [rocky/python-uncompyle6#278]
## How to Reproduce

```python
import sys
from uncompyle6 import code_deparse 
def f():
    [a, *x]
code_deparse(f.__code__, sys.stdout)
```
=>
```
[(a,), x]
```

## Expected behavior

```python
import sys
from uncompyle6 import code_deparse 
def f():
    [a, *x]
code_deparse(f.__code__, sys.stdout)
```
=>
```
[a, *x]
```

## Environment

- Uncompyle6 version: ~~3.3.3~~ 3.3.5
- Python version: 3.7.2
- OS and Version: 4.19.56-1-MANJARO

**Comment by rocky** [comment]
@x0ret Are you interested in looking at this? 

For 

```python
a = 5
x = [1, 2, 3]
i = [(a,), x]
j = [(a,), x]
```

we get: 

```
 ... 
     2. sstmt
        stmt
            assign (2): ('%|%c = %p\n', -1, (0, 200))
                 0. expr
                    list (3)
                         0. expr
                            tuple (2)
                                 0. expr
                                    L.   3      14  LOAD_NAME                a
                                 1.             16  BUILD_TUPLE_1         1 
                         1. expr
                                        18  LOAD_NAME                x
                         2.             20  BUILD_LIST_2          2 
                 1. store
                                22  STORE_NAME               i
     3. sstmt
        stmt
            assign (2): ('%|%c = %p\n', -1, (0, 200))
                 0. expr
                    build_list_unpack (3)
                         0. expr
                            tuple (2)
                                 0. expr
                                    L.   4      24  LOAD_NAME                a
                                 1.             26  BUILD_TUPLE_1         1 
                         1. expr
                                        28  LOAD_NAME                x
                         2.             30  BUILD_LIST_UNPACK_2     2 
                 1. store
                                32  STORE_NAME               j
```

@thautwarm If you are going to report bugs please upgrade to the latest version, 3.3.5.

**Comment by thautwarm** [comment]
Change this line
https://github.com/rocky/python-uncompyle6/blob/3f9a86227777c61689bf3fb394902c8a76e97c13/uncompyle6/semantics/pysource.py#L1825
to `if lastnodetype.endswith("UNPACK") or lastnodetype.endswith("UNPACK_2"):` will work, but the pretty print seems to get messy after doing this:

```python
def f(x):
    return [1, *x]
```
produces
```
return [
 *(
  1,), *x]
```

However, at least the semantics matches the source code.

**Comment by rocky** [comment]
@thautwarm Code-wise @x0ret has things covered. If you want to help though you might create a program that has the following characteristics: you compile in Python 3.5+ decompile it and then run it and it checks that it doesn't have the bad behavior it currently has. (Here you might just assert variables `i` and `j` equal some Python literal constant .

Look https://github.com/rocky/python-uncompyle6/blob/master/test/simple_source/bug35/01_loop_if_continue.py

for one such example. The program `https://github.com/rocky/python-uncompyle6/blob/master/test/add-test.py` which given the `--run` option will compile the new test program and put in in the corresponding `bytecode_3x_run` directory.

**Comment by thautwarm** [comment]
Okay, thanks for your instructions and your fast resolutions.
I'll manage to add some tests then.
