### ISSUE TITLE
Scripts without header

### ISSUE THREAD

**Issue by Ekey** [rocky/python-uncompyle6#28]
Hi rocky. Is that possible to decompile scripts without header? I have game which uses (Python 2.7.x - CPython) with compiled variants and they not contain MAGIC and TIMESTAMP. Also some strings written in unicode. Can you check it?

Samples: https://www.sendspace.com/file/zgxhk2

Thanks advance! :+1: :)

**Comment by rocky** [comment]
Crazycompilers  <http://h.goebel@crazy-compilers.com> used to offer a paid
service for this kind of stuff (and if they need help, I'd be happy to
assist for in compensation for all of the great work they have done in the
past).  I'm not set up for this kind of thing.

**Comment by Ekey** [comment]
10 EUR per 5 KB (5120 bytes) - It is very much! 
63 479 685 bytes / 5120 bytes ~= 123980 EUR! I can buy 6 cars for that money :)

Anyway thanks for answer.
