### ISSUE TITLE
Synchronizing nonterminal names with Python AST grammar nonterminal names

### ISSUE THREAD

**Issue by rocky** [rocky/python-uncompyle6#29]
Write some sort of filter to turn uncompyle6's parse tree into [Python's  AST](https://docs.python.org/3/library/ast.html).  See the other transformers in `uncompyle6/semantics` for other kinds of transformations.

Some things to note. uncompyle6's parse tree is _not_ an AST (abstract syntax tree). In particular it is not abstract: a traversal of the leaves of the tree will produce the entire (pseudo-instruction augmented) instruction stream. So in contrast to an AST, there is nothing removed. See http://rocky.github.io/pycon2018.co/#/ for examples how how they differ. 

As with other phases of the program this phase will no doubt need customization per version as I'm sure the AST changes by Python version, if for no other reason as a result of new language. (But I suspect there are other things as well.)

@belph See above.

**Comment by belph** [comment]
As an addendum to this, would there be any interest in adding the capability of mapping the AST produced by `uncompyle6` to an AST from Python's `ast` module? The decompilation capabilities of `uncompyle6` are really awesome, and I was hoping to do some runtime bytecode hacking with it. That requires round-tripping the decompiled AST back into bytecode via `compile` or a self-rolled recompiler, though, and I imagine that the former would be easier to manage (though I may be wrong).

**Comment by rocky** [comment]
There is interest in what people are interested enough in participating in.

So if you would like to make a pass over the latest AST and uncompyle6's nonterminals to get them closer in sync with Python 3.6/3.7's do it and submit a pull request. 

There are something you should be aware of. First, I suspect the AST names like bytecode names have changed since they were first introduced. Second although at the top there can be some matching as you move lower down it's not going to work. I think even at the top the ideas are a little mismatched. 

Second, you'll never be able to get things to roundtrip all of the time. However I suspect you can get it to fixpoint after a couple of iterations.

**Comment by rocky** [comment]
If you look at commits 85d65e2 and be5efe3 you'll see the difficulty of trying to match up names. For something like 

```
x <= y <= z
```

the Python AST reports this as a `Compare` node is it would for `x <= y`. The difference is only in the number of children and that the `Compare` node has two comparison operators. 

In our grammar we need separate grammar rules for  `x <= y` versus `x <= y <= z` and that means different nonterminals which don't exist in the AST. In be5efe3 we did match up what had been `cmp` with `compare` having to rename the previous use of the `compare` nonterminal. 

As for matching up the Camel case ("Compare" versus "compare"), that kind of foolish consistency I've never been that big a fan of and it would mean a huge change everywhere. Instead I'd like to believe that programmers would be able to make the adjustment and in truth the two sets of nonterminals in the grammars have to be different. In those applications that use this, they are free to do an automatic camelcase conversion in display. 

Or at such time when there really is an application that would benefit by this we can do the massive and disruptive change.

However in your travels if you happen to find situations like this one, feel free point out the inconsistency and open a pull request. 

In my view for this you "vote" or "petition" for this by doing: finding situations and fixing. At this point, there is no magic wand one can wave to have this fixed, just hard work. 

(In defence of the original authors this predates by about a decade Python's lack of a standard AST that could have been consulted for names.)

**Comment by rocky** [comment]
In general this is impossible. However an initial pass was made to make the two look closer at the upper levels. Further issues, should be less broad and more specific with respect to nonterminal name correspondences.
