### ISSUE TITLE
Can't seem to make batch ops work

### ISSUE THREAD

**Issue by Cen-Silver** [rocky/python-uncompyle6#296]
Tried what was shown in the only two threads I found here from Google, but can't seem to make uncompyle6 work with batch operation and recursion on my files... (I can work single files just fine though)

I have the latest version as of now (3.5.1)
Win10 64Bits

PS: Sorry if I'm on the wrong section, my knowledge on using anything Github related is around 0, and the only options I saw here were bug report or feature request, and I thought this one was more fitting.

If this is wrong and there's anything I can do to fix it, please do tell.

**Comment by rocky** [comment]
Sorry, but I can't do anything with this information; it is too vague. I don't have the time or desire to get into an interactive dialogue to figure out what tried and did. 

For things like this, you are probably better off with StackOverflow or one of the various forums that guides you towards what is needed to explain a problem and is better suited to the back-and-forth questioning that seems to be needed here. 

If this is a bug, then follow the template given when you opened the issue. 

Sure, I understand you are a novice of Github, but that doesn't excuse you from reading instructions when it is offered.
