### ISSUE TITLE
decompile python3.6 pyc error

### ISSUE THREAD

**Issue by orxvan** [rocky/python-uncompyle6#299]
## Description

pyc file in python3.6 can't be decompiled by uncompyle6 ,all files in my project, even a simple file with 10 lines.

Error Report:
```
# file apps.pyc
# --- This code section failed: ---

   1       0  LOAD_CONST               0
           2  LOAD_CONST               ('AppConfig',)
           4  IMPORT_NAME              django.apps
           6  IMPORT_FROM              AppConfig
           8  STORE_NAME               AppConfig
          10  BINARY_OR

   4      12  <32>
          14  LOAD_CODE                <code_object CoreConfig>
          16  LOAD_STR                 'CoreConfig'
          18  MAKE_FUNCTION_0          ''
          20  LOAD_STR                 'CoreConfig'
          22  LOAD_NAME                AppConfig
          24  CALL_FUNCTION_3       3  ''
          26  STORE_NAME               CoreConfig
          28  LOAD_CONST               None
          30  <53>

Parse error at or near `None' instruction at offset -1
```
## How to Reproduce

```console

$ uncompyle6 apps.pyc


```

[py&pyc.zip](https://github.com/rocky/python-uncompyle6/files/3987363/py.pyc.zip)
apps.pyc and its source code apps.py all in this zip file

## Environment

```
# uncompyle6 version 3.6.0
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.7.4 (default, Aug 13 2019, 15:17:50)
# [Clang 4.0.1 (tags/RELEASE_401/final)]
# Mac OSX 10.15.2
```

**Comment by rocky** [comment]
What is the otput of  `Python -V` *on the Python that byte compiled this?*

**Comment by orxvan** [comment]
> What is the output of `Python -V` _on the Python 3.6 interpreter that byte compiled this?_

Python 3.6.8

**Comment by rocky** [comment]
And the output of `python -c "import sys; print(sys.version)"` ?

**Comment by rocky** [comment]
And one other thing. The ouptut of `python -c "import opcode; print(opcode.opname[53], opcode.opname[32])"`

**Comment by orxvan** [comment]
> And the output of `python -c "import sys; print(sys.version)"` ?
```
[root@economist-web-7fc5559bcf-hqrqq deploy]# python3 -c "import sys; print(sys.version)"
3.6.8 (default, May 21 2019, 14:04:21)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@economist-web-7fc5559bcf-hqrqq deploy]# python -c "import sys; print(sys.version)"
2.7.5 (default, Apr  9 2019, 14:30:50)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```



> Also what is the output of `python -c "import opcode; print(opcode.opname[53], opcode.opname[32])"` ?

```
[root@economist-web-7fc5559bcf-hqrqq deploy]# python -c "import opcode; print(opcode.opname[53], opcode.opname[32])"
('DELETE_SLICE+3', 'SLICE+2')
[root@economist-web-7fc5559bcf-hqrqq deploy]# python3 -c "import opcode; print(opcode.opname[53], opcode.opname[32])"
<53> <32>
```

and the main python interpreter should be python3

**Comment by rocky** [comment]
Ok. This bytecode isn't valid 3.6.8 bytecode or any 3.6 bytecode. 

In the future, when you open a bug issue here, please follow the instructions given better. In particluar include the python version, which instructed in the "Environment" section and when you give output. Also give the _input_  command you ran as well as the full ouput.

**Comment by orxvan** [comment]
> Ok. This bytecode isn't valid 3.6.8 bytecode or any 3.6 bytecode.
> 
> In the future, when you open a bug issue here, please follow the instructions given better. In particluar include the python version, which is instructed in the "Environment" section. Also make sure to give the _input_ command(s) you ran as well as the full ouput.

Sorry for lack some ENV information in this bug issue.
You said the bytecode is invalid in 3.6.8 or 3.6,but it can run in the Docker container which Python version is 3.6.8.
And the is bytecodes are made by the command 
```
python3 -m compileall -b FOLDER_NAME
```
so, how can I decompiled the pyc files which made by this command?
Thank you!
