### ISSUE TITLE
code section failed, Parse/Syntax error at or near "LOAD_NAME/CONTINUE" token

### ISSUE THREAD

**Issue by lotebi** [rocky/python-uncompyle6#305]
## Description
Getting wired **code section failed** errors with different versions of **uncompyle6**, **uncompyle2**, **Easy Python Decompiler** and https://python-decompiler.com/ (just mentioning because might help for better understanding of the problem) . After playing with original source code I was able to identify the problematic section and reproduced same error with the code below:

```
for i in x:
    if i:
        for ii in y:
            ii = True
    else:
        continue
    
    if i:
        break
```

Problem disappears if removing (or replacing with some simple assignment directives like i = True ) some different parts from the code above.
For example:
```
    if i:
```
from second line 

or 
```
        for ii in y:
            ii = True
```
from lines 3 - 4

or 
```
    if i:
        break
```
from the end.

Unfortunately don't know where to dig further, but will keep trying and would be glad to contribute if you could give me the right direction.

## How to Reproduce
just compile and uncompyle code provided above.

Outputs generated from pycharm for uncompyle6 and uncompyle2 from the same pyc file.

```console
# uncompyle6
# --- This code section failed: ---

   3         0  SETUP_LOOP           59  'to 62'
             3  LOAD_NAME             0  'x'
             6  GET_ITER         
             7  FOR_ITER             51  'to 61'
            10  STORE_NAME            1  'i'

   4        13  LOAD_NAME             1  'i'
            16  POP_JUMP_IF_FALSE     7  'to 7'

   5        19  SETUP_LOOP           26  'to 48'
            22  LOAD_NAME             2  'y'
            25  GET_ITER         
            26  FOR_ITER             12  'to 41'
            29  STORE_NAME            3  'ii'

   6        32  LOAD_NAME             4  'True'
            35  STORE_NAME            3  'ii'
            38  JUMP_BACK            26  'to 26'
            41  POP_BLOCK        
            42  JUMP_FORWARD          3  'to 48'

   8        45  CONTINUE              7  'to 7'
          48_0  COME_FROM            19  '19'
          48_1  COME_FROM            19  '19'

  10        48  LOAD_NAME             1  'i'
            51  POP_JUMP_IF_FALSE     7  'to 7'

  11        54  BREAK_LOOP       
            55  JUMP_BACK             7  'to 7'
            58  JUMP_BACK             7  'to 7'
            61  POP_BLOCK        
          62_0  COME_FROM             0  '0'

Parse error at or near `LOAD_NAME' instruction at offset 48



#uncompyle2
--- This code section failed: ---

0	SETUP_LOOP        '62'
3	LOAD_NAME         'x'
6	GET_ITER          None
7	FOR_ITER          '61'
10	STORE_NAME        'i'

13	LOAD_NAME         'i'
16	POP_JUMP_IF_FALSE '7'

19	SETUP_LOOP        '48'
22	LOAD_NAME         'y'
25	GET_ITER          None
26	FOR_ITER          '41'
29	STORE_NAME        'ii'

32	LOAD_NAME         'True'
35	STORE_NAME        'ii'
38	JUMP_BACK         '26'
41	POP_BLOCK         None
42	JUMP_FORWARD      '48'

45	CONTINUE          '7'
48_0	COME_FROM         '19'
48_1	COME_FROM         '42'

48	LOAD_NAME         'i'
51	POP_JUMP_IF_FALSE '7'

54	BREAK_LOOP        None
55	JUMP_BACK         '7'
58	JUMP_BACK         '7'
61	POP_BLOCK         None
62_0	COME_FROM         '0'

Syntax error at or near `CONTINUE' token at offset 45
```

## Environment

- Uncompyle6 version: uncompyle6 3.6.3
- Python version: Python 2.7.11
- OS and Version: Windows 10

**Comment by rocky** [comment]
Thanks for the detailed report. I think it is addressed by  6466d30. 

However by far this isn't the end of control-flow problems in Python 2.7 or more generally Python. I am in the middle of redoing this for Python 3 in the decompyle3 project, and although that is more stable and scalable, even after that is done, a complete revison of how control-flow is detected is needed.
