### ISSUE TITLE
Bad Marshal Data

### ISSUE THREAD

**Issue by backslash** [rocky/python-uncompyle6#309]
Currently using uncompyle6 and pyinstaller 2.1+
I run into this issue: https://stackoverflow.com/questions/60841666/decompiling-python-files-valueerror
I posted all of the information about the malformed value error. This seems to be an issue with uncompyle6 itself from my online research.

**Comment by rocky** [comment]
> This seems to be an issue with uncompyle6 itself from my online research.

In your online research you seem to have missed reading the instructions that are given when opening an issue. In particular: if you can't disassemble it, it aint an uncompyle6 or decompyle3 bug. 

Come back after you have a valid disassembly, and have read the instructions for given for reporting a bug or issue.
