### ISSUE TITLE
Spelling error in warning

### ISSUE THREAD

**Issue by secworks** [rocky/python-uncompyle6#311]
## Description
There is minor spelling error in the comment generated in the decompiled source.

The generated comment:
"Warning: this version has problems handling the Python 3 byte type in contants properly."

'contants' should be 'constants'

The string is here:
https://github.com/rocky/python-uncompyle6/blob/e80e72e6ab62e1e1bf123a9d2d2ba5f19497b623/uncompyle6/main.py#L105

**Comment by rocky** [comment]
Ok. Change made. Thanks!
