### ISSUE TITLE
Decompiling 3.6.9 pyc results in - Error: IndexError: list index out of range

### ISSUE THREAD

**Issue by Fohdeesha** [rocky/python-uncompyle6#327]
Hi! I know you're a busy guy and I can't provide the source code, so I don't expect a fix - just posting for posterity in case maybe it's a simple bug to fix on uncompyle6's side. I am adding some custom cli commands to my router distro which is all processed by a ton of 3.6.9 pyc files. So far Uncompyle6 has flawlessly decompiled all of them I've needed. However there's one last pyc I need to modify that checks the integrity of all the cli commands/netconf YANG crap that gets passed through it. It's using sysrepo-python. When running a decompile, this is what I get:

```
##Running Uncompyle6 under python 3.6.9:
root@testing:~/pycdc# uncompyle6 /usr/lib/yams/python/yams/util/sysrepo.pyc
# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Jul 17 2020, 12:50:27)
# [GCC 8.4.0]
# Embedded file name: /usr/lib/yams/python/yams/util/sysrepo.py
# Compiled at: 2020-08-18 01:00:57
# Size of source mod 2**32: 37976 bytes
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/uncompyle6/semantics/pysource.py", line 2079, in template_engine
    node[index]
  File "/usr/lib/python3.6/collections/__init__.py", line 1050, in __getitem__
    def __getitem__(self, i): return self.data[i]
IndexError: list index out of range

##Running Uncompyle6 under python 3.7.3:
root@testing:~/cli# uncompyle6 sysrepo.pyc
# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.7.3 (default, Jul 25 2020, 13:03:44)
# [GCC 8.3.0]
# Embedded file name: /usr/lib/yams/python/yams/util/sysrepo.py
# Compiled at: 2020-08-17 21:00:57
# Size of source mod 2**32: 37976 bytes
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uncompyle6/semantics/pysource.py", line 2079, in template_engine
    node[index]
  File "/usr/local/lib/python3.7/dist-packages/spark_parser/ast.py", line 23, in __getitem__
    return self.data[i]
IndexError: list index out of range
```

I tried to use Decompyle++ instead, which also errors out, but manages to spit out about 70% of the original py succesfully. It also successfully disassembled the whole file. Linked below are the original bytecode pyc, the failed partial py decompile from Decompyle++, as well as the assembly output from Decompyle++ - 

https://fohdeesha.com/pyc/sysrepo.pyc
https://fohdeesha.com/pyc/sysrepo-partial-failed.py
https://fohdeesha.com/pyc/sysrepo.pyc-assembly.txt

Thank you for reading!

**Comment by rocky** [comment]
With commit 1164cd90 this decompiled okay. 

However there should be other changes that need to be investigated as to why there error handling failed so badly, when there was a problem.

**Comment by Fohdeesha** [comment]
WOW! Thank you, I was not expecting that. Is there any place I can donate some beer money other than the github sponsorship?

**Comment by rocky** [comment]
Github sponsership is fine - thanks. You are like only the 2nd person to do so in all these months. 

(But in truth, right now I _am_ very busy and shouildn't devote too much time here.)
