### ISSUE TITLE
How to remap opcodes

### ISSUE THREAD

**Issue by a4321559** [rocky/python-uncompyle6#332]
## Description

i want to remap opcodes, how can i do that? 
do i need to rewrite xdis.opcodes?

**Comment by rocky** [comment]
> i want to remap opcodes, how can i do that?
> do i need to rewrite xdis.opcodes?

That'd probably would work. And it is just code so there are probably other ways as well.

Unless there are others who start getting involved in this project or it becomes funded better, we are really not in a position to serve as a discussion list for how things you might want to do  and how you might approach that. 

Possibly StackOverflow or something like that might be better suited. 

Sorry. Good luck hacking though!

**Comment by depgrey** [comment]
waiting for python 3.9
