### ISSUE TITLE
decompile failed,please help

### ISSUE THREAD

**Issue by weijie2018** [rocky/python-uncompyle6#334]
L. 110       168  BREAK_LOOP
->             170_0  COME_FROM           164  '164'
               170_1  COME_FROM           128  '128'
                 170  POP_BLOCK
                 172  LOAD_CONST               None
               174_0  COME_FROM_FINALLY    54  '54'
Instruction context:
->
 L. 354       776  BREAK_LOOP
             778_780  JUMP_BACK           388  'to 388'
               782_0  COME_FROM           394  '394'
                 782  POP_BLOCK
Instruction context:
->
 L. 502       642  BREAK_LOOP
                 644  JUMP_BACK           240  'to 240'
               646_0  COME_FROM           246  '246'
                 646  POP_BLOCK
Instruction context:

 L. 996         6  STORE_FAST               'td'
                   8  LOAD_DEREF               'company_name'
                  10  LOAD_FAST                'td'
                  12  COMPARE_OP               in
                  14  POP_JUMP_IF_FALSE_BACK     4  'to 4'
                  16  LOAD_STR                 ''
                  18  LOAD_FAST                'td'
                  20  COMPARE_OP               in
                  22  POP_JUMP_IF_TRUE     40  'to 40'
                  24  LOAD_STR                 ''
                  26  LOAD_FAST                'td'
                  28  COMPARE_OP               in
                  30  POP_JUMP_IF_TRUE     40  'to 40'
                  32  LOAD_STR                 '
[11.zip](https://github.com/rocky/python-uncompyle6/files/5492305/11.zip)

'
                  34  LOAD_FAST                'td'
                  36  COMPARE_OP               in
                  38  POP_JUMP_IF_FALSE_BACK     4  'to 4'
->              40_0  COME_FROM            30  '30'
                40_1  COME_FROM            22  '22'
                  40  LOAD_FAST                'td'
                  42  LIST_APPEND           2  ''
                  44  JUMP_BACK             4  'to 4'
                  46  RETURN_VALUE

# file login.pyc
# --- This code section failed: ---

 L. 996         0  BUILD_LIST_0          0
                2  LOAD_FAST                '.0'
              4_0  COME_FROM            44  '44'
              4_1  COME_FROM            38  '38'
              4_2  COME_FROM            14  '14'
                4  FOR_ITER             46  'to 46'

 L. 996         6  STORE_FAST               'td'
                8  LOAD_DEREF               'company_name'
               10  LOAD_FAST                'td'
               12  COMPARE_OP               in
               14  POP_JUMP_IF_FALSE_BACK     4  'to 4'
               16  LOAD_STR                 ''
               18  LOAD_FAST                'td'
               20  COMPARE_OP               in
               22  POP_JUMP_IF_TRUE     40  'to 40'
               24  LOAD_STR                 ''
               26  LOAD_FAST                'td'
               28  COMPARE_OP               in
               30  POP_JUMP_IF_TRUE     40  'to 40'
               32  LOAD_STR                 ''
               34  LOAD_FAST                'td'
               36  COMPARE_OP               in
               38  POP_JUMP_IF_FALSE_BACK     4  'to 4'
             40_0  COME_FROM            30  '30'
             40_1  COME_FROM            22  '22'
               40  LOAD_FAST                'td'
               42  LIST_APPEND           2  ''
               44  JUMP_BACK             4  'to 4'
               46  RETURN_VALUE
               -1  RETURN_LAST

Parse error at or near `COME_FROM' instruction at offset 40_0

**Comment by rocky** [comment]
The zip file doesn't unzip. Also, please follow the instruction that were given when you opened the ticket.

**Comment by weijie2018** [comment]
please  review,thanks!
[11pyc.txt](https://github.com/rocky/python-uncompyle6/files/5557062/11pyc.txt)

[11pyc.zip](https://github.com/rocky/python-uncompyle6/files/5557060/11pyc.zip)

**Comment by rocky** [comment]
What does this code do?
