### ISSUE TITLE
Is it possible to package Uncompyle6 with another project using pyinstaller

### ISSUE THREAD

**Issue by GhostNaix** [rocky/python-uncompyle6#337]
Is it possible to package Uncompyle6 with another project into one single executable using pyinstaller ?
I tried however when I run the executable it returns an error:
`No module named scanner27`
I wish to be able to distribute this project to computers who don't have python install

**Comment by extremecoders-re** [comment]
I've managed to successfully package uncompyle6 with PyOxidizer rather than PyInstaller. May be helpful.

https://github.com/extremecoders-re/uncompyle6-builds

**Comment by rocky** [comment]
Ok so question answered. And I think if you use the google there are other tools as well.

**Comment by GhostNaix** [comment]
OK decided to investigate this again since this was backlogged for ages apparently you add `--hidden-import uncompyle6.scanners.scanner38` or `--hidden-import uncompyle6.scanners.scanner27` in this case.
