### ISSUE TITLE
runtime errors after installing from uncompyle6-2.5.0.tar.gz

### ISSUE THREAD

**Issue by w00127960** [rocky/python-uncompyle6#34]
Downloaded
https://pypi.python.org/packages/d3/b4/af8130cbf6826d2fbc66dedaf4a14e449db880557413d63bd1fb79973209/uncompyle6-2.5.0.tar.gz#md5=b632fff4a10273055cf8a59c44c75892

installed via "python setup.py install"

tried on: 
RH Linux 6, Python 2.6.6)
Windows 10 + Cygwin, Python 2.7.10
Windows 10, Python 2.7.12

In each case executing uncompyle6 I get always some form of import error (formatting is slightly different depending on version), here for Windows:

```
c:\Python27\Scripts>uncompyle6.exe -v
Traceback (most recent call last):
  File "c:\Python27\Scripts\uncompyle6-script.py", line 9, in <module>
    load_entry_point('uncompyle6==2.5.0', 'console_scripts', 'uncompyle6')()
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
    return self.resolve()
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2239, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main_bin'
```

With the 2.4 version I have no such issue.

**Comment by rocky** [comment]
I think I see where I messed up in the packaging  which [44c03ff] should address.

Here's a workaround until another release is cut. Find where the `uncompyle6` script is installed. In that file you see the line:

```python
from uncompyle6.bin import main_bin
```

Change that to: 
```python
from uncompyle6.bin.uncompile import main_bin
```

Another workaround for CentOS in to call `bin/uncompile` which gets installed somewhere when you ran `setup.py install`. Details on the location below, but here are the details for CentOS6.

```console
 /usr/lib/python2.6/site-packages/uncompyle6-2.5.0-py2.6.egg/uncompyle6/bin/uncompile.py --help
Usage:
  uncompile [OPTIONS]... [ FILE | DIR]...
  uncompile [--help | -h | --V | --version]
```
As for how to find that location. When I ran `setup.py install` somewhere I saw: 

```
Extracting uncompyle6-2.5.0-py2.6.egg to /usr/lib/python2.6/site-packages
```

and this tells me to look in `/usr/lib/python2.6/site-packages` for `bin/uncompile.py`

**Comment by glensc** [comment]
the workardound suggesting to modify script doesn't work for installed packages, as those are autogenerated entrypoints:

```
➔ cat /usr/bin/uncompyle6
#!/usr/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'uncompyle6==2.5.0','console_scripts','uncompyle6'
__requires__ = 'uncompyle6==2.5.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('uncompyle6==2.5.0', 'console_scripts', 'uncompyle6')()
    )

```

**Comment by rocky** [comment]
I'll put out a new release in the not-too-distant future.

**Comment by w00127960** [comment]
making the change in __pkg_info__ and re-installing fixes the error

but I have here 4 files which do not decompile, I attached the output in
case you are interested

thanks for your help and the program
Michael

**Comment by rocky** [comment]
I don't see a new attachment, but that's probably just as well. Create new issues one for each program. That way, the progress or lack of can be tracked independently. Thanks.

**Comment by rocky** [comment]
2.6.0 is out and should address this.

**Comment by glensc** [comment]
thanks. the tests also pass (#35)
