### ISSUE TITLE
decompiled source code is mixed with Instruction context: and python code

### ISSUE THREAD

**Issue by retsyo** [rocky/python-uncompyle6#342]
When I use uncompyle6 on a python 3.8 pyc file, I get something like the following
Why the result is mixed with op-code and python code? And How to get all the real python code?
Thanks

```python

Instruction context:
   
 L.1798        86  POP_BLOCK        
                  88  POP_EXCEPT       
->                90  CALL_FINALLY         96  'to 96'
                  92  LOAD_CONST               None

....   # more are omitted for clear reason

import logging
log = logging.getLogger(__name__)
import PySide2
import pyqtgraph

```

**Comment by rocky** [comment]
You'll get this whenever some decompilation fails for a partricular function or module

Please read and follow the instructions given when you open an issue: https://github.com/rocky/python-uncompyle6/issues/new?assignees=&labels=&template=bug-report.md
