### ISSUE TITLE
Error while decompiling a file 

### ISSUE THREAD

**Issue by wacns** [rocky/python-uncompyle6#346]
Hi rocky,
when I tried to decompiling a file I have got an error which is
" AttributeError: xdis.opcodes.opcoode_39 has no attribute 'END_FINALLY'
I wish you are able to help me.

**Comment by rocky** [comment]
https://stackoverflow.com/questions/66550211/decompiling-pyc-files-for-python-3-9-2

**Comment by wacns** [comment]
Traceback (most recent call last):
  File
"C:\Users\abody\AppData\Local\Programs\Python\Python36-32\lib\runpy.py",
line 193, in _run_module_as_main
    "__main__", mod_spec)
  File
"C:\Users\abody\AppData\Local\Programs\Python\Python36-32\lib\runpy.py",
line 85, in _run_code
    exec(code, run_globals)
  File
"C:\Users\abody\Documents\PROECTS\TweakPY_bot\F-19.exe_extracted\lowpython36\Scripts\uncompyle6.exe\__main__.py",
line 9, in <module>
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\bin\uncompile.py",
line 194, in main_bin
    **options)
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\main.py",
line 324, in main
    do_fragments,
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\main.py",
line 222, in decompile_file
    do_fragments=do_fragments,
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\main.py",
line 141, in decompile
    co, out, bytecode_version, debug_opts=debug_opts, is_pypy=is_pypy
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\semantics\pysource.py",
line 2570, in code_deparse
    scanner = get_scanner(version, is_pypy=is_pypy)
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\scanner.py",
line 566, in get_scanner
    "scan.Scanner%s(show_asm=show_asm)" % v_str, locals(), globals()
  File "<string>", line 1, in <module>
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\scanners\scanner39.py",
line 36, in __init__
    Scanner37Base.__init__(self, 3.9, show_asm)
  File
"c:\users\abody\documents\proects\tweakpy_bot\f-19.exe_extracted\lowpython36\lib\site-packages\uncompyle6\scanners\scanner37base.py",
line 98, in __init__
    self.opc.END_FINALLY,
AttributeError: module 'xdis.opcodes.opcode_39' has no attribute
'END_FINALLY'

‫في الجمعة، 7 مايو 2021 في 4:10 ص تمت كتابة ما يلي بواسطة ‪R. Bernstein‬‏ <‪
***@***.***‬‏>:‬
