### ISSUE TITLE
Adding Python 3.9 support

### ISSUE THREAD

**Issue by Irval1337** [rocky/python-uncompyle6#347]
Hello. Could you please add Python 3.9 support for your library?

**Comment by rocky** [comment]
Right now there's not enough support from the community me to get involved in this. But this is open source so free to start working on it.

**Comment by praveenpgeb** [comment]
hi its not working for python 3.9 plz update

**Comment by Irval1337** [comment]
https://github.com/rocky/python-uncompyle6/issues/331
