### ISSUE TITLE
jump_back_index = self.offset2tok_index[jump_target] -

### ISSUE THREAD

**Issue by leejshades** [rocky/python-uncompyle6#349]
![image](https://user-images.githubusercontent.com/7189444/121988571-2b194c00-cdcd-11eb-9eb6-f1a7a86c5d07.png)

**Comment by leejshades** [comment]
![image](https://user-images.githubusercontent.com/7189444/121988603-39fffe80-cdcd-11eb-812f-dce534f1b80a.png)

**Comment by rocky** [comment]
This isn't something that anyone can make use of. Read an follow the instructions in https://github.com/rocky/python-uncompyle6/issues/new?&template=bug-report.md  and the "How to Reproduce" section.
