### ISSUE TITLE
Syntax error at or near `COME_FROM' token at offset 46_1

### ISSUE THREAD

**Issue by glensc** [rocky/python-uncompyle6#35]
testing fails running under python 2.7 with 2.5.0 release:
[2.5.0.txt](https://github.com/rocky/python-uncompyle6/files/346082/KJRj.txt)

note: 2.4.0 release tests do pass:
[2.4.0.txt](https://github.com/rocky/python-uncompyle6/files/346087/bAFc.txt)

**Comment by rocky** [comment]
I don't think this is a problem in the current github code. So try with that and let me know if it is still a problem. 

There's been some long-overdue code refactoring. (Much more is needed though). In that, the way that bytecode for 2.6 and 2.5 is handled is a bit different. Alas, in some cases there is a regression from what worked in uncompyle2 for python 2.6 and even more so in especially 2.5.

Addressing the problems in 2.5 and 2.6 is largely a matter of work.

**Comment by glensc** [comment]
not reproducible with master (0adf70b4d92496dbc387880b4395a85e3f345d59), so closing
