### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by schmatteo** [rocky/python-uncompyle6#358]
PS C:\Users\admin\Documents\py> uncompyle6.exe mod_antitoxicity.pyc
# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
# Embedded file name: mod_antitoxicity
# Compiled at: 2020-12-12 20:45:08
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\uncompyle6.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\uncompyle6\bin\uncompile.py", line 194, in main_bin
    **options)
  File "c:\python27\lib\site-packages\uncompyle6\main.py", line 324, in main
    do_fragments,
  File "c:\python27\lib\site-packages\uncompyle6\main.py", line 222, in decompile_file
    do_fragments=do_fragments,
  File "c:\python27\lib\site-packages\uncompyle6\main.py", line 141, in decompile
    co, out, bytecode_version, debug_opts=debug_opts, is_pypy=is_pypy
  File "c:\python27\lib\site-packages\uncompyle6\semantics\pysource.py", line 2573, in code_deparse
    co, code_objects=code_objects, show_asm=debug_opts["asm"]
  File "c:\python27\lib\site-packages\uncompyle6\scanners\scanner2.py", line 211, in ingest
    bytecode = self.build_instructions(co)
  File "c:\python27\lib\site-packages\uncompyle6\scanner.py", line 132, in build_instructions
    self.insts = self.remove_extended_args(list(bytecode))
  File "c:\python27\lib\site-packages\xdis\bytecode.py", line 234, in get_instructions_bytes
    argrepr = opc.opcode_arg_fmt[opc.opname[op]](arg)
  File "c:\python27\lib\site-packages\xdis\opcodes\base.py", line 433, in format_RAISE_VARARGS_older
    assert 0 <= argc <= 3
AssertionError

How to fix it and successfully decompile this file if this happens?

**Comment by rocky** [comment]
Read instructions for how to report a bug.

**Comment by jekeam** [comment]
> PS C:\Users\admin\Documents\py> uncompyle6.exe mod_antitoxicity.pyc
> 
> # uncompyle6 version 3.7.4
> # Python bytecode 2.7 (62211)
> # Decompiled from: Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
> # Embedded file name: mod_antitoxicity
> # Compiled at: 2020-12-12 20:45:08
> Traceback (most recent call last): File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main "**main**", fname, loader, pkg_name) File "c:\python27\lib\runpy.py", line 72, in _run_code exec code in run_globals File "C:\Python27\Scripts\uncompyle6.exe__main__.py", line 9, in File "c:\python27\lib\site-packages\uncompyle6\bin\uncompile.py", line 194, in main_bin **options) File "c:\python27\lib\site-packages\uncompyle6\main.py", line 324, in main do_fragments, File "c:\python27\lib\site-packages\uncompyle6\main.py", line 222, in decompile_file do_fragments=do_fragments, File "c:\python27\lib\site-packages\uncompyle6\main.py", line 141, in decompile co, out, bytecode_version, debug_opts=debug_opts, is_pypy=is_pypy File "c:\python27\lib\site-packages\uncompyle6\semantics\pysource.py", line 2573, in code_deparse co, code_objects=code_objects, show_asm=debug_opts["asm"] File "c:\python27\lib\site-packages\uncompyle6\scanners\scanner2.py", line 211, in ingest bytecode = self.build_instructions(co) File "c:\python27\lib\site-packages\uncompyle6\scanner.py", line 132, in build_instructions self.insts = self.remove_extended_args(list(bytecode)) File "c:\python27\lib\site-packages\xdis\bytecode.py", line 234, in get_instructions_bytes argrepr = opc.opcode_arg_fmt[opc.opname[op]](arg) File "c:\python27\lib\site-packages\xdis\opcodes\base.py", line 433, in format_RAISE_VARARGS_older assert 0 <= argc <= 3 AssertionError
> 
> How to fix it and successfully decompile this file if this happens?

I also wanted to modify this mod, but encountered the same error, did you manage to figure out the problem?

**Comment by rocky** [comment]
> > How to fix it and successfully decompile this file if this happens?
> 
> I also wanted to modify this mod, but encountered the same error, did you manage to figure out the problem?

@jekeam Did you manage to read and follow the instructions?

**Comment by jekeam** [comment]
> Did you manage to read and follow the instructions?
Do you pray for instructions? I prefer to solve problems.

**Comment by rocky** [comment]
And I prefer for you solve your own problems.
