### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [rocky/python-uncompyle6#363]
## Description
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

## Background
Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/uncompyle6/lokal -name '*.py')
```

How do you think about to improve 14 source code places? :thinking:

**Comment by rocky** [comment]
I don't really understand what is being asked other than you want some code changed to assist in some analysis tools which might "improve software components".  And this is pretty vague.

First of all, this is open-source software, so as long as the result is GPL you are free to change the code any way you want.
As for getting the code back into the code base, submit a PR and we'll look what the changes are.  I am open to submitting a PR for changing one of the 14 or so files to get better idea of the change part. As for the _why_ part, I'd appreciate understanding in more detail  what is meant.

**Comment by elfring** [comment]
:thought_balloon: Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")?

**Comment by rocky** [comment]
I'll say probably not, but again, honestly, I really don't know what it is you are asking. That link is to Python 3 docs and you are asking about Python2.  Ask a very specific detailed question if you want a detailed answer. Or maybe you should be asking StackOverflow about such questions.
