### ISSUE TITLE
Xdis Imcode Compiler Flag Error

### ISSUE THREAD

**Issue by TechQaiser** [rocky/python-uncompyle6#367]
Sir Fix This Problem Or Whats The Matter Thats What We All Termux Users Facing This Prob In uncompyle6 Kindly Please Fix ed It . Thanks & Regards 😍
![Screenshot_20211113-231806](https://user-images.githubusercontent.com/69212320/141655268-a247c998-65a2-41e2-9b65-1b135f7fda01.png)

**Comment by rocky** [comment]
Looks like no one is available to help you. :-(
