### ISSUE TITLE
some decompyle runtime errors

### ISSUE THREAD

**Issue by w00127960** [rocky/python-uncompyle6#37]
[decompyle.errors.gz](https://github.com/rocky/python-uncompyle6/files/348902/decompyle.errors.gz)

not much to say, this is the output of 5 errors during decompilation

**Comment by rocky** [comment]
Please try with the current github sources, not the last release. There were a number of bugs fixed since the last release. 

Also separate into one issue per compilation problem. Not one issue per library.. Thanks.

**Comment by w00127960** [comment]
only one left when using the github sources is:

```
# file stats.pyc
# --- This code section failed: ---

 249       0  SETUP_LOOP        '68'
           3  LOAD_FAST         '.0'
           6  FOR_ITER          '67'
           9  STORE_FAST        'point'
          12  LOAD_DEREF        'start'
          15  LOAD_FAST         'point'
          18  LOAD_ATTR         'dt'
          21  DUP_TOP           ''
          22  ROT_THREE         ''
          23  COMPARE_OP        '<='
          26  JUMP_IF_FALSE     '39'
          29  POP_TOP           ''
          30  LOAD_DEREF        'stop'
          33  COMPARE_OP        '<'
          36  JUMP_FORWARD      '41'
        39_0  COME_FROM         '26'
          39  ROT_TWO           ''
          40  POP_TOP           ''
        41_0  COME_FROM         '36'
          41  JUMP_IF_FALSE     '63'
          44  POP_TOP           ''
          45  LOAD_FAST         'point'
          48  LOAD_ATTR         'len'
          51  JUMP_IF_FALSE     '63'
          54  POP_TOP           ''
          55  LOAD_FAST         'point'
          58  YIELD_VALUE       ''
          59  POP_TOP           ''
          60  JUMP_BACK         '6'
        63_0  COME_FROM         '41'
        63_1  COME_FROM         '51'
          63  POP_TOP           ''
          64  JUMP_BACK         '6'
          67  POP_BLOCK         ''
        68_0  COME_FROM         '0'

Syntax error at or near `COME_FROM' token at offset 63_1

```

**Comment by rocky** [comment]
1. What version of python are you using? Use  python -V  and copy the output.
2. Attach a copy of the byte compiled file that has  a problem. This file is not part github sources or test files. It is is something you happen to have installed in your Python library setup.

**Comment by w00127960** [comment]
$ python --version
Python 2.7.10

**Comment by w00127960** [comment]
[stats.pyc.txt](https://github.com/rocky/python-uncompyle6/files/353246/stats.pyc.txt)

**Comment by rocky** [comment]
stats .py doesn't have a magic number that matches what python --version gives. 

So now attach the source code.

**Comment by w00127960** [comment]
can't, don't have the source :)

**Comment by rocky** [comment]
Ok. Given that pycdc and older uncompyle barf on that bytecode too, there's nothing I can do to fix this. 

We'll wait then for some other situation where someone has the source code.
