### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by formula-x** [rocky/python-uncompyle6#371]
Is this for hacking paid software in order to engineer

**Comment by rocky** [comment]
Issues are for feature reports and bugs not questions or discussions. This sounds like a troll.

The README has a section called "Why this?" Read that and this history of project.

Before asking a question that I personally will answer, I need to see some effort by the poster, especially if  that  poster is anonymous to have made an effort to seek out answers first.

**Comment by formula-x** [comment]
This seems like you’re helping others to steal paid software. If you don’t
answer my question I’ll be forced to report this repo.

**Comment by formula-x** [comment]
I read the readme but even after reading it this looks like something to
assist others with hacking authentication systems for software. It also
looks like a package used to reverse engineering. I myself work on desktop
apps that I don’t want to share the source code for and this infringes on
that privacy..
