### ISSUE TITLE
getsource from already import pyc file

### ISSUE THREAD

**Issue by djerryz** [rocky/python-uncompyle6#387]
## Description

Current, use uncompyle6 with :
```
uncompyle6 flag.pyc
```
This Ask we have a good static pyc file.

But in my scene, pyc is confuse , so it cannot decompile by uncompyle6 directly.
Luckly, I load another runtime library , and then i can import  confuse 'flag.pyc'.
Also, I can use globals() to list its attr.

The question is , i wanna modify a value in flag.pyc. 
so  i have to get its source to flag.py , modify value ,and recompile it to pyc, replace old one to win the game. (Like a HotFix)
And now , i already import confuse flag.pyc to memory but cannot use uncompyle6 to get its source .
I really need your help ,thank you very much.

**Comment by djerryz** [comment]
seems ,if we can get code_object , then we can get source...
how to get import module code_object

**Comment by djerryz** [comment]
More, Real Question is how xdis.load get **co** from already import module

**Comment by djerryz** [comment]
>>> help(marshal.load)
Help on built-in function load in module marshal:

load(file, /)
    Read one value from the open file and return it.

      file
        Must be readable binary file.

    If no valid value is read (e.g. because the data has a different Python
    version's incompatible marshal format), raise EOFError, ValueError or
    TypeError.

    Note: If an object containing an unsupported type was marshalled with
    dump(), load() will substitute None for the unmarshallable type.

if we can marshal.dump imported module .. and then use marshl.load it

**Comment by djerryz** [comment]
```
import marshal
def func_a(num):
    print(num)

co = marshal.loads(marshal.dumps(func_a.__code__))
>>> help(co)
 |  Data descriptors defined here:
 |
 |  co_argcount
 |
 |  co_cellvars
 |
 |  co_code
 |
 |  co_consts
 |
 |  co_filename
 |
 |  co_firstlineno
 |
 |  co_flags
 |
 |  co_freevars
 |
 |  co_kwonlyargcount
 |
 |  co_lnotab
 |
 |  co_name
 |
 |  co_names
 |
 |  co_nlocals
 |
 |  co_stacksize
 |
 |  co_varnames
 
>>> co.co_name
'func_a'
>>> co.co_names
('print',)
>>> co.co_varnames
('num',)
```

**Comment by djerryz** [comment]
```
import marshal

def func_a(num):
    print(num)

with open("a_func.bin", "wb") as f:
    f.write(marshal.dumps(func_a.__code__))
```

```
from uncompyle6.main import decompile
import marshal

version = (3,7,0)
with open("a_func.bin", "rb") as fp:
    bytecode = fp.read()
    co = marshal.loads(bytecode)
outfile = "re_func_a.py"
out_stream = open(outfile, mode="w", encoding="utf-8")
decompile(
        version,
        co,
        out_stream
    )
out_stream.close()
```

There are a **BUG HERE!! re_func_a.py Don't have def function name!!**

cat re_func_a.py:
```
# uncompyle6 version 3.8.0
# Python bytecode 3.7.0
# Decompiled from: Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: <stdin>
print(num)
```

**Comment by djerryz** [comment]
```
import inspect
from importlib import import_module

module = import_module("hello2")
source = inspect.getsource(module)
```

just have compiled file hello2.pyc, will not work.

**Comment by djerryz** [comment]
-> import a module 
-> marshal.dumps 
-> marshal.loads
-> uncompyle6

shortcoming:
* marshal.dumps  seems support data, function, but not class , module
* loop all attr which already been load

really need a more smart way.

**Comment by rocky** [comment]
I am sorry but this is not the right place to solicit help for something you would like to be able to do for which bytecode decompilation might be needed in one of the steps you need to do. 

https://reverseengineering.stackexchange.com/ or https://stackoverflow.com/ or a chat board on reverse engineering seems like a more appropriate venue for this kind of "I want to be able to do something, how do I do it?" kind of thing. 

If there is an urgent legitimate need  for  personal help, paid consultation is available.

**Comment by djerryz** [comment]
Thank you. ❤ . I really support paid for knowledge.

**Comment by djerryz** [comment]
worry about my poor english can not have a well talk with you. 
i think i should learn more python Basic knowledge which not in application layer but in Cpython self.
