### ISSUE TITLE
Can't run uncompyle6 on manjaro

### ISSUE THREAD

**Issue by ahmedmoselhi** [rocky/python-uncompyle6#390]
Hi i have installed uncompyle6 on manjaro 21.2.5 but when i try to run it i get this error:
`Traceback (most recent call last):
  File "/home/ahmed/.local/bin/uncompyle6", line 5, in <module>
    from uncompyle6.bin.uncompile import main_bin
ModuleNotFoundError: No module named 'uncompyle6'`

**Comment by rocky** [comment]
This looks like a generic problem in installing Python and the way it works. You are better off asking in some kind of channel like  https://stackoverflow.com/ that is suited towards helping people install Python packages or working on manjaro.
