### ISSUE TITLE
Uncompyle6 Trouble with decompilation

### ISSUE THREAD

**Issue by NotCookey** [rocky/python-uncompyle6#402]
I'm trying to decompile a file called `main.pyc`, i believe its written in 3.10 so i've installed 3.10 and ran uncompyle6 using `C:\Users\XXX\AppData\Local\Programs\Python\Python310\Scripts>uncompyle6.exe main.pyc>m.py`

But i get an error saying that -
```
# uncompyle6 version 3.8.0
# Python bytecode 3.10.0 (3439)
# Decompiled from: Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: obf\main.py

Unsupported Python version, 3.10.0, for decompilation
```

I would really appreciate if anyone could help what i'm doing wrong-

**Comment by rocky** [comment]
You are not reading error messages given or enough of an effort to see what information about this has been written before. 

https://github.com/rocky/python-uncompyle6/issues/331
