### ISSUE TITLE
Parse error at or near `COME_FROM' instruction

### ISSUE THREAD

**Issue by dog8848** [rocky/python-uncompyle6#410]
hello,I am a personal developer. I lost my source code due to carelessness and want to use decompilation to recover it. I encountered this problem:

  File "D:\PycharmProjects\NetworkProtocolScripts\venv\lib\site-packages\uncompyle6\parsers\reducecheck\ifelsestmt.py", line 176, in ifelsestmt
    if last_token == "COME_FROM" and tokens[first].offset > last_token.attr:
Exception in ifelsestmt '>' not supported between instances of 'str' and 'int'
rule: ifelsestmt ::= testexpr c_stmts_opt jump_forward_else else_suite \e__come_froms
offsets 4584_4586 .. 4830_0

**Comment by rocky** [comment]
Sorry to hear about your loss. In order to work on this you need to read and follow instructions given in https://github.com/rocky/python-uncompyle6/issues/new?assignees=&labels=&template=bug-report.md
