### ISSUE TITLE
AssertionError: None does not smell like code 

### ISSUE THREAD

**Issue by ducquan311** [rocky/python-uncompyle6#421]
![image](https://user-images.githubusercontent.com/72018110/201380875-121d9ca1-cf50-4595-ad37-97428dcd8cd7.png)
I can't uncompile this file.What should i do ?
Thank all

**Comment by rocky** [comment]
> What should i do ?

Read and follow the instructions in https://github.com/rocky/python-uncompyle6/issues/new?assignees=&labels=&template=bug-report.md
