### ISSUE TITLE
AssertionError: None does not smell like code

### ISSUE THREAD

**Issue by lovelylee** [rocky/python-uncompyle6#433]

**Comment by SpaceHan** [comment]
have you run uncompyle6 in the same python version of the .pyc file(which will be printed after you pyinstxtractor finished extracting .pyc from .exe)

**Comment by rocky** [comment]
Have you read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md#do-you-have-valid-bytecode  and the rest of that and PREREQUESITS and CAVEATS in https://raw.githubusercontent.com/rocky/python-uncompyle6/master/.github/ISSUE_TEMPLATE/bug-report.md ?
