### ISSUE TITLE
Pyc error decompile

### ISSUE THREAD

**Issue by binaryapi** [rocky/python-uncompyle6#434]
when i decompile pyc file i have this error apear

__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF__SFSF_SFSF += 'U0ZfU0ZTRl9fU0ZTRl9TRlNGX19TRlNGX1NGU0ZfX1NGU0ZfU0ZTRl9fU0ZTRl9TRlNGX19TRlNGX1NGU0ZfX1NGU0ZfU0ZTRl9f'  

...... until the end of file with 

exec(marshal.loads(zlib.decompress(lzma.decompress(base64.b64decode(base64.b16decode(base64.b32decode(base64.b85decode(b'M@mFQO ...........

**Comment by rocky** [comment]
Please read the guidelines for opening an issue.
