### ISSUE TITLE
Error in unicode decompilation Python 2.7

### ISSUE THREAD

**Issue by andrem-eberle** [rocky/python-uncompyle6#443]
## Description

Unicode strings in Python 2.7.18 are generating regular strings after decompilation.

This one might be a minor bug, and usually not an issue, but it breaks some tests in test_ast.py for the 2.7.18.

Also this one seems to include potential xdis disasm errors also, as it doesn't seem to flag the string as unicode?

## How to Reproduce

Input:
```
var1 = u'x'
var2 = 'x'
print(type(var1))
print(type(var2))
```
run compileall & uncompyle6

## Output Given
```
var1 = 'x'
var2 = 'x'
print(type(var1))
print(type(var2))
```

Running the first code will give:
```
<type 'unicode'>
<type 'str'>
```

For the uncompiled code:

```
<type 'str'>
<type 'str'>
```
## Expected behavior

Should return the correct unicode form for the string.

## Environment

Python 2.7.18
Ubuntu 16.0x

**Comment by rocky** [comment]
I am not totally sure, but this is probably better corrected in xdis, and then possibly no change is needed in this project.

**Comment by rocky** [comment]
This was more an xdis bug than an uncompyle6 bug. The master branch of xdis now corrects this.

**Comment by Naim75o** [comment]
:blush:
