### ISSUE TITLE
Wrong import in Python 2.7.18

### ISSUE THREAD

**Issue by andrem-eberle** [rocky/python-uncompyle6#448]
## Description

Certain imports in Python 2.7 are being decompiled wrong

## How to Reproduce

Input file.py:
```
"""a doc"""

from contextlib import *
```
```
python2.7 -m compileall file.py && python3.8 uncompyle6 file.pyc
```
## Output Given

```
__doc__ = 'a doc'
from .contextlib import *
```

It adds a relative import to contextlib which shouldn't be there.

## Expected behavior

Correct import line

## Environment

Python 2.7.18 for compileall
Python 3.8.16 for uncompyle6
Ubuntu 16.0x

**Comment by rocky** [comment]
Fixed by #449
