### ISSUE TITLE
'uncompyl6' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Misterpopcorn12** [rocky/python-uncompyle6#454]
i got python 3.10, and i installed all of the files and finished all, then when i head over to cmd its saying 'uncompyl6' is not recognized as an internal or external command,
operable program or batch file.

maybe a bad install

**Comment by rocky** [comment]
Stackoverflow or something similar is a more appropriate venue for this kind of thing.
