### ISSUE TITLE
Unknown magic number 3495 in Demand_Change_Report.pyc

### ISSUE THREAD

**Issue by BoldHu** [rocky/python-uncompyle6#461]
When I use the tool to decompiler a pyc file, the result of .py file just have a sentence: Unknown magic number 3495 in Demand_Change_Report.pyc. How to fix it? I have tried several methods and change the .pyc' s magical code. All failed. Please help me.
<img width="502" alt="image" src="https://github.com/rocky/python-uncompyle6/assets/77840338/0dff6137-a394-4a2e-8327-15c1016f9dcd">

**Comment by rocky** [comment]
The first thing you probably need to do to is learn how to read and follow instructions. 

If you were to have followed instructions the problem would have been clearer.  The weird error message comes from the fact that 3.11 support in xdis is only in the current git master version of xdis and you are not using that. 

However, while getting a new xdis will remove that message you'll just get another message saying that 3.11 is not supported. 

How to fix that? Well, you could write code to support 3.11, if you can't do that support the project, or if you don't want to do that, hire some programmer of your choosing to do that. ;-)   This too has been mentioned elsewhere ad nausium.
