### ISSUE TITLE
Traceback (most recent call last):   File "<frozen runpy>", line 198, in _run_module_as_main   File "<frozen runpy>", line 88, in _run_code

### ISSUE THREAD

**Issue by khoixgod** [rocky/python-uncompyle6#463]
as the title, after i run the command "uncompyle6" its gives me that

**Comment by rocky** [comment]
Read and follow the information in  https://github.com/rocky/python-uncompyle6/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
