### ISSUE TITLE
Deparsing stopped due to parse error + Parse error at or near `POP_JUMP_IF_TRUE' instruction at offset 928_930

### ISSUE THREAD

**Issue by sooooooph** [rocky/python-uncompyle6#472]
## Description
When decompiling a specific file, the error in the title is output.

## How to Reproduce
The file was extracted from taget.exe

I used:
```
uncompyle6  target.pyc
```
Output is
```
Parse error at or near `POP_JUMP_IF_TRUE' instruction at offset 928_930
```
and
```
# file C:\Users\target.pyc
# Deparsing stopped due to parse error
```

## Expected behavior
there was no error

## Environment
uncompyle6 3.9.0
Python 3.6.6
OS Windows 10 22H2

## Workarounds
I know it can be avoided with parseXX.py, but I don't know how to use it.
I would like to know the steps after this command.
```
uncompyle6  target.pyc
```
https://github.com/rocky/python-uncompyle6/commit/e1628d4d3a87002d1246b4d7ba7d523e9266dd44

**Comment by sooooooph** [comment]
why did you close it?

**Comment by rocky** [comment]
No bytecode and source code was attached.

**Comment by sooooooph** [comment]
Is this the information you are looking for?
```
(python366) C:\Users>uncompyle6 target.pyc
# uncompyle6 version 3.9.0
# Python bytecode version base 3.6 (3379)
# Decompiled from: Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
```

**Comment by rocky** [comment]
No, this is not bytecode attached. 

> If you are reporting a bug in decompilation, it will probably not be acted upon unless it is narrowed to a small example. You may have to do some work remove extraneous code from the source example. Most bugs can be expressed in 30 lines of code.

> Bugs are not for asking questions about a problem you are trying to solve that involve the use of uncompyle6 along the way, although I may be more tolerant of this if you sponsor the project.
