### ISSUE TITLE
just became a sponsor and need help to uncompyle python 3.11 exe file

### ISSUE THREAD

**Issue by Kingkhan14** [rocky/python-uncompyle6#474]
how to get to you and i want my script to be uncompiled plz reply asap

**Comment by rocky** [comment]
Thanks for the sponsorship - here is the situation for 3.11. 

I do have some 3.9 and 3.10 fragments of byte bytecode that I can decompile, there is not that much difference between 3.8 which I have been reworking privately.

I haven't seriously looked at 3.11 beyond changes to the assembly format. Sending mail to python.decompiler39plus@gmail.com is the best way to discuss things that you would like keep private.

**Comment by Kingkhan14** [comment]
Ya will do let's talk on mail bro

**Comment by Kingkhan14** [comment]
sent u on the mails please check...

**Comment by rocky** [comment]
Time to time I get requests like the above. What tends to happen in with requests like this is that promises are as broken as easily as they are made.

Therefore folks should know that in the future, payment will be required in advance of consultation or service.
