### ISSUE TITLE
liberapay link ?

### ISSUE THREAD

**Issue by fenugrec** [rocky/python-uncompyle6#481]
You mentioned you had some liberapay donations coming in, do you still have a profile on there ? Would prefer using that over github's sponsorship/billing mechanism.

**Comment by fenugrec** [comment]
I should say - I probably found it, https://liberapay.com/rocky/ , but would like to confirm it is still valid and under your control (one never knows these days...)

**Comment by rocky** [comment]
> You mentioned you had some liberapay donations coming in, do you still have a profile on there ? Would prefer using that over github's sponsorship/billing mechanism.

Either is fine.

**Comment by fenugrec** [comment]
Thanks. Sent a few peanuts - barely makes up for some of the incredibly rude people spamming  "hey bro pls support 3.9 bro "  tickets . Hope this gets a bit more traction, but I know exactly how hard it is (I've crowdfunded some OSS things in recent years). Can't help with the nitty-gritty unfortunately, I'm more of a C guy.

**Comment by rocky** [comment]
I will be giving a talk at [Black Hat Asia on this](https://www.blackhat.com/asia-24/briefings/schedule/index.html). So I will be picking up work on this in preparation. 

Thanks for the donation.  I greatly appreciate it.
