### ISSUE TITLE
Unsupported Python version, 3.11, for decompilation

### ISSUE THREAD

**Issue by vkchahar** [rocky/python-uncompyle6#493]
uncompyle6 version 3.9.1
 Python bytecode version base 3.11 (3495)
 Decompiled from: Python 3.11.0 (main, Mar 23 2024, 20:50:59) [GCC 9.4.0]
 Embedded file name: ToolChain_V1.py
 Compiled at: 2023-11-09 15:49:25
 Size of source mod 2**32: 17856 bytes

Unsupported Python version, 3.11, for decompilation

 Unsupported bytecode in file ToolChain_V1.pyc
 Unsupported Python version, 3.11, for decompilation

**Comment by xianxiaoyin** [comment]
我也遇到了相同的问题，请问这个怎么解决？

**Comment by rocky** [comment]
> 我也遇到了相同的问题，请问这个怎么解决？

您也不閱讀或遵循說明

**Comment by LY1806620741** [comment]
> Unsupported Python version, 3.11, for decompilation 我也遇到了相同的问题，请问这个怎么解决？

作者目前没有精力兼容3.9+以上版本，请自行努力，或者自己贡献时间精力
