### ISSUE TITLE
uncompyle6 / decompile / issue

### ISSUE THREAD

**Issue by NISKULAT** [rocky/python-uncompyle6#497]
Hello, rocky! When decompiling with uncompyle6 I don't get full-fledged code, I get only some disassembled code and an error at the end of decompilation (IndexError: tuple index out of range). The file is written in python 3.6 and was obfuscated with pyarmor. I have successfully deobfuscated it and cannot get it to decompile correctly. Please tell me what the error may be, I am ready to discuss the issue from the financial side. If you are ready to help, write me: 
my email - amxtory@gmail.com
my discord - amxtory

**Comment by rocky** [comment]
Please read the last two paragraphs of https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md#confidentiality-of-bug-reports.

 Most people find these rates a bit high (although this is in line with what I was making as a professional programmer doing work that many could also do.)
