### ISSUE TITLE
Missing comma.

### ISSUE THREAD

**Issue by BoubQC** [rocky/python-uncompyle6#57]
Had an error decompiling a library. Here is a repro case where the decompiled file is not the same as the original. Would it be possible to fix it?

Original file
```python
def some_function():
    return ['some_string']

def some_other_function():
    some_variable, = some_function()
    print(some_variable)
```

Decompiled file
```python
# Python bytecode 2.7 (62211) disassembled from Python 2.7
# Embedded file name: E:/Junk/Uncompyle6_repro\some_file_original.py
# Compiled at: 2016-10-04 15:35:56


def some_function():
    return ['some_string']


def some_other_function():
    some_variable = some_function()
    print some_variable
```

Look at the comma after the 'some_variable' declaration in the source file, missing in the decompiled file. Personally would have coded it differently but eh... 

[repro.zip](https://github.com/rocky/python-uncompyle6/files/509353/repro.zip)

Thanks a lot for your help.

**Comment by BoubQC** [comment]
some_variable should equal 'some_string' while some_function returns ['some_string']

**Comment by rocky** [comment]
Thanks for reporting the problem. I see what's wrong and have corrected this on my laptop. I just need to add some tests and polish some things which I'll do when I get a chance.

**Comment by rocky** [comment]
@BoubQC Double check that commit d2b477a addresses and close this if it does.

**Comment by BoubQC** [comment]
@rocky Working great. Thanks.
