### ISSUE TITLE
Breakage with xdis 3.2.0

### ISSUE THREAD

**Issue by adamchainz** [rocky/python-uncompyle6#61]
I have this library installed for using hypothesis in one of my projects. Today I tried upgrading to the latest `xdis` (3.2.0) and got this breakage:

```
self = <uncompyle6.scanners.scanner27.Scanner27 object at 0x7fb928b3f790>
op = 12
    def op_size(self, op):
        """
            Return size of operator with its arguments
            for given opcode <op>.
            """
>       if op < self.opc.HAVE_ARGUMENT and op not in self.opc.hasArgumentExtended:
E       AttributeError: 'module' object has no attribute 'hasArgumentExtended'
```

Full stack trace can be seen here on Travis: https://travis-ci.org/adamchainz/mariadb-dyncol/builds/170691586

**Comment by rocky** [comment]
Very sorry for the breakage. Need to be more careful in the future. I've just put out a new release of uncompyle6, version 2.9.3, to address the API breakage. 

If that addresses, close this, or leave open for a while and then close

**Comment by adamchainz** [comment]
Build passed now on adamchainz/mariadb-dyncol#58, thanks! I understand it can be tricky developing two interdependent libraries. One suggestion would be to fix the version of `xdis` more strictly here. The current setup in your `__pkginfo__` would allow it to even use a version 4.0.0 which could presumably have a breaking change... https://github.com/rocky/python-uncompyle6/blob/master/__pkginfo__.py#L41

**Comment by rocky** [comment]
So the suggestion is to bump xdis to 4.0.0 and uncompyle6 to use that. Right?

**Comment by moagstar** [comment]
@adamchainz Correct me if I'm wrong, but I think the suggestion is to be more restrictive about the version pinning, by specifying an upper bound on the versions of xdis (and I guess spark-parser) allowed rather than anything >= the currently supported version, something along the lines of...

```python
install_requires   = ['spark-parser >= 1.4.0, < 1.5.0 ', 'xdis >= 3.1.0, < 3.2.0']
```

would probably have prevented this problem when installing uncompyle6 2.9.2, while still allowing patch releases of xdis or spark-parser for bug fixes.

**Comment by adamchainz** [comment]
Yes @moagstar I was suggesting what you have put so much more eloquently

**Comment by rocky** [comment]
Commit 1a38d3d  tries to address this. Double check though.

**Comment by adamchainz** [comment]
LGTM!
