### ISSUE TITLE
directly pass code objects

### ISSUE THREAD

**Issue by abbbi** [rocky/python-uncompyle6#65]
hi there,

im pretty new to fiddling with python bytecode. However i have binary file whose format seems to be
clutched with some more stuff, it is missing the correct python magic and so on.. so it is not a regular
pyc. Its been created by pyinstaller on a windows system so encodings also a bit different.. Unompyle
complains about wrong format, I can however unmarshal the code so i end
up having a code object:

>>> code
<code object <module> at 0x7ff718016270, file "main.py", line 3>

which of course can be disassembled using dis.dis()

Now i wonder: is there a way i can transform back to source using uncompyle6 by make
it use the code object directly or dumped disassambled code? 

Thank you

**Comment by rocky** [comment]
The top-level function in uncompyle6 which will disassemble f code object is [`uncompyle6.disas.disco`](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/disas.py#L31). 

You will need to know which version of python the code uses and whether it was compiled with PyPI.

**Comment by abbbi** [comment]
thanks, that works like a charm and dumps the instructions, do i need it to pass it to some parser as a next step to generate actual source from them?

**Comment by rocky** [comment]
Ooops - sorry I gave you the wrong function name. Good to see you figured it out though.
