### ISSUE TITLE
Getting more Publicity and users for UnCompyle6.

### ISSUE THREAD

**Issue by clozinski** [rocky/python-uncompyle6#85]
How can we get more publicity and users for UnCompyle6?

I saw that  your Awesome Python pull  request 
https://github.com/vinta/awesome-python/pull/809

is still open.  Bummer.  So how can we get your more publicity and users?

How about a link exchange?

https//Pylang.info 

is the world's largest Python directory.  It starts off with the Awesome Python information, and adds additional links.   It lists not just libraries, but also blogs videos, articles and other interesting content.   It is a much deeper and richer hierarchy than the github pages. I invite you to watch the lightening talk video on the web site. 

PyLang is also just starting to list companies that are doing Python development.  To learn more about tha softwre for listing companies, I invite you to take a look at the video on the sister site

https://ioscompanies.info

Please let me know if you are interested in a link exchange. 

This offer applies to all Python (or iOS) related Blogs, Articles and Libraries. 

Warm Regards
Christopher Lozinski

**Comment by rocky** [comment]
While Pylang looks interesting, right now, I'm not looking for more publicity or users.
