### ISSUE TITLE
Parse error at or near `COME_FROM_EXCEPT_CLAUSE'

### ISSUE THREAD

**Issue by Zm908** [rocky/python-uncompyle6#88]
Buggy file is attached (this is actually a cmd.py from the standard library)
[COME_FROM_EXCEPT_CLAUSE.zip](https://github.com/rocky/python-uncompyle6/files/905677/COME_FROM_EXCEPT_CLAUSE.zip)

**Comment by rocky** [comment]
Should be fixed by a9f7a3c
