### ISSUE TITLE
A bunch of errors from Python 3.5 standard library

### ISSUE THREAD

**Issue by Zm908** [rocky/python-uncompyle6#96]
I tried to decompile Python 3.5 standard library and found some bugs. So I want to report them. There are .py, .pyc and the decompiler output for each bug.
[errors.zip](https://github.com/rocky/python-uncompyle6/files/910370/errors.zip)

**Comment by rocky** [comment]
Please break this out into one issue per problem. 

It has never been particular hard to find a program that this or for that matter any of the other Python decompilers fail on. What _is_ helpful is isolating the problems. 

See https://github.com/rocky/python-uncompyle6/tree/master/test/simple_source/bug35 for examples of bugs isolated, say,  to Python 3.5.
