### ISSUE TITLE
otp\avatar\LocalAvatar.pyc from toontowninfinite: Parse error at or near `POP_TOP' instruction at offset 507 (Python 2.4)

### ISSUE THREAD

**Issue by AnythingTechPro** [rocky/python-uncompyle6#97]
[PARSE_ERROR_POP_TOP.pyc.zip](https://github.com/rocky/python-uncompyle6/files/913982/PARSE_ERROR_POP_TOP.pyc.zip)

**Comment by rocky** [comment]
In order for me to be able to fix this, I'd need the corresponding source code. Don't have it? Well decompile that part by hand, or find something similar that you have source code to.

**Comment by AnythingTechPro** [comment]
Here is the source code dump which i've uploaded on dropbox; https://dl.dropboxusercontent.com/u/3925811/py2.rar

**Comment by rocky** [comment]
Ok. But which of the 100's of files in that are we talking about? Ideally, I'd like just the source to the function(s) that aren't decompiling.

**Comment by rocky** [comment]
Oh wait, in theory it probably is `otp/avatar/LocalAvatar.pyc.py` but it looks like when you ran uncompyle2 the last time to get that, uncompyle2 had the same problem in the same place too. 

So again, what's the _real_ source to this?

**Comment by rocky** [comment]
And https://github.com/ToontownInfinite/src/blob/master/otp/avatar/LocalAvatar.py#L364 seems to have code that when compiled for Python 2.4 produces a similar problem.

**Comment by AnythingTechPro** [comment]
The source code is located in packages, toontown and otp. The reason I want to decompile this source code is because this source code was dumped from a "test" client and is a lot different.
