### ISSUE TITLE
PEP 448 - Additional Unpacking Generalizations for dictionaries (BUILD_MAP_UNPACK error)

### ISSUE THREAD

**Issue by Zm908** [rocky/python-uncompyle6#98]
[BUILD_MAP_UNPACK.zip](https://github.com/rocky/python-uncompyle6/files/920387/BUILD_MAP_UNPACK.zip)

**Comment by rocky** [comment]
03498963d49721718913000bdfb6c093158b3ea4 solves this particular situation, but more work is needed for similar kinds of uses. Right now I'm not sure how one can distinguish these looking at the bytecode.

**Comment by rocky** [comment]
Think this is fully fixed now.

**Comment by Zm908** [comment]
Still there is a problem with unpacking dict comprehension, e.g. {**{0:0 for a in b}}

[BUILD_MAP_UNPACK.zip](https://github.com/rocky/python-uncompyle6/files/966195/BUILD_MAP_UNPACK.zip)

**Comment by rocky** [comment]
364827a  should address this

**Comment by Zm908** [comment]
The latter commit gives triple * when decompiling  `{**{0:0 for a in b}}` :
`{***{0:0 for a in b}}`

**Comment by Zm908** [comment]
Also there is a problem when trying to construct dictionary in such a way: `{**{}, **{}}`. This construction generates parser error.

**Comment by Zm908** [comment]
Unfortunately `{**{}, **{}}` is decompiled to `{**{}}`
Also, `{**{0:0 for a in b}, **{}}` still generates BUILD_MAP_UNPACK error

**Comment by rocky** [comment]
It will be a while before handling BUILD_MAP_UNPACK and PEP 448 will be fully addressed. 

If you feel you can do better, by all means submit a merge request. Or there there is another python decompiler out there that handles this better, by all means use that.
