### ISSUE TITLE
CALL_FUNCTION_EX error

### ISSUE THREAD

**Issue by Zm908** [rocky/python-uncompyle6#99]
[CALL_FUNCTION_EX.zip](https://github.com/rocky/python-uncompyle6/files/920390/CALL_FUNCTION_EX.zip)

**Comment by rocky** [comment]
This is subsumed by #58. 

 @moagstar  I believe you are handling this. Do want this as two tickets. We could either keep this and remove it from #58 or add this to #58. You're choice.

**Comment by moagstar** [comment]
I added the attachment to #58 I can use it to verify the eventual fix. Doesn't seem worth keeping two issues lying round. @Zm908 thanks for the test code.
